In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import cobra
from cobra.core.configuration import Configuration
from cobra.io import read_sbml_model, write_sbml_model
from cobra.flux_analysis import flux_variability_analysis
from tqdm import tqdm

In [12]:
M_xanthus = read_sbml_model("../M_xanthus_model_V4.xml")
M_xanthus

In [13]:
M_xanthus.summary()

In [14]:
iMAT_res = pd.read_csv(
    "/home/mickael/github/M_xanthus-E_coli-Predation/results/Model_V4_iMAT/Ec1/epsilon_1.0_quantiles_40_70.tsv",
    sep="\t",
)
# iMAT_res = pd.read_csv("/home/mickael/github/M_xanthus-E_coli-Predation/results/iMat/reactionData_classification_name.csv", sep=";", index_col="Unnamed: 0")
iMAT_res

     reaction_id  flux_value classification  y_f  y_r
0     rxn02201_c    0.000000            low  1.0  0.0
1     rxn00351_c    1.084850           high  1.0  0.0
2     rxn07431_c    1.000000           high  1.0  0.0
3     rxn00836_c   -1.000000           high  0.0  1.0
4     rxn01094_c    0.000000            low  1.0  0.0
...          ...         ...            ...  ...  ...
1334  rxn30548_c    0.000000            NaN  NaN  NaN
1335  rxn09888_c    1.333333            NaN  NaN  NaN
1336  rxn06033_c   -1.000000            NaN  NaN  NaN
1337   EX_hdca_e -152.180850            NaN  NaN  NaN
1338  rxn08704_c  152.180850       moderate  NaN  NaN

[1339 rows x 5 columns]

In [15]:
iMAT_res_filter = iMAT_res[
    iMAT_res.flux_value != 0
]  # take all the flux different from 0 (so active one)
# iMAT_res_filter = iMAT_res[iMAT_res.flux != 0]
iMAT_res_filter

     reaction_id  flux_value classification  y_f  y_r
1     rxn00351_c    1.084850           high  1.0  0.0
2     rxn07431_c    1.000000           high  1.0  0.0
3     rxn00836_c   -1.000000           high  0.0  1.0
7     rxn00364_c    7.330270       moderate  NaN  NaN
9     rxn03408_c    1.701158            NaN  NaN  NaN
...          ...         ...            ...  ...  ...
1332  rxn00899_c   -1.000000           high  0.0  1.0
1335  rxn09888_c    1.333333            NaN  NaN  NaN
1336  rxn06033_c   -1.000000            NaN  NaN  NaN
1337   EX_hdca_e -152.180850            NaN  NaN  NaN
1338  rxn08704_c  152.180850       moderate  NaN  NaN

[538 rows x 5 columns]

In [16]:
# # Create dictionary to convert name to id
# Dico_reaction = {}
# for i in M_xanthus.reactions._dict:
#     Dico_reaction[M_xanthus.reactions.get_by_id(i).name] = i
# print(Dico_reaction)

# # create a list of reaction id that should have flux
# active_list = []
# for i in iMAT_res_filter["reaction_id"]:
#     active_list.append(Dico_reaction[i])
# print(active_list)

Check reaction bounds and change the bounds (0.0, 0.0) looking at ModelSeed

In [17]:
# create a list of reaction id that should have flux
active_list = []
for i in iMAT_res_filter["reaction_id"]:
    active_list.append(i)
print(active_list)

['rxn00351_c', 'rxn07431_c', 'rxn00836_c', 'rxn00364_c', 'rxn03408_c', 'rxn00646_c', 'rxn01673_c', 'rxn02342_c', 'rxn05156_c', 'rxn03239_c', 'rxn05457_c', 'rxn00199_c', 'rxn01358_c', 'rxn00172_c', 'rxn02168_c', 'rxn00800_c', 'rxn08333_c', 'rxn01705_c', 'rxn00192_c', 'rxn02898_c', 'rxn10336_c', 'rxn02504_c', 'rxn00262_c', 'rxn05040_c', 'rxn02988_c', 'rxn04792_c', 'rxn00165_c', 'rxn01117_c', 'rxn11268_c', 'rxn00710_c', 'rxn02305_c', 'rxn00910_c', 'rxn01129_c', 'rxn01297_c', 'rxn08796_c', 'rxn08941_c', 'rxn03181_c', 'rxn02331_c', 'rxn06493_c', 'rxn00337_c', 'rxn03248_c', 'rxn08127_c', 'rxn00416_c', 'rxn02376_c', 'rxn12512_c', 'rxn01739_c', 'rxn02679_c', 'rxn01974_c', 'rxn08971_c', 'rxn00060_c', 'rxn00148_c', 'rxn00100_c', 'rxn05560_c', 'rxn08976_c', 'rxn00781_c', 'rxn05298_c', 'rxn02264_c', 'rxn09202_c', 'rxn01451_c', 'rxn00097_c', 'rxn02212_c', 'rxn00695_c', 'rxn10481_c', 'rxn00692_c', 'rxn01492_c', 'rxn00802_c', 'rxn08440_c', 'rxn01825_c', 'rxn02720_c', 'rxn00178_c', 'rxn01362_c', 'rxn05161_c', 'rxn00549_c', 'rxn10060_c', 'rxn01354_c', 'rxn00305_c', 'rxn00612_c', 'rxn05461_c', 'rxn00917_c', 'rxn00300_c', 'rxn01925_c', 'rxn08799_c', 'rxn05957_c', 'rxn05335_c', 'rxn01516_c', 'rxn05595_c', 'rxn03245_c', 'rxn05458_c', 'rxn02404_c', 'rxn01644_c', 'rxn02911_c', 'rxn09188_c', 'rxn08822_c', 'rxn05030_c', 'rxn05345_c', 'rxn01465_c', 'rxn10204_c', 'rxn05145_c', 'rxn01872_c', 'rxn01643_c', 'rxn00248_c', 'rxn00707_c', 'rxn00369_c', 'rxn01637_c', 'rxn00566_c', 'rxn01269_c', 'rxn00392_c', 'rxn00747_c', 'rxn01334_c', 'rxn00830_c', 'rxn00029_c', 'rxn06777_c', 'rxn02175_c', 'rxn02774_c', 'rxn01575_c', 'rxn03240_c', 'rxn09562_c', 'rxn01501_c', 'rxn00555_c', 'rxn03080_c', 'rxn10011_c', 'rxn01256_c', 'rxn00213_c', 'rxn01629_c', 'rxn00777_c', 'rxn05164_c', 'rxn01740_c', 'rxn00190_c', 'rxn01444_c', 'rxn02314_c', 'rxn08801_c', 'rxn00251_c', 'rxn00790_c', 'rxn00237_c', 'rxn00463_c', 'rxn08311_c', 'rxn01146_c', 'rxn09210_c', 'rxn00285_c', 'rxn00182_c', 'rxn01045_c', 'rxn00712_c', 'rxn08615_c', 'rxn00126_c', 'rxn01871_c', 'rxn00299_c', 'rxn08546_c', 'rxn03159_c', 'rxn00875_c', 'rxn01000_c', 'rxn03397_c', 'rxn08128_c', 'rxn01706_c', 'rxn11703_c', 'rxn01300_c', 'rxn00786_c', 'rxn01100_c', 'rxn00838_c', 'rxn01255_c', 'rxn10014_c', 'OF_PROTEIN', 'rxn00527_c', 'rxn05151_c', 'rxn01917_c', 'rxn03253_c', 'rxn01509_c', 'rxn02011_c', 'rxn08528_c', 'rxn01669_c', 'rxn00187_c', 'rxn00006_c', 'rxn00915_c', 'rxn01515_c', 'rxn00994_c', 'rxn01653_c', 'rxn03147_c', 'rxn03843_c', 'rxn02317_c', 'rxn01116_c', 'rxn00829_c', 'rxn01544_c', 'rxn09113_c', 'rxn01138_c', 'rxn02402_c', 'rxn01607_c', 'rxn05465_c', 'rxn05148_c', 'rxn06077_c', 'rxn08126_c', 'rxn05732_c', 'rxn01303_c', 'rxn00113_c', 'rxn00137_c', 'rxn00745_c', 'rxn06023_c', 'rxn00611_c', 'rxn01678_c', 'rxn02286_c', 'rxn00872_c', 'rxn00832_c', 'rxn01106_c', 'rxn00690_c', 'rxn00066_c', 'rxn10012_c', 'rxn04938_c', 'rxn05115_c', 'rxn00412_c', 'rxn01573_c', 'rxn00650_c', 'rxn03167_c', 'rxn00515_c', 'rxn01353_c', 'rxn03244_c', 'rxn06723_c', 'rxn00775_c', 'rxn02680_c', 'rxn00804_c', 'rxn11040_c', 'rxn02895_c', 'rxn00189_c', 'rxn01508_c', 'rxn02508_c', 'rxn00420_c', 'rxn14334_c', 'rxn00993_c', 'rxn00469_c', 'rxn02804_c', 'rxn05005_c', 'rxn00048_c', 'rxn05231_c', 'rxn00283_c', 'rxn00726_c', 'rxn00184_c', 'rxn01025_c', 'rxn02155_c', 'rxn02475_c', 'rxn05460_c', 'rxn03108_c', 'rxn01018_c', 'rxn03247_c', 'rxn00278_c', 'rxn01476_c', 'rxn00205_c', 'rxn03146_c', 'rxn00410_c', 'rxn01333_c', 'rxn12510_c', 'rxn05342_c', 'rxn00414_c', 'rxn00799_c', 'rxn02405_c', 'rxn00011_c', 'rxn07430_c', 'rxn02200_c', 'rxn01069_c', 'rxn00791_c', 'rxn03150_c', 'rxn00365_c', 'rxn01827_c', 'rxn05312_c', 'rxn08975_c', 'rxn03243_c', 'rxn01302_c', 'rxn05029_c', 'rxn00368_c', 'rxn02285_c', 'rxn05315_c', 'OF_DNA', 'rxn00290_c', 'rxn07466_c', 'rxn00459_c', 'rxn00770_c', 'rxn05195_c', 'rxn00076_c', 'rxn14040_c', 'rxn05209_c', 'rxn06377_c', 'rxn08444_c', 'rxn00175_c', 'rxn01366_c', 'rxn01143_c', 'rxn00260_c', 'rxn00461_c', 'rxn03136_c', 'rxn01387_c', 'rxn02937_c', 'rxn01652_c', 'rxn00350_c', 'rxn03137_c', 'rxn01115_c', 'rxn05462_c', 'rxn01128_c', 'rxn00952_c', 'rxn05006_c', 'rxn00533_c', 'rxn02476_c', 'rxn01512_c', 'rxn03841_c', 'rxn04954_c', 'rxn06865_c', 'rxn03249_c', 'rxn00713_c', 'rxn01257_c', 'rxn00943_c', 'rxn00903_c', 'rxn01648_c', 'rxn02213_c', 'rxn00086_c', 'rxn01127_c', 'rxn00615_c', 'rxn01265_c', 'rxn00874_c', 'rxn00834_c', 'rxn00704_c', 'rxn02322_c', 'rxn08130_c', 'rxn10010_c', 'rxn11702_c', 'rxn01332_c', 'rxn01510_c', 'rxn00785_c', 'rxn00693_c', 'rxn01351_c', 'rxn03909_c', 'rxn01101_c', 'rxn03084_c', 'rxn06600_c', 'rxn03439_c', 'rxn02005_c', 'rxn00558_c', 'rxn00346_c', 'rxn01859_c', 'rxn00806_c', 'rxn05323_c', 'rxn05616_c', 'rxn01790_c', 'rxn05651_c', 'rxn00077_c', 'rxn01388_c', 'rxn03638_c', 'rxn01446_c', 'rxn02056_c', 'rxn00991_c', 'rxn03242_c', 'rxn00301_c', 'rxn00141_c', 'rxn01200_c', 'rxn01241_c', 'rxn00438_c', 'rxn01434_c', 'rxn00912_c', 'rxn02345_c', 'rxn00122_c', 'rxn06076_c', 'rxn05179_c', 'rxn03241_c', 'rxn01521_c', 'rxn02276_c', 'rxn00338_c', 'rxn00119_c', 'rxn00709_c', 'rxn08549_c', 'rxn01466_c', 'rxn01674_c', 'rxn00974_c', 'rxn00605_c', 'rxn00744_c', 'rxn02008_c', 'rxn05740_c', 'rxn03904_c', 'rxn01679_c', 'rxn10199_c', 'rxn00409_c', 'rxn02831_c', 'rxn01258_c', 'OF_RNA', 'rxn00840_c', 'rxn03901_c', 'rxn01985_c', 'rxn10013_c', 'rxn02832_c', 'rxn10052_c', 'rxn00946_c', 'rxn00193_c', 'rxn05114_c', 'rxn03164_c', 'rxn03251_c', 'rxn00256_c', 'rxn08335_c', 'rxn03004_c', 'rxn00138_c', 'rxn08942_c', 'rxn06729_c', 'rxn05168_c', 'rxn01858_c', 'rxn01799_c', 'rxn00504_c', 'rxn01485_c', 'rxn05206_c', 'rxn09296_c', 'rxn00239_c', 'rxn00441_c', 'rxn03250_c', 'rxn02465_c', 'rxn03130_c', 'rxn01791_c', 'rxn02507_c', 'rxn08131_c', 'rxn05464_c', 'rxn00990_c', 'rxn14333_c', 'rxn01964_c', 'rxn02341_c', 'rxn01137_c', 'rxn03182_c', 'rxn01343_c', 'rxn06510_c', 'rxn00209_c', 'rxn02474_c', 'rxn03246_c', 'rxn00604_c', 'rxn02929_c', 'rxn00104_c', 'rxn00715_c', 'rxn01019_c', 'rxn09014_c', 'rxn02914_c', 'rxn01603_c', 'rxn00686_c', 'rxn00117_c', 'rxn01520_c', 'rxn00330_c', 'rxn00493_c', 'rxn00293_c', 'rxn14011_c', 'rxn00839_c', 'rxn00154_c', 'rxn15395_c', 'rxn14427_c', 'rxn08098_c', 'rxn08734_c', 'rxn09003_c', 'rxn09001_c', 'rxn14415_c', 'rxn39452_c', 'rxn39451_c', 'rxn15167_c', 'rxn09037_c', 'rxn08241_c', 'rxn08234_c', 'rxn14061_c', 'rxn13957_c', 'rxn26127_c', 'rxn05488_c', 'rxn05559_c', 'rxn05468_c', 'rxn05467_c', 'rxn08502_e', 'rxn08691_c', 'rxn08689_c', 'rxn12225_c', 'rxn03086_c', 'rxn03030_c', 'rxn12666_c', 'rxn00470_c', 'rxn05459_c', 'rxn12603_c', 'rxn00068_c', 'rxn05514_c', 'rxn00957_c', 'rxn11946_c', 'rxn05039_c', 'rxn09128_c', 'rxn05175_c', 'rxn01972_c', 'rxn00979_c', 'rxn12224_c', 'rxn03537_c', 'rxn02990_c', 'rxn01249_c', 'rxn09106_c', 'rxn04413_c', 'rxn04139_c', 'rxn03893_c', 'rxn03538_c', 'rxn09310_c', 'rxn01213_c', 'rxn05618_c', 'rxn00181_c', 'rxn01396_c', 'rxn08655_c', 'rxn12239_c', 'rxn03393_c', 'rxn02897_c', 'rxn03395_c', 'OF_BIOMASS', 'EX_his_L_e', 'EX_metox_e', 'EX_mg2_e', 'EX_ac_e', 'EX_h2s_e', 'EX_so4_e', 'EX_pydx_e', 'EX_spmd_e', 'EX_ppi_e', 'EX_orn_e', 'EX_pi_e', 'EX_leu_L_e', 'EX_h2_e', 'EX_lys_L_e', 'EX_k_e', 'EX_cu2_e', 'EX_Fe3_e', 'EX_fru_e', 'EX_alaala_e', 'EX_co2_e', 'EX_h_e', 'EX_ca2_e', 'EX_zn2_e', 'EX_cl_e', 'EX_tre_e', 'EX_pheme_e', 'EX_glu_L_e', 'EX_feenter_e', 'EX_mn2_e', 'EX_enter_e', 'EX_for_e', 'EX_ile_L_e', 'EX_cobalt2_e', 'EX_val_L_e', 'EX_o2_e', 'DM_Biomass_c', 'rxn01375_c', 'rxn00899_c', 'rxn09888_c', 'rxn06033_c', 'EX_hdca_e', 'rxn08704_c']

Shut down all others reactions

In [18]:
for i in M_xanthus.reactions:  # Shut down all the non active reaction
    if i.id not in active_list:
        i.bounds = [0, 0]
list_blocked = cobra.flux_analysis.find_blocked_reactions(M_xanthus)

M_xanthus.optimize()  # Didn't growth

In [20]:
# cobra.flux_analysis.gapfill(M_xanthus, universal=M_xanthus_ref, exchange_reactions= True, demand_reactions=True, )

Force to activate specific reaction

In [22]:
# Add constraint that force the fluxe to pass there / Infeasable
y = M_xanthus.problem.Variable("y_RXN", type="binary")  # add a binary constraint
M_xanthus.add_cons_vars(y)

for i in active_list:
    have_flux = M_xanthus.problem.Constraint(
        M_xanthus.reactions.get_by_id(i).flux_expression
        - 1
        + 1000
        * (
            1 - y
        ),  # - 1 [threshold] + 1000 [big number] * (1 - y) [if 1 = big number] [if 0 = - big number]
        lb=0,
        ub=0,
    )  # force the reaction to have at least 1 (or -1?) flux
    M_xanthus.add_cons_vars(have_flux)

M_xanthus.solver.update()

In [23]:
M_xanthus.optimize()

/home/mickael/miniconda3/envs/Micka_Predation/lib/python3.12/site-packages/cobra/util/solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

## **New Data**

python3 IntegrationPackage/main.py weighted_iMAT -f 'data/Raw/WT_vs_4preys.txt' -g 'GeneNames' -i 'W1' -m 'M_xanthus_model_V3_hdca_iMAT.xml' -o results/ -d "quantile"

In [24]:
DataTable = pd.read_csv(
    "/home/mickael/github/M_xanthus-E_coli-Predation/data/Raw/WT_vs_4preys.txt",
    sep="\t",
)
DataTable

,GeneNames,Ec1,Ec2,Ec3,B1,B2,B3,C1,C2,C3,...,W3,K1,K2,K3,WC1,WC2,WC3,KC1,KC2,KC3
0,WP_002614080.1,13032,13136,12917,18050,22828,16816,42888,32404,20170,...,60053,35638,38908,37314,15344,15530,27018,17185,13886,9121
1,WP_002614803.1,6817,5982,6246,15018,16718,18070,29227,34305,9713,...,69546,28536,31303,34021,19022,19870,35902,12388,22264,17843
2,WP_002633201.1,275,195,239,521,550,406,1140,727,386,...,2409,838,832,531,1110,995,1063,1841,1027,766
3,WP_002633598.1,15516,14792,13306,28206,30917,22916,64389,58243,23106,...,62136,27039,28864,34478,7962,9148,24438,4169,7524,7193
4,WP_002633601.1,4095,2680,1969,8170,8806,14771,20987,18394,9361,...,17038,13309,11109,20035,3338,2187,11373,3164,2406,4588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7184,WP_141276995.1,31,36,108,26,31,49,93,69,45,...,76,29,39,42,29,26,39,23,19,33
7185,WP_141277062.1,11,13,46,11,17,4,43,46,17,...,79,10,15,13,14,33,26,17,19,31
7186,WP_143049088.1,1332,1512,1834,2258,2340,1791,4704,5134,1659,...,13345,3235,3431,2941,4105,5714,3841,9265,5144,6080
7187,WP_143049089.1,46,26,305,79,90,72,154,115,44,...,196,89,63,71,102,60,67,100,47,93
7188,WP_143049094.1,918,2104,1781,1836,1928,1194,3263,3999,1372,...,3892,452,531,460,1444,3448,1236,264,711,468

In [25]:
DicoTable = pd.read_csv(
    "/home/mickael/github/M_xanthus-E_coli-Predation/data/RNA_seq_DE_result/WT_vs_Ecol_ratio1_3.csv",
    sep=";",
)
DicoTable

,gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,Gene_name,GeneID,orgdb_symbol,orgdb_old_MXAN,orgdb_Name
0,WP_002614080.1,"17681,5595400946","1,13148580809734","0,333820387052008","3,38950481152327","0,000700189800953942","0,00401749202195971",MXAN_RS25275,41362483.0,MXAN_RS25275,MXAN_5201,30S ribosomal protein S21
1,WP_002614803.1,"13055,8658450867","-0,279785484378841","0,341134653438939","-0,820161427630867","0,41212408777437","0,55634844891773",MXAN_RS16100,41360674.0,infA,MXAN_3321,translation initiation factor IF-1
2,WP_002633201.1,"520,781350902195","-0,488659406109829","0,310280848578043","-1,57489386905206","0,115280944069584","0,223684953832229",MXAN_RS31645,41363738.0,MXAN_RS31645,MXAN_6531,HPr family phosphocarrier protein
3,WP_002633598.1,"17667,1430239249","1,78674248251241","0,432318538781286","4,1329305181991","3,58167027156953e-05","0,000318057858780743",MXAN_RS16040,41360662.0,MXAN_RS16040,MXAN_3309,50S ribosomal protein L14
4,WP_002633601.1,"4426,40026145906","0,8104626466811","0,545743984534573","1,48506015576569","0,13752788957159","0,253668278115051",MXAN_RS16025,41360659.0,MXAN_RS16025,MXAN_3306,50S ribosomal protein L16
...,...,...,...,...,...,...,...,...,...,...,...,...
6886,WP_141276995.1,"55,5707618478865","2,38043768070863","0,546005542238998","4,35973171801004","1,30221996444244e-05","0,000133398790047742",NaN,NaN,NaN,NaN,NaN
6887,WP_141277062.1,"25,2414912393685","1,38263010290852","0,762769321629563","1,81264513884054","0,0698865710503559","0,155014402646007",NaN,NaN,NaN,NaN,NaN
6888,WP_143049088.1,"2729,23193040998","0,100695081633711","0,293071005956888","0,343585955577344","0,7311576882233","0,819386506675355",MXAN_RS19445,41361331.0,NaN,NaN,NaN
6889,WP_143049089.1,"109,891161452436","2,01788957892024","0,643239069754101","3,1370755816988","0,0017064213158805","0,008435401210712",NaN,NaN,NaN,NaN,NaN
6890,WP_143049094.1,"2090,89896910754","1,32918118754963","0,466747524468472","2,84775198125216","0,00440292229873144","0,0182225450814164",MXAN_RS37770,41364889.0,NaN,NaN,NaN

In [26]:
dico_genes = {}
for i in range(len(DicoTable)):
    dico_genes.update({DicoTable.loc[i, "gene"]: DicoTable.loc[i, "orgdb_old_MXAN"]})
dico_genes

{'WP_002614080.1': 'MXAN_5201',
 'WP_002614803.1': 'MXAN_3321',
 'WP_002633201.1': 'MXAN_6531',
 'WP_002633598.1': 'MXAN_3309',
 'WP_002633601.1': 'MXAN_3306',
 'WP_002633602.1': 'MXAN_3305',
 'WP_002633603.1': 'MXAN_3304',
 'WP_002633604.1': 'MXAN_3303',
 'WP_002633606.1': 'MXAN_3301',
 'WP_002633607.1': 'MXAN_3300',
 'WP_002633608.1': 'MXAN_3299',
 'WP_002634092.1': 'MXAN_5125',
 'WP_002634160.1': 'MXAN_5074',
 'WP_002634235.1': 'MXAN_5002',
 'WP_002634367.1': 'MXAN_5592',
 'WP_002634498.1': 'MXAN_5688',
 'WP_002634858.1': 'MXAN_2709',
 'WP_002635080.1': 'MXAN_2913',
 'WP_002635502.1': 'MXAN_1434',
 'WP_002635980.1': 'MXAN_0672',
 'WP_002636238.1': 'MXAN_0403',
 'WP_002636478.1': 'MXAN_4033',
 'WP_002636551.1': 'MXAN_4095',
 'WP_002636698.1': 'MXAN_4636',
 'WP_002636699.1': 'MXAN_4637',
 'WP_002636736.1': 'MXAN_4673',
 'WP_002637061.1': 'MXAN_2448',
 'WP_002637270.1': 'MXAN_1926',
 'WP_002637381.1': 'MXAN_3295',
 'WP_002637840.1': 'MXAN_7512',
 'WP_002638649.1': 'No old locus tag',
 'WP_002639025.1': 'MXAN_2528',
 'WP_002639318.1': 'No old locus tag',
 'WP_002639616.1': 'MXAN_3793',
 'WP_002639669.1': 'MXAN_3596',
 'WP_002639727.1': 'MXAN_2978',
 'WP_002640434.1': 'MXAN_4894',
 'WP_002640507.1': 'MXAN_3154',
 'WP_002640579.1': 'No old locus tag',
 'WP_002640911.1': 'MXAN_7339',
 'WP_002640925.1': 'MXAN_2457',
 'WP_011550153.1': 'MXAN_0001',
 'WP_011550154.1': 'MXAN_0002',
 'WP_011550155.1': 'MXAN_0003',
 'WP_011550156.1': 'MXAN_0004',
 'WP_011550157.1': 'MXAN_0005',
 'WP_011550158.1': 'MXAN_0008',
 'WP_011550159.1': 'MXAN_0009',
 'WP_011550160.1': 'MXAN_0010',
 'WP_011550161.1': 'MXAN_0012',
 'WP_011550162.1': 'MXAN_0013',
 'WP_011550163.1': 'MXAN_0014',
 'WP_011550164.1': 'MXAN_0015',
 'WP_011550165.1': 'MXAN_0016',
 'WP_011550166.1': 'MXAN_0017',
 'WP_011550168.1': 'MXAN_0019',
 'WP_011550169.1': 'MXAN_0020',
 'WP_011550171.1': 'MXAN_0022',
 'WP_011550173.1': 'MXAN_0024',
 'WP_011550174.1': nan,
 'WP_011550175.1': 'MXAN_0026',
 'WP_011550176.1': 'MXAN_0027',
 'WP_011550178.1': 'MXAN_0029',
 'WP_011550179.1': 'MXAN_0030',
 'WP_011550180.1': 'MXAN_0031',
 'WP_011550181.1': 'MXAN_0032',
 'WP_011550182.1': 'MXAN_0033',
 'WP_011550183.1': 'MXAN_0034',
 'WP_011550184.1': 'MXAN_0035',
 'WP_011550188.1': 'MXAN_0039',
 'WP_011550189.1': 'MXAN_0040',
 'WP_011550190.1': 'MXAN_0041',
 'WP_011550191.1': 'MXAN_0042',
 'WP_011550192.1': 'MXAN_0043',
 'WP_011550193.1': 'MXAN_0044',
 'WP_011550194.1': 'MXAN_0045',
 'WP_011550196.1': nan,
 'WP_011550197.1': 'MXAN_0048',
 'WP_011550198.1': 'MXAN_0049',
 'WP_011550199.1': 'MXAN_0050',
 'WP_011550200.1': 'MXAN_0051',
 'WP_011550201.1': 'MXAN_0052',
 'WP_011550202.1': 'MXAN_0053',
 'WP_011550203.1': 'MXAN_0054',
 'WP_011550204.1': nan,
 'WP_011550205.1': 'MXAN_0056',
 'WP_011550206.1': 'MXAN_0057',
 'WP_011550207.1': 'MXAN_0058',
 'WP_011550208.1': 'MXAN_0059',
 'WP_011550209.1': 'MXAN_0060',
 'WP_011550210.1': 'MXAN_0061',
 'WP_011550212.1': 'MXAN_0063',
 'WP_011550213.1': 'MXAN_0064',
 'WP_011550217.1': 'MXAN_0070',
 'WP_011550218.1': 'MXAN_0071',
 'WP_011550219.1': 'MXAN_0072',
 'WP_011550220.1': 'MXAN_0073',
 'WP_011550221.1': 'MXAN_0074',
 'WP_011550223.1': 'MXAN_0076',
 'WP_011550224.1': 'MXAN_0077',
 'WP_011550225.1': 'MXAN_0078',
 'WP_011550226.1': 'MXAN_0079',
 'WP_011550227.1': 'MXAN_0080',
 'WP_011550228.1': 'MXAN_0081',
 'WP_011550229.1': 'MXAN_0082',
 'WP_011550230.1': 'MXAN_0083',
 'WP_011550231.1': 'MXAN_0084',
 'WP_011550232.1': 'MXAN_0085',
 'WP_011550233.1': 'MXAN_0086',
 'WP_011550234.1': 'MXAN_0087',
 'WP_011550235.1': 'MXAN_0088',
 'WP_011550236.1': 'MXAN_0089',
 'WP_011550237.1': 'MXAN_0090',
 'WP_011550239.1': 'MXAN_0092',
 'WP_011550240.1': 'MXAN_0093',
 'WP_011550241.1': 'MXAN_0094',
 'WP_011550242.1': 'MXAN_0095',
 'WP_011550243.1': 'MXAN_0096',
 'WP_011550244.1': 'MXAN_0097',
 'WP_011550245.1': 'MXAN_0098',
 'WP_011550247.1': 'MXAN_0100',
 'WP_011550248.1': 'MXAN_0101',
 'WP_011550249.1': 'MXAN_0102',
 'WP_011550251.1': 'MXAN_0104',
 'WP_011550252.1': 'MXAN_0105',
 'WP_011550254.1': 'MXAN_0107',
 'WP_011550256.1': 'MXAN_0109',
 'WP_011550257.1': 'MXAN_0110',
 'WP_011550258.1': 'MXAN_0111',
 'WP_011550259.1': 'MXAN_0112',
 'WP_011550260.1': 'MXAN_0113',
 'WP_011550261.1': 'MXAN_0114',
 'WP_011550262.1': 'MXAN_0115',
 'WP_011550263.1': 'MXAN_0116',
 'WP_011550264.1': 'MXAN_0117',
 'WP_011550265.1': 'MXAN_0118',
 'WP_011550266.1': 'MXAN_0119',
 'WP_011550267.1': 'MXAN_0120',
 'WP_011550270.1': 'MXAN_0123',
 'WP_011550271.1': 'MXAN_0124',
 'WP_011550273.1': 'MXAN_0126',
 'WP_011550275.1': 'MXAN_0128',
 'WP_011550276.1': 'MXAN_0129',
 'WP_011550277.1': 'MXAN_0130',
 'WP_011550278.1': 'MXAN_0131',
 'WP_011550279.1': 'MXAN_0133',
 'WP_011550281.1': 'MXAN_0134',
 'WP_011550282.1': 'MXAN_0135',
 'WP_011550283.1': 'MXAN_0136',
 'WP_011550284.1': 'MXAN_0137',
 'WP_011550285.1': 'MXAN_0138',
 'WP_011550286.1': 'MXAN_0139',
 'WP_011550287.1': 'MXAN_0140',
 'WP_011550288.1': 'MXAN_0141',
 'WP_011550289.1': 'MXAN_0142',
 'WP_011550290.1': 'MXAN_0143',
 'WP_011550291.1': 'MXAN_0144',
 'WP_011550292.1': 'MXAN_0145',
 'WP_011550293.1': 'MXAN_0146',
 'WP_011550294.1': 'MXAN_0147',
 'WP_011550295.1': 'MXAN_0148',
 'WP_011550298.1': 'MXAN_0151',
 'WP_011550299.1': 'MXAN_0152',
 'WP_011550300.1': 'MXAN_0153',
 'WP_011550302.1': 'MXAN_0155',
 'WP_011550303.1': 'MXAN_0156',
 'WP_011550304.1': nan,
 'WP_011550305.1': 'MXAN_0158',
 'WP_011550306.1': 'MXAN_0159',
 'WP_011550307.1': 'MXAN_0160',
 'WP_011550309.1': 'MXAN_0162',
 'WP_011550311.1': 'MXAN_0164',
 'WP_011550312.1': 'MXAN_0165',
 'WP_011550313.1': 'MXAN_0166',
 'WP_011550314.1': 'MXAN_0167',
 'WP_011550315.1': 'MXAN_0168',
 'WP_011550317.1': 'MXAN_0170',
 'WP_011550319.1': 'MXAN_0172',
 'WP_011550320.1': 'MXAN_0173',
 'WP_011550321.1': 'MXAN_0174',
 'WP_011550322.1': 'MXAN_0175',
 'WP_011550323.1': 'MXAN_0176',
 'WP_011550326.1': 'MXAN_0179',
 'WP_011550329.1': 'MXAN_0182',
 'WP_011550330.1': 'MXAN_0183',
 'WP_011550331.1': 'MXAN_0184',
 'WP_011550332.1': 'MXAN_0185',
 'WP_011550333.1': 'MXAN_0186',
 'WP_011550334.1': 'MXAN_0188',
 'WP_011550335.1': 'MXAN_0189',
 'WP_011550339.1': 'MXAN_0193',
 'WP_011550341.1': 'MXAN_0195',
 'WP_011550342.1': 'MXAN_0196',
 'WP_011550344.1': 'MXAN_0198',
 'WP_011550345.1': 'MXAN_0199',
 'WP_011550346.1': 'MXAN_0200',
 'WP_011550347.1': 'MXAN_0201',
 'WP_011550348.1': 'MXAN_0202',
 'WP_011550349.1': 'MXAN_0203',
 'WP_011550350.1': 'MXAN_0204',
 'WP_011550351.1': 'MXAN_0205',
 'WP_011550352.1': 'MXAN_0206',
 'WP_011550353.1': 'MXAN_0207',
 'WP_011550357.1': 'MXAN_0211',
 'WP_011550358.1': 'MXAN_0212',
 'WP_011550359.1': 'MXAN_0213',
 'WP_011550360.1': 'MXAN_0214',
 'WP_011550361.1': 'MXAN_0215',
 'WP_011550363.1': 'MXAN_0217',
 'WP_011550365.1': 'MXAN_0219',
 'WP_011550366.1': 'MXAN_0220',
 'WP_011550367.1': 'MXAN_0221',
 'WP_011550368.1': 'MXAN_0222',
 'WP_011550369.1': 'MXAN_0223',
 'WP_011550371.1': 'MXAN_0225',
 'WP_011550373.1': 'MXAN_0227',
 'WP_011550374.1': 'MXAN_0228',
 'WP_011550375.1': 'MXAN_0229',
 'WP_011550376.1': 'MXAN_0230',
 'WP_011550377.1': 'MXAN_0231',
 'WP_011550378.1': 'MXAN_0232',
 'WP_011550380.1': 'MXAN_0235',
 'WP_011550381.1': 'MXAN_0236',
 'WP_011550382.1': 'MXAN_0237',
 'WP_011550383.1': 'MXAN_0238',
 'WP_011550386.1': 'No old locus tag',
 'WP_011550387.1': 'MXAN_0242',
 'WP_011550388.1': 'MXAN_0243',
 'WP_011550389.1': 'MXAN_0244',
 'WP_011550390.1': 'MXAN_0245',
 'WP_011550391.1': 'MXAN_0246',
 'WP_011550393.1': 'MXAN_0248',
 'WP_011550395.1': 'MXAN_0250',
 'WP_011550396.1': 'MXAN_0251',
 'WP_011550397.1': 'MXAN_0252',
 'WP_011550398.1': 'MXAN_0253',
 'WP_011550399.1': 'MXAN_0254',
 'WP_011550400.1': 'MXAN_0255',
 'WP_011550401.1': 'MXAN_0256',
 'WP_011550402.1': 'MXAN_0257',
 'WP_011550404.1': 'MXAN_0259',
 'WP_011550405.1': 'MXAN_0260',
 'WP_011550406.1': 'MXAN_0261',
 'WP_011550407.1': 'MXAN_0262',
 'WP_011550408.1': 'MXAN_0263',
 'WP_011550409.1': 'MXAN_0264',
 'WP_011550411.1': 'MXAN_0266',
 'WP_011550412.1': 'MXAN_0267',
 'WP_011550413.1': nan,
 'WP_011550414.1': 'MXAN_0269',
 'WP_011550416.1': 'MXAN_0271',
 'WP_011550417.1': 'MXAN_0272',
 'WP_011550418.1': 'MXAN_0273',
 'WP_011550421.1': 'MXAN_0276',
 'WP_011550422.1': 'MXAN_0277',
 'WP_011550423.1': 'MXAN_0278',
 'WP_011550424.1': 'MXAN_0279',
 'WP_011550426.1': 'MXAN_0282',
 'WP_011550427.1': 'MXAN_0283',
 'WP_011550428.1': 'MXAN_0284',
 'WP_011550429.1': 'MXAN_0285',
 'WP_011550430.1': 'MXAN_0286',
 'WP_011550432.1': 'MXAN_0288',
 'WP_011550433.1': 'MXAN_0289',
 'WP_011550434.1': 'MXAN_0290',
 'WP_011550436.1': 'MXAN_0292',
 'WP_011550437.1': 'MXAN_0293',
 'WP_011550438.1': 'MXAN_0294',
 'WP_011550439.1': 'MXAN_0295',
 'WP_011550440.1': 'MXAN_0296',
 'WP_011550441.1': 'MXAN_0297',
 'WP_011550443.1': 'MXAN_0299',
 'WP_011550444.1': 'MXAN_0300',
 'WP_011550445.1': 'MXAN_0301',
 'WP_011550446.1': 'MXAN_0302',
 'WP_011550447.1': 'MXAN_0303',
 'WP_011550448.1': 'MXAN_0304',
 'WP_011550449.1': 'MXAN_0305',
 'WP_011550450.1': 'MXAN_0306',
 'WP_011550451.1': 'MXAN_0307',
 'WP_011550452.1': 'MXAN_0308',
 'WP_011550453.1': 'MXAN_0309',
 'WP_011550455.1': 'MXAN_0311',
 'WP_011550456.1': 'MXAN_0312',
 'WP_011550457.1': 'MXAN_0313',
 'WP_011550458.1': 'MXAN_0314',
 'WP_011550459.1': 'MXAN_0315',
 'WP_011550460.1': 'MXAN_0316',
 'WP_011550461.1': 'MXAN_0317',
 'WP_011550462.1': 'MXAN_0318',
 'WP_011550463.1': 'MXAN_0324',
 'WP_011550464.1': 'MXAN_0325',
 'WP_011550465.1': 'MXAN_0326',
 'WP_011550466.1': 'MXAN_0327',
 'WP_011550467.1': 'MXAN_0328',
 'WP_011550468.1': 'MXAN_0330',
 'WP_011550469.1': 'MXAN_0331',
 'WP_011550470.1': 'MXAN_0332',
 'WP_011550471.1': 'MXAN_0333',
 'WP_011550473.1': 'MXAN_0335',
 'WP_011550474.1': 'MXAN_0336',
 'WP_011550477.1': 'MXAN_0339',
 'WP_011550479.1': 'MXAN_0341',
 'WP_011550480.1': 'MXAN_0342',
 'WP_011550481.1': 'MXAN_0343',
 'WP_011550482.1': 'MXAN_0344',
 'WP_011550483.1': 'MXAN_0345',
 'WP_011550484.1': 'MXAN_0346',
 'WP_011550486.1': 'MXAN_0348',
 'WP_011550489.1': 'MXAN_0351',
 'WP_011550490.1': 'MXAN_0352',
 'WP_011550493.1': 'MXAN_0355',
 'WP_011550496.1': 'MXAN_0358',
 'WP_011550497.1': 'MXAN_0359',
 'WP_011550498.1': 'MXAN_0360',
 'WP_011550499.1': 'MXAN_0361',
 'WP_011550501.1': 'MXAN_0363',
 'WP_011550502.1': 'MXAN_0364',
 'WP_011550503.1': 'MXAN_0365',
 'WP_011550504.1': 'MXAN_0366',
 'WP_011550506.1': 'MXAN_0368',
 'WP_011550507.1': 'MXAN_0369',
 'WP_011550509.1': 'MXAN_0371',
 'WP_011550510.1': 'MXAN_0372',
 'WP_011550512.1': 'MXAN_0374',
 'WP_011550513.1': 'MXAN_0375',
 'WP_011550514.1': 'MXAN_0376',
 'WP_011550515.1': 'MXAN_0377',
 'WP_011550516.1': nan,
 'WP_011550517.1': 'MXAN_0379',
 'WP_011550520.1': 'MXAN_0384',
 'WP_011550522.1': 'MXAN_0386',
 'WP_011550523.1': 'MXAN_0387',
 'WP_011550524.1': 'MXAN_0389',
 'WP_011550525.1': 'MXAN_0390',
 'WP_011550526.1': 'MXAN_0391',
 'WP_011550530.1': 'MXAN_0395',
 'WP_011550534.1': 'MXAN_0399',
 'WP_011550536.1': 'MXAN_0401',
 'WP_011550539.1': 'MXAN_0405',
 'WP_011550541.1': 'MXAN_0407',
 'WP_011550543.1': 'MXAN_0409',
 'WP_011550544.1': 'MXAN_0410',
 'WP_011550545.1': 'MXAN_0411',
 'WP_011550546.1': 'MXAN_0412',
 'WP_011550549.1': 'MXAN_0415',
 'WP_011550551.1': 'MXAN_0417',
 'WP_011550552.1': 'MXAN_0418',
 'WP_011550553.1': 'MXAN_0419',
 'WP_011550554.1': 'MXAN_0420',
 'WP_011550555.1': 'MXAN_0421',
 'WP_011550556.1': 'MXAN_0422',
 'WP_011550557.1': 'MXAN_0423',
 'WP_011550565.1': 'MXAN_0432',
 'WP_011550566.1': 'MXAN_0433',
 'WP_011550567.1': 'MXAN_0434',
 'WP_011550568.1': 'MXAN_0435',
 'WP_011550569.1': 'MXAN_0436',
 'WP_011550570.1': 'MXAN_0437',
 'WP_011550571.1': 'MXAN_0438',
 'WP_011550572.1': 'MXAN_0439',
 'WP_011550575.1': 'MXAN_0442',
 'WP_011550576.1': 'MXAN_0443',
 'WP_011550577.1': 'MXAN_0444',
 'WP_011550579.1': 'MXAN_0446',
 'WP_011550580.1': 'MXAN_0447',
 'WP_011550581.1': 'MXAN_0448',
 'WP_011550584.1': 'MXAN_0451',
 'WP_011550585.1': 'MXAN_0452',
 'WP_011550586.1': 'MXAN_0453',
 'WP_011550587.1': 'MXAN_0454',
 'WP_011550588.1': 'MXAN_0455',
 'WP_011550589.1': nan,
 'WP_011550590.1': 'MXAN_0457',
 'WP_011550591.1': 'MXAN_0458',
 'WP_011550592.1': 'MXAN_0459',
 'WP_011550593.1': 'MXAN_0460',
 'WP_011550594.1': 'MXAN_0461',
 'WP_011550595.1': 'MXAN_0462',
 'WP_011550596.1': 'MXAN_0463',
 'WP_011550597.1': 'MXAN_0464',
 'WP_011550599.1': 'MXAN_0466',
 'WP_011550600.1': 'MXAN_0467',
 'WP_011550601.1': 'MXAN_0468',
 'WP_011550602.1': 'MXAN_0469',
 'WP_011550603.1': 'MXAN_0470',
 'WP_011550604.1': 'MXAN_0471',
 'WP_011550606.1': 'MXAN_0473',
 'WP_011550608.1': 'MXAN_0475',
 'WP_011550609.1': 'MXAN_0476',
 'WP_011550610.1': 'MXAN_0477',
 'WP_011550611.1': 'MXAN_0478',
 'WP_011550612.1': 'MXAN_0479',
 'WP_011550613.1': 'MXAN_0480',
 'WP_011550614.1': 'MXAN_0481',
 'WP_011550615.1': 'MXAN_0482',
 'WP_011550616.1': 'MXAN_0483',
 'WP_011550617.1': 'MXAN_0484',
 'WP_011550618.1': 'MXAN_0485',
 'WP_011550619.1': 'MXAN_0486',
 'WP_011550621.1': 'MXAN_0488',
 'WP_011550626.1': 'MXAN_0493',
 'WP_011550627.1': 'MXAN_0494',
 'WP_011550629.1': 'MXAN_0496',
 'WP_011550634.1': 'MXAN_0501',
 'WP_011550636.1': 'MXAN_0504',
 'WP_011550637.1': nan,
 'WP_011550638.1': 'MXAN_0506',
 'WP_011550644.1': 'MXAN_0512',
 'WP_011550646.1': 'MXAN_0513',
 'WP_011550647.1': 'MXAN_0515',
 'WP_011550649.1': 'MXAN_0517',
 'WP_011550650.1': 'MXAN_0518',
 'WP_011550653.1': 'MXAN_0521',
 'WP_011550654.1': 'MXAN_0522',
 'WP_011550657.1': 'MXAN_0525',
 'WP_011550658.1': 'MXAN_0526',
 'WP_011550659.1': 'MXAN_0527',
 'WP_011550661.1': 'MXAN_0529',
 'WP_011550662.1': 'MXAN_0530',
 'WP_011550663.1': 'MXAN_0531',
 'WP_011550664.1': 'MXAN_0532',
 'WP_011550665.1': 'MXAN_0533',
 'WP_011550666.1': 'MXAN_0534',
 'WP_011550668.1': 'MXAN_0536',
 'WP_011550669.1': 'MXAN_0537',
 'WP_011550670.1': 'MXAN_0538',
 'WP_011550671.1': 'MXAN_0539',
 'WP_011550672.1': nan,
 'WP_011550673.1': 'MXAN_0541',
 'WP_011550674.1': 'MXAN_0542',
 'WP_011550675.1': 'MXAN_0543',
 'WP_011550676.1': 'MXAN_0544',
 'WP_011550677.1': 'MXAN_0545',
 'WP_011550678.1': 'MXAN_0546',
 'WP_011550679.1': 'MXAN_0547',
 'WP_011550680.1': 'MXAN_0548',
 'WP_011550681.1': 'MXAN_0549',
 'WP_011550684.1': nan,
 'WP_011550686.1': 'MXAN_0554',
 'WP_011550687.1': 'MXAN_0555',
 'WP_011550688.1': 'MXAN_0556',
 'WP_011550690.1': 'MXAN_0558',
 'WP_011550691.1': 'MXAN_0559',
 'WP_011550692.1': 'MXAN_0560',
 'WP_011550693.1': 'MXAN_0561',
 'WP_011550694.1': 'MXAN_0562',
 'WP_011550696.1': 'MXAN_0564',
 'WP_011550697.1': 'MXAN_0565',
 'WP_011550698.1': 'MXAN_0566',
 'WP_011550699.1': 'MXAN_0567',
 'WP_011550704.1': 'MXAN_0572',
 'WP_011550706.1': 'MXAN_0575',
 'WP_011550709.1': 'MXAN_0578',
 'WP_011550710.1': 'MXAN_0579',
 'WP_011550712.1': 'MXAN_0581',
 'WP_011550714.1': 'MXAN_0583',
 'WP_011550715.1': 'MXAN_0584',
 'WP_011550716.1': 'MXAN_0585',
 'WP_011550717.1': 'MXAN_0586',
 'WP_011550718.1': 'MXAN_0587',
 'WP_011550719.1': 'MXAN_0588',
 'WP_011550722.1': 'MXAN_0592',
 'WP_011550725.1': 'MXAN_0594',
 'WP_011550727.1': 'MXAN_0596',
 'WP_011550729.1': 'MXAN_0598',
 'WP_011550730.1': 'MXAN_0599',
 'WP_011550732.1': 'MXAN_0601',
 'WP_011550733.1': 'MXAN_0602',
 'WP_011550735.1': 'MXAN_0604',
 'WP_011550736.1': 'MXAN_0605',
 'WP_011550738.1': 'MXAN_0607',
 'WP_011550740.1': 'MXAN_0609',
 'WP_011550741.1': 'MXAN_0610',
 'WP_011550742.1': 'MXAN_0611',
 'WP_011550743.1': 'MXAN_0612',
 'WP_011550744.1': 'MXAN_0613',
 'WP_011550746.1': 'MXAN_0615',
 'WP_011550747.1': 'MXAN_0616',
 'WP_011550748.1': 'MXAN_0617',
 'WP_011550749.1': 'MXAN_0618',
 'WP_011550750.1': 'MXAN_0619',
 'WP_011550751.1': 'MXAN_0620',
 'WP_011550752.1': 'MXAN_0621',
 'WP_011550753.1': 'MXAN_0622',
 'WP_011550754.1': 'MXAN_0623',
 'WP_011550755.1': 'MXAN_0624',
 'WP_011550756.1': 'MXAN_0625',
 'WP_011550757.1': 'MXAN_0626',
 'WP_011550758.1': 'MXAN_0627',
 'WP_011550759.1': 'MXAN_0628',
 'WP_011550760.1': 'MXAN_0629',
 'WP_011550761.1': 'MXAN_0630',
 'WP_011550763.1': 'MXAN_0632',
 'WP_011550765.1': 'MXAN_0634',
 'WP_011550766.1': 'MXAN_0635',
 'WP_011550767.1': 'MXAN_0636',
 'WP_011550768.1': 'MXAN_0637',
 'WP_011550769.1': 'MXAN_0638',
 'WP_011550770.1': 'MXAN_0639',
 'WP_011550771.1': 'MXAN_0640',
 'WP_011550772.1': 'MXAN_0641',
 'WP_011550775.1': 'MXAN_0644',
 'WP_011550776.1': 'MXAN_0645',
 'WP_011550777.1': 'MXAN_0646',
 'WP_011550778.1': 'MXAN_0647',
 'WP_011550782.1': 'MXAN_0651',
 'WP_011550783.1': 'MXAN_0652',
 'WP_011550784.1': 'MXAN_0653',
 'WP_011550785.1': 'MXAN_0654',
 'WP_011550786.1': 'MXAN_0655',
 'WP_011550788.1': nan,
 'WP_011550789.1': 'MXAN_0658',
 'WP_011550790.1': 'MXAN_0659',
 'WP_011550791.1': 'MXAN_0660',
 'WP_011550792.1': 'MXAN_0661',
 'WP_011550793.1': 'MXAN_0662',
 'WP_011550794.1': 'MXAN_0663',
 'WP_011550795.1': 'MXAN_0664',
 'WP_011550796.1': 'MXAN_0665',
 'WP_011550797.1': 'MXAN_0666',
 'WP_011550798.1': 'MXAN_0667',
 'WP_011550799.1': 'MXAN_0668',
 'WP_011550800.1': 'MXAN_0669',
 'WP_011550801.1': 'MXAN_0670',
 'WP_011550802.1': 'MXAN_0671',
 'WP_011550804.1': 'MXAN_0674',
 'WP_011550805.1': 'MXAN_0675',
 'WP_011550806.1': 'MXAN_0676',
 'WP_011550808.1': 'MXAN_0678',
 'WP_011550809.1': 'MXAN_0679',
 'WP_011550810.1': nan,
 'WP_011550811.1': 'MXAN_0681',
 'WP_011550812.1': 'MXAN_0682',
 'WP_011550814.1': 'MXAN_0684',
 'WP_011550815.1': 'MXAN_0685',
 'WP_011550816.1': 'MXAN_0686',
 'WP_011550820.1': 'MXAN_0690',
 'WP_011550822.1': 'MXAN_0694',
 'WP_011550823.1': 'MXAN_0695',
 'WP_011550824.1': 'MXAN_0696',
 'WP_011550827.1': 'MXAN_0699',
 'WP_011550828.1': 'MXAN_0700',
 'WP_011550829.1': 'MXAN_0701',
 'WP_011550831.1': 'MXAN_0703',
 'WP_011550832.1': 'MXAN_0704',
 'WP_011550836.1': 'MXAN_0708',
 'WP_011550837.1': 'MXAN_0709',
 'WP_011550838.1': 'MXAN_0710',
 'WP_011550839.1': 'MXAN_0711',
 'WP_011550840.1': 'MXAN_0712',
 'WP_011550841.1': 'MXAN_0713',
 'WP_011550842.1': 'MXAN_0714',
 'WP_011550843.1': 'MXAN_0715',
 'WP_011550844.1': 'MXAN_0716',
 'WP_011550845.1': 'MXAN_0717',
 'WP_011550846.1': 'MXAN_0718',
 'WP_011550848.1': 'MXAN_0720',
 'WP_011550850.1': 'MXAN_0722',
 'WP_011550852.1': 'MXAN_0724',
 'WP_011550853.1': 'MXAN_0725',
 'WP_011550855.1': 'MXAN_0729',
 'WP_011550856.1': 'MXAN_0730',
 'WP_011550857.1': 'MXAN_0731',
 'WP_011550858.1': 'MXAN_0732',
 'WP_011550859.1': 'MXAN_0733',
 'WP_011550861.1': 'MXAN_0735',
 'WP_011550862.1': 'MXAN_0736',
 'WP_011550863.1': 'MXAN_0737',
 'WP_011550864.1': 'MXAN_0738',
 'WP_011550865.1': 'MXAN_0739',
 'WP_011550866.1': 'MXAN_0740',
 'WP_011550867.1': 'MXAN_0741',
 'WP_011550868.1': 'MXAN_0742',
 'WP_011550870.1': 'MXAN_0744',
 'WP_011550872.1': 'MXAN_0746',
 'WP_011550873.1': 'MXAN_0747',
 'WP_011550874.1': 'MXAN_0748',
 'WP_011550876.1': 'MXAN_0750',
 'WP_011550877.1': 'MXAN_0751',
 'WP_011550878.1': 'MXAN_0752',
 'WP_011550880.1': 'MXAN_0754',
 'WP_011550883.1': 'MXAN_0756',
 'WP_011550884.1': 'MXAN_0758',
 'WP_011550886.1': 'MXAN_0760',
 'WP_011550887.1': 'MXAN_0761',
 'WP_011550888.1': 'MXAN_0762',
 'WP_011550889.1': 'MXAN_0763',
 'WP_011550890.1': 'MXAN_0764',
 'WP_011550891.1': 'MXAN_0765',
 'WP_011550893.1': 'MXAN_0767',
 'WP_011550894.1': 'MXAN_0768',
 'WP_011550896.1': 'MXAN_0770',
 'WP_011550897.1': 'MXAN_0771',
 'WP_011550898.1': 'MXAN_0772',
 'WP_011550899.1': 'MXAN_0773',
 'WP_011550900.1': 'MXAN_0774',
 'WP_011550901.1': 'MXAN_0775',
 'WP_011550902.1': 'MXAN_0776',
 'WP_011550903.1': 'MXAN_0777',
 'WP_011550905.1': 'MXAN_0779',
 'WP_011550907.1': 'MXAN_0781',
 'WP_011550909.1': 'MXAN_0785',
 'WP_011550910.1': 'MXAN_0787',
 'WP_011550911.1': 'MXAN_0788',
 'WP_011550913.1': 'No old locus tag',
 'WP_011550914.1': 'MXAN_0791',
 'WP_011550915.1': 'MXAN_0792',
 'WP_011550916.1': 'MXAN_0793',
 'WP_011550918.1': 'MXAN_0795',
 'WP_011550919.1': 'MXAN_0796',
 'WP_011550920.1': 'MXAN_0797',
 'WP_011550924.1': 'MXAN_0801',
 'WP_011550925.1': 'MXAN_0802',
 'WP_011550927.1': 'MXAN_0804',
 'WP_011550928.1': 'MXAN_0805',
 'WP_011550929.1': 'MXAN_0806',
 'WP_011550930.1': 'MXAN_0807',
 'WP_011550931.1': 'MXAN_0808',
 'WP_011550932.1': 'MXAN_0809',
 'WP_011550933.1': 'MXAN_0810',
 'WP_011550934.1': 'MXAN_0811',
 'WP_011550935.1': 'MXAN_0812',
 'WP_011550936.1': 'MXAN_0813',
 'WP_011550937.1': 'MXAN_0814',
 'WP_011550939.1': 'MXAN_0816',

In [27]:
DataTable = DataTable.replace(to_replace=dico_genes)
DataTable

,GeneNames,Ec1,Ec2,Ec3,B1,B2,B3,C1,C2,C3,...,W3,K1,K2,K3,WC1,WC2,WC3,KC1,KC2,KC3
0,MXAN_5201,13032,13136,12917,18050,22828,16816,42888,32404,20170,...,60053,35638,38908,37314,15344,15530,27018,17185,13886,9121
1,MXAN_3321,6817,5982,6246,15018,16718,18070,29227,34305,9713,...,69546,28536,31303,34021,19022,19870,35902,12388,22264,17843
2,MXAN_6531,275,195,239,521,550,406,1140,727,386,...,2409,838,832,531,1110,995,1063,1841,1027,766
3,MXAN_3309,15516,14792,13306,28206,30917,22916,64389,58243,23106,...,62136,27039,28864,34478,7962,9148,24438,4169,7524,7193
4,MXAN_3306,4095,2680,1969,8170,8806,14771,20987,18394,9361,...,17038,13309,11109,20035,3338,2187,11373,3164,2406,4588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7184,NaN,31,36,108,26,31,49,93,69,45,...,76,29,39,42,29,26,39,23,19,33
7185,NaN,11,13,46,11,17,4,43,46,17,...,79,10,15,13,14,33,26,17,19,31
7186,NaN,1332,1512,1834,2258,2340,1791,4704,5134,1659,...,13345,3235,3431,2941,4105,5714,3841,9265,5144,6080
7187,NaN,46,26,305,79,90,72,154,115,44,...,196,89,63,71,102,60,67,100,47,93
7188,NaN,918,2104,1781,1836,1928,1194,3263,3999,1372,...,3892,452,531,460,1444,3448,1236,264,711,468

In [28]:
for i in DataTable.GeneNames:
    print(i)

MXAN_5201
MXAN_3321
MXAN_6531
MXAN_3309
MXAN_3306
MXAN_3305
MXAN_3304
MXAN_3303
MXAN_3301
MXAN_3300
MXAN_3299
MXAN_5125
MXAN_5074
MXAN_5002
MXAN_5592
MXAN_5688
MXAN_2709
MXAN_2913
MXAN_1434
MXAN_0672
MXAN_0403
MXAN_4033
MXAN_4095
MXAN_4636
MXAN_4637
MXAN_4673
MXAN_2448
MXAN_1926
MXAN_3295
MXAN_7512
No old locus tag
MXAN_2528
No old locus tag
MXAN_3793
MXAN_3596
MXAN_2978
MXAN_4894
MXAN_3154
No old locus tag
MXAN_7339
MXAN_2457
MXAN_0001
MXAN_0002
MXAN_0003
MXAN_0004
MXAN_0005
MXAN_0008
MXAN_0009
MXAN_0010
MXAN_0012
MXAN_0013
MXAN_0014
MXAN_0015
MXAN_0016
MXAN_0017
MXAN_0019
MXAN_0020
MXAN_0022
MXAN_0024
nan
MXAN_0026
MXAN_0027
MXAN_0029
MXAN_0030
MXAN_0031
MXAN_0032
MXAN_0033
MXAN_0034
MXAN_0035
WP_011550185.1
MXAN_0039
MXAN_0040
MXAN_0041
MXAN_0042
MXAN_0043
MXAN_0044
MXAN_0045
nan
MXAN_0048
MXAN_0049
MXAN_0050
MXAN_0051
MXAN_0052
MXAN_0053
MXAN_0054
nan
MXAN_0056
MXAN_0057
MXAN_0058
MXAN_0059
MXAN_0060
MXAN_0061
MXAN_0063
MXAN_0064
MXAN_0070
MXAN_0071
MXAN_0072
MXAN_0073
MXAN_0074
MXAN_0076
MXAN_0077
MXAN_0078
MXAN_0079
MXAN_0080
MXAN_0081
MXAN_0082
MXAN_0083
MXAN_0084
MXAN_0085
MXAN_0086
MXAN_0087
MXAN_0088
MXAN_0089
MXAN_0090
MXAN_0092
MXAN_0093
MXAN_0094
MXAN_0095
MXAN_0096
MXAN_0097
MXAN_0098
MXAN_0100
MXAN_0101
MXAN_0102
MXAN_0104
MXAN_0105
MXAN_0107
MXAN_0109
MXAN_0110
MXAN_0111
MXAN_0112
MXAN_0113
MXAN_0114
MXAN_0115
MXAN_0116
MXAN_0117
MXAN_0118
MXAN_0119
MXAN_0120
MXAN_0123
MXAN_0124
MXAN_0126
MXAN_0128
MXAN_0129
MXAN_0130
MXAN_0131
MXAN_0133
MXAN_0134
MXAN_0135
MXAN_0136
MXAN_0137
MXAN_0138
MXAN_0139
MXAN_0140
MXAN_0141
MXAN_0142
MXAN_0143
MXAN_0144
MXAN_0145
MXAN_0146
MXAN_0147
MXAN_0148
MXAN_0151
MXAN_0152
MXAN_0153
MXAN_0155
MXAN_0156
nan
MXAN_0158
MXAN_0159
MXAN_0160
MXAN_0162
MXAN_0164
MXAN_0165
MXAN_0166
MXAN_0167
MXAN_0168
MXAN_0170
MXAN_0172
MXAN_0173
MXAN_0174
MXAN_0175
MXAN_0176
WP_011550324.1
WP_011550325.1
MXAN_0179
MXAN_0182
MXAN_0183
MXAN_0184
MXAN_0185
MXAN_0186
MXAN_0188
MXAN_0189
MXAN_0193
MXAN_0195
MXAN_0196
MXAN_0198
MXAN_0199
MXAN_0200
MXAN_0201
MXAN_0202
MXAN_0203
MXAN_0204
MXAN_0205
MXAN_0206
MXAN_0207
WP_011550356.1
MXAN_0211
MXAN_0212
MXAN_0213
MXAN_0214
MXAN_0215
MXAN_0217
MXAN_0219
MXAN_0220
MXAN_0221
MXAN_0222
MXAN_0223
MXAN_0225
MXAN_0227
MXAN_0228
MXAN_0229
MXAN_0230
MXAN_0231
MXAN_0232
MXAN_0235
MXAN_0236
MXAN_0237
MXAN_0238
WP_011550384.1
No old locus tag
MXAN_0242
MXAN_0243
MXAN_0244
MXAN_0245
MXAN_0246
MXAN_0248
MXAN_0250
MXAN_0251
MXAN_0252
MXAN_0253
MXAN_0254
MXAN_0255
MXAN_0256
MXAN_0257
MXAN_0259
MXAN_0260
MXAN_0261
MXAN_0262
MXAN_0263
MXAN_0264
MXAN_0266
MXAN_0267
nan
MXAN_0269
MXAN_0271
MXAN_0272
MXAN_0273
WP_011550419.1
WP_011550420.1
MXAN_0276
MXAN_0277
MXAN_0278
MXAN_0279
MXAN_0282
MXAN_0283
MXAN_0284
MXAN_0285
MXAN_0286
MXAN_0288
MXAN_0289
MXAN_0290
MXAN_0292
MXAN_0293
MXAN_0294
MXAN_0295
MXAN_0296
MXAN_0297
MXAN_0299
MXAN_0300
MXAN_0301
MXAN_0302
MXAN_0303
MXAN_0304
MXAN_0305
MXAN_0306
MXAN_0307
MXAN_0308
MXAN_0309
MXAN_0311
MXAN_0312
MXAN_0313
MXAN_0314
MXAN_0315
MXAN_0316
MXAN_0317
MXAN_0318
MXAN_0324
MXAN_0325
MXAN_0326
MXAN_0327
MXAN_0328
MXAN_0330
MXAN_0331
MXAN_0332
MXAN_0333
MXAN_0335
MXAN_0336
MXAN_0339
MXAN_0341
MXAN_0342
MXAN_0343
MXAN_0344
MXAN_0345
MXAN_0346
WP_011550485.1
MXAN_0348
MXAN_0351
MXAN_0352
MXAN_0355
MXAN_0358
MXAN_0359
MXAN_0360
MXAN_0361
MXAN_0363
MXAN_0364
MXAN_0365
MXAN_0366
MXAN_0368
MXAN_0369
MXAN_0371
MXAN_0372
MXAN_0374
MXAN_0375
MXAN_0376
MXAN_0377
nan
MXAN_0379
MXAN_0384
WP_011550521.1
MXAN_0386
MXAN_0387
MXAN_0389
MXAN_0390
MXAN_0391
MXAN_0395
MXAN_0399
MXAN_0401
MXAN_0405
MXAN_0407
WP_011550542.1
MXAN_0409
MXAN_0410
MXAN_0411
MXAN_0412
MXAN_0415
MXAN_0417
MXAN_0418
MXAN_0419
MXAN_0420
MXAN_0421
MXAN_0422
MXAN_0423
MXAN_0432
MXAN_0433
MXAN_0434
MXAN_0435
MXAN_0436
MXAN_0437
MXAN_0438
MXAN_0439
WP_011550573.1
MXAN_0442
MXAN_0443
MXAN_0444
MXAN_0446
MXAN_0447
MXAN_0448
MXAN_0451
MXAN_0452
MXAN_0453
MXAN_0454
MXAN_0455
nan
MXAN_0457
MXAN_0458
MXAN_0459
MXAN_0460
MXAN_0461
MXAN_0462
MXAN_0463
MXAN_0464
MXAN_0466
MXAN_0467
MXAN_0468
MXAN_0469
MXAN_0470
MXAN_0471
MXAN_0473
MXAN_0475
MXAN_0476
MXAN_0477
MXAN_0478
MXAN_0479
MXAN_0480
MXAN_0481
MXAN_0482
MXAN_0483
MXAN_0484
MXAN_0485
MXAN_0486
MXAN_0488
WP_011550624.1
MXAN_0493
MXAN_0494
MXAN_0496
MXAN_0501
MXAN_0504
nan
MXAN_0506
MXAN_0512
MXAN_0513
MXAN_0515
MXAN_0517
MXAN_0518
MXAN_0521
MXAN_0522
MXAN_0525
MXAN_0526
MXAN_0527
WP_011550660.1
MXAN_0529
MXAN_0530
MXAN_0531
MXAN_0532
MXAN_0533
MXAN_0534
MXAN_0536
MXAN_0537
MXAN_0538
MXAN_0539
nan
MXAN_0541
MXAN_0542
MXAN_0543
MXAN_0544
MXAN_0545
MXAN_0546
MXAN_0547
MXAN_0548
MXAN_0549
WP_011550682.1
WP_011550683.1
nan
MXAN_0554
MXAN_0555
MXAN_0556
WP_011550689.1
MXAN_0558
MXAN_0559
MXAN_0560
MXAN_0561
MXAN_0562
MXAN_0564
MXAN_0565
MXAN_0566
MXAN_0567
WP_011550700.1
WP_011550703.1
MXAN_0572
MXAN_0575
WP_011550707.1
MXAN_0578
MXAN_0579
MXAN_0581
MXAN_0583
MXAN_0584
MXAN_0585
MXAN_0586
MXAN_0587
MXAN_0588
WP_011550720.1
WP_011550721.1
MXAN_0592
MXAN_0594
MXAN_0596
MXAN_0598
MXAN_0599
WP_011550731.1
MXAN_0601
MXAN_0602
MXAN_0604
MXAN_0605
MXAN_0607
MXAN_0609
MXAN_0610
MXAN_0611
MXAN_0612
MXAN_0613
MXAN_0615
MXAN_0616
MXAN_0617
MXAN_0618
MXAN_0619
MXAN_0620
MXAN_0621
MXAN_0622
MXAN_0623
MXAN_0624
MXAN_0625
MXAN_0626
MXAN_0627
MXAN_0628
MXAN_0629
MXAN_0630
MXAN_0632
MXAN_0634
MXAN_0635
MXAN_0636
MXAN_0637
MXAN_0638
MXAN_0639
MXAN_0640
MXAN_0641
MXAN_0644
MXAN_0645
MXAN_0646
MXAN_0647
MXAN_0651
MXAN_0652
MXAN_0653
MXAN_0654
MXAN_0655
nan
MXAN_0658
MXAN_0659
MXAN_0660
MXAN_0661
MXAN_0662
MXAN_0663
MXAN_0664
MXAN_0665
MXAN_0666
MXAN_0667
MXAN_0668
MXAN_0669
MXAN_0670
MXAN_0671
MXAN_0674
MXAN_0675
MXAN_0676
MXAN_0678
MXAN_0679
nan
MXAN_0681
MXAN_0682
MXAN_0684
MXAN_0685
MXAN_0686
MXAN_0690
MXAN_0694
MXAN_0695
MXAN_0696
MXAN_0699
MXAN_0700
MXAN_0701
MXAN_0703
MXAN_0704
WP_011550833.1
MXAN_0708
MXAN_0709
MXAN_0710
MXAN_0711
MXAN_0712
MXAN_0713
MXAN_0714
MXAN_0715
MXAN_0716
MXAN_0717
MXAN_0718
MXAN_0720
MXAN_0722
MXAN_0724
MXAN_0725
MXAN_0729
MXAN_0730
MXAN_0731
MXAN_0732
MXAN_0733
MXAN_0735
MXAN_0736
MXAN_0737
MXAN_0738
MXAN_0739
MXAN_0740
MXAN_0741
MXAN_0742
MXAN_0744
MXAN_0746
MXAN_0747
MXAN_0748
MXAN_0750
MXAN_0751
MXAN_0752
MXAN_0754
MXAN_0756
MXAN_0758
MXAN_0760
MXAN_0761
MXAN_0762
MXAN_0763
MXAN_0764
MXAN_0765
MXAN_0767
MXAN_0768
MXAN_0770
MXAN_0771
MXAN_0772
MXAN_0773
MXAN_0774
MXAN_0775
MXAN_0776
MXAN_0777
MXAN_0779
WP_011550906.1
MXAN_0781
MXAN_0785
MXAN_0787
MXAN_0788
No old locus tag
MXAN_0791
MXAN_0792
MXAN_0793
MXAN_0795
MXAN_0796
MXAN_0797
MXAN_0801
MXAN_0802
MXAN_0804
MXAN_0805
MXAN_0806
MXAN_0807
MXAN_0808
MXAN_0809
MXAN_0810
MXAN_0811
MXAN_0812
MXAN_0813
MXAN_0814
MXAN_0816
MXAN_0817
MXAN_0818
MXAN_0819
MXAN_0820
MXAN_0821
MXAN_0822
MXAN_0823
MXAN_0824
MXAN_0825
WP_011550949.1
MXAN_0827
MXAN_0829
MXAN_0831
MXAN_0832
MXAN_0833
MXAN_0836
MXAN_0838
MXAN_0839
MXAN_0840
MXAN_0841
MXAN_0844
MXAN_0845
nan
MXAN_0848
MXAN_0853
MXAN_0854
MXAN_0855
MXAN_0856
MXAN_0857
MXAN_0858
MXAN_0859
MXAN_0860
MXAN_0861
MXAN_0862
MXAN_0863
MXAN_0864
MXAN_0865
MXAN_0866
MXAN_0867
MXAN_0868
nan
MXAN_0870
MXAN_0871
MXAN_0872
MXAN_0873
MXAN_0874
MXAN_0875
MXAN_0876
MXAN_0877
MXAN_0878
MXAN_0879
MXAN_0880
MXAN_0881
MXAN_0882
No old locus tag
MXAN_0884
MXAN_0885
MXAN_0886
MXAN_0887
MXAN_0888
MXAN_0889
MXAN_0890
MXAN_0891
MXAN_0893
MXAN_0894
MXAN_0895
MXAN_0896
MXAN_0897
MXAN_0898
MXAN_0899
MXAN_0900
MXAN_0901
MXAN_0902
MXAN_0903
MXAN_0904
MXAN_0905
MXAN_0906
MXAN_0908
MXAN_0909
MXAN_0910
MXAN_0911
MXAN_0912
MXAN_0913
MXAN_0914
MXAN_0915
MXAN_0916
MXAN_0917
MXAN_0918
MXAN_0919
MXAN_0920
MXAN_0921
MXAN_0922
MXAN_0923
MXAN_0924
MXAN_0925
MXAN_0926
MXAN_0927
MXAN_0929
MXAN_0931
MXAN_0932
MXAN_0933
MXAN_0934
MXAN_0936
MXAN_0937
MXAN_0938
MXAN_0939
MXAN_0940
MXAN_0941
MXAN_0942
MXAN_0943
MXAN_0944
MXAN_0945
MXAN_0946
MXAN_0948
MXAN_0950
MXAN_0951
MXAN_0952
MXAN_0953
MXAN_0954
MXAN_0955
MXAN_0956
MXAN_0957
MXAN_0958
MXAN_0959
MXAN_0961
MXAN_0962
MXAN_0964
MXAN_0965
MXAN_0966
MXAN_0968
MXAN_0969
MXAN_0970
MXAN_0975
MXAN_0976
MXAN_0977
MXAN_0978
MXAN_0979
MXAN_0981
MXAN_0984
WP_011551106.1
MXAN_0986
MXAN_0988
MXAN_0990
MXAN_0991
MXAN_0992
MXAN_0993
MXAN_0994
MXAN_0995
MXAN_0996
MXAN_0997
MXAN_0998
MXAN_1000
MXAN_1001
MXAN_1002
MXAN_1003
MXAN_1004
MXAN_1005
MXAN_1006
MXAN_1007
MXAN_1009
MXAN_1010
MXAN_1011
MXAN_1012
MXAN_1013
MXAN_1015
MXAN_1016
MXAN_1017
MXAN_1018
MXAN_1019
WP_011551141.1
MXAN_1021
MXAN_1022
MXAN_1023
MXAN_1026
MXAN_1027
MXAN_1028
MXAN_1030
MXAN_1031
MXAN_1032
MXAN_1033
MXAN_1034
MXAN_1035
MXAN_1036
MXAN_1037
MXAN_1038
MXAN_1039
MXAN_1040
MXAN_1041
MXAN_1042
MXAN_1043
MXAN_1047
MXAN_1048
MXAN_1049
MXAN_1050
MXAN_1051
MXAN_1052
MXAN_1053
MXAN_1055
MXAN_1056
MXAN_1057
MXAN_1058
MXAN_1059
MXAN_1060
MXAN_1061
MXAN_1062
MXAN_1063
MXAN_1065
MXAN_1066
nan
MXAN_1068
MXAN_1070
MXAN_1071
MXAN_1072
MXAN_1073
MXAN_1074
MXAN_1075
MXAN_1076
MXAN_1077
MXAN_1079
MXAN_1080
MXAN_1081
MXAN_1083
MXAN_1084
MXAN_1085
MXAN_1086
MXAN_1087
MXAN_1088
MXAN_1089
MXAN_1090
MXAN_1091
MXAN_1092
MXAN_1095
MXAN_1096
MXAN_1097
MXAN_1098
MXAN_1099
MXAN_1100
MXAN_1101
MXAN_1102
MXAN_1103
MXAN_1104
MXAN_1105
MXAN_1106
MXAN_1107
MXAN_1109
MXAN_1110
MXAN_1111
MXAN_1112
MXAN_1113
MXAN_1114
MXAN_1115
MXAN_1116
MXAN_1118
MXAN_1119
MXAN_1120
MXAN_1121
MXAN_1123
MXAN_1124
MXAN_1125
MXAN_1126
MXAN_1127
MXAN_1129
MXAN_1130
MXAN_1132
MXAN_1133
MXAN_1134
MXAN_1135
MXAN_1136
MXAN_1137
MXAN_1138
MXAN_1139
MXAN_1140
MXAN_1141
MXAN_1142
MXAN_1143
MXAN_1144
MXAN_1145
MXAN_1146
MXAN_1147
MXAN_1148
MXAN_1150
MXAN_1152
MXAN_1153
MXAN_1154
MXAN_1155
MXAN_1156
MXAN_1157
MXAN_1159
MXAN_1161
MXAN_1162
MXAN_1163
MXAN_1164
MXAN_1166
MXAN_1167
MXAN_1170
MXAN_1171
MXAN_1174
MXAN_1175
MXAN_1176
MXAN_1177
MXAN_1178
MXAN_1179
MXAN_1181
MXAN_1182
MXAN_1183
MXAN_1184
MXAN_1185
WP_011551305.1
MXAN_1187
MXAN_1188
MXAN_1189
nan
MXAN_1192
MXAN_1193
MXAN_1194
MXAN_1197
MXAN_1198
MXAN_1199
WP_011551320.1
WP_011551321.1
WP_011551322.1
MXAN_1204
WP_011551326.1
WP_011551330.1
WP_011551331.1
MXAN_1214
MXAN_1215
WP_011551335.1
WP_011551336.1
WP_011551337.1
WP_011551338.1
WP_011551339.1
WP_011551340.1
WP_011551341.1
WP_011551342.1
WP_011551344.1
MXAN_1226
WP_011551347.1
WP_011551348.1
WP_011551349.1
MXAN_1231
MXAN_1232
MXAN_1233
MXAN_1234
MXAN_1235
MXAN_1236
MXAN_1237
MXAN_1238
MXAN_1239
MXAN_1240
MXAN_1242
MXAN_1243
MXAN_1244
MXAN_1246
WP_011551366.1
MXAN_1248
MXAN_1249
MXAN_1250
MXAN_1254
nan
MXAN_1256
MXAN_1257
MXAN_1258
MXAN_1259
MXAN_1261
MXAN_1262
MXAN_1263
MXAN_1264
MXAN_1265
MXAN_1266
nan
MXAN_1268
MXAN_1269
MXAN_1270
MXAN_1271
MXAN_1272
MXAN_1273
MXAN_1275
WP_011551393.1
MXAN_1277
MXAN_1278
MXAN_1280
MXAN_1282
MXAN_1283
MXAN_1287
MXAN_1290
MXAN_1293
MXAN_1294
MXAN_1295
MXAN_1296
MXAN_1297
MXAN_1298
MXAN_1299
MXAN_1300
MXAN_1301
MXAN_1302
MXAN_1303
MXAN_1304
MXAN_1305
MXAN_1307
MXAN_1309
MXAN_1310
MXAN_1311
MXAN_1312
MXAN_1314
MXAN_1316
MXAN_1317
MXAN_1318
MXAN_1319
MXAN_1320
MXAN_1321
MXAN_1323
MXAN_1324
MXAN_1325
MXAN_1326
MXAN_1327
MXAN_1328
MXAN_1331
MXAN_1332
MXAN_1333
MXAN_1334
MXAN_1335
MXAN_1336
MXAN_1337
MXAN_1338
MXAN_1339
MXAN_1340
MXAN_1341
MXAN_1342
MXAN_1343
MXAN_1344
MXAN_1345
MXAN_1346
MXAN_1347
MXAN_1349
MXAN_1350
MXAN_1351
MXAN_1352
MXAN_1354
MXAN_1355
MXAN_1357
MXAN_1358
MXAN_1359
MXAN_1360
MXAN_1361
MXAN_1362
MXAN_1363
MXAN_1364
MXAN_1365
MXAN_1366
MXAN_1367
MXAN_1368
MXAN_1369
MXAN_1372
MXAN_1373
nan
MXAN_1376
MXAN_1378
MXAN_1380
MXAN_1382
MXAN_1383
MXAN_1384
MXAN_1385
MXAN_1386
MXAN_1387
MXAN_1388
MXAN_1389
MXAN_1390
MXAN_1391
MXAN_1392
MXAN_1393
MXAN_1394
MXAN_1395
MXAN_1396
MXAN_1397
MXAN_1399
MXAN_1400
MXAN_1401
MXAN_1402
MXAN_1403
MXAN_1405
MXAN_1406
MXAN_1407
nan
MXAN_1409
MXAN_1412
MXAN_1413
MXAN_1414
MXAN_1415
MXAN_1416
MXAN_1417
nan
MXAN_1420
MXAN_1421
MXAN_1422
MXAN_1423
MXAN_1424
MXAN_1425
MXAN_1426
MXAN_1427
MXAN_1428
MXAN_1429
MXAN_1430
MXAN_1432
MXAN_1433
MXAN_1435
MXAN_1436
MXAN_1438
MXAN_1439
MXAN_1440
MXAN_1441
MXAN_1442
MXAN_1443
MXAN_1444
MXAN_1445
MXAN_1446
MXAN_1447
MXAN_1448
MXAN_1449
MXAN_1450
MXAN_1451
MXAN_1452
MXAN_1453
MXAN_1454
MXAN_1455
nan
MXAN_1457
nan
nan
MXAN_1460
MXAN_1462
MXAN_1463
MXAN_1464
MXAN_1465
MXAN_1466
MXAN_1468
MXAN_1470
MXAN_1471
MXAN_1472
MXAN_1474
MXAN_1476
MXAN_1477
MXAN_1478
MXAN_1479
MXAN_1480
MXAN_1481
MXAN_1482
MXAN_1483
MXAN_1485
MXAN_1486
MXAN_1493
MXAN_1495
WP_011551610.1
WP_011551611.1
MXAN_1501
nan
MXAN_1504
MXAN_1505
WP_011551617.1
MXAN_1507
MXAN_1508
MXAN_1509
MXAN_1510
MXAN_1511
MXAN_1512
MXAN_1513
MXAN_1514
MXAN_1515
MXAN_1516
MXAN_1517
MXAN_1518
MXAN_1520
MXAN_1521
MXAN_1522
MXAN_1523
MXAN_1524
MXAN_1527
MXAN_1528
MXAN_1529
MXAN_1530
MXAN_1531
MXAN_1532
MXAN_1534
MXAN_1535
MXAN_1536
MXAN_1537
MXAN_1539
MXAN_1540
MXAN_1541
MXAN_1542
MXAN_1543
MXAN_1544
MXAN_1546
MXAN_1547
MXAN_1548
MXAN_1549
MXAN_1550
MXAN_1552
MXAN_1553
MXAN_1554
MXAN_1555
MXAN_1556
MXAN_1557
MXAN_1559
MXAN_1560
MXAN_1561
MXAN_1562
MXAN_1563
MXAN_1564
MXAN_1565
MXAN_1566
MXAN_1567
MXAN_1568
MXAN_1570
MXAN_1571
MXAN_1572
MXAN_1574
MXAN_1575
MXAN_1578
MXAN_1579
MXAN_1580
WP_011551692.1
MXAN_1582
MXAN_1585
MXAN_1586
MXAN_1587
MXAN_1588
MXAN_1589
MXAN_1590
MXAN_1591
MXAN_1593
MXAN_1594
MXAN_1595
MXAN_1596
MXAN_1597
MXAN_1598
MXAN_1599
MXAN_1600
MXAN_1601
MXAN_1602
MXAN_1604
MXAN_1605
MXAN_1606
MXAN_1608
nan
MXAN_1610
MXAN_1611
MXAN_1612
MXAN_1614
MXAN_1615
MXAN_1616
MXAN_1617
MXAN_1618
MXAN_1619
MXAN_1620
MXAN_1621
MXAN_1623
MXAN_1624
MXAN_1626
MXAN_1627
MXAN_1628
MXAN_1632
MXAN_1633
WP_011551747.1
WP_011551749.1
WP_011551750.1
MXAN_1640
MXAN_1641
WP_011551753.1
MXAN_1643
MXAN_1644
MXAN_1645
MXAN_1646
MXAN_1647
MXAN_1648
MXAN_1649
MXAN_1650
MXAN_1651
MXAN_1652
MXAN_1653
MXAN_1654
MXAN_1656
MXAN_1657
MXAN_1659
MXAN_1661
MXAN_1663
MXAN_1665
MXAN_1666
MXAN_1667
MXAN_1669
MXAN_1671
MXAN_1672
MXAN_1673
MXAN_1674
MXAN_1675
MXAN_1676
MXAN_1677
MXAN_1678
MXAN_1679
MXAN_1680
MXAN_1681
MXAN_1683
MXAN_1684
MXAN_1686
WP_011551799.1
MXAN_1689
MXAN_1692
MXAN_1693
MXAN_1695
MXAN_1697
nan
MXAN_1700
MXAN_1701
MXAN_1703
MXAN_1706
MXAN_1707
MXAN_1708
MXAN_1709
MXAN_1710
MXAN_1713
MXAN_1714
MXAN_1718
MXAN_1719
MXAN_1720
MXAN_1726
MXAN_1728
MXAN_1732
MXAN_1733
MXAN_1735
MXAN_1736
MXAN_1737
MXAN_1741
MXAN_1742
MXAN_1743
MXAN_1744
MXAN_1745
MXAN_1746
MXAN_1748
nan
MXAN_1751
MXAN_1752
MXAN_1754
MXAN_1756
MXAN_1757
MXAN_1758
MXAN_1759
MXAN_1766
WP_011551876.1
MXAN_1769
MXAN_1774
MXAN_1775
MXAN_1776
MXAN_1777
nan
MXAN_1788
MXAN_1789
MXAN_1790
MXAN_1791
MXAN_1792
MXAN_1793
MXAN_1796
MXAN_1800
MXAN_1801
MXAN_1805
MXAN_1807
MXAN_1808
MXAN_1810
MXAN_1813
MXAN_1814
WP_011551920.1
MXAN_1816
MXAN_1819
WP_011551925.1
WP_011551926.1
WP_011551929.1
MXAN_1831
MXAN_1833
WP_011551936.1
WP_011551937.1
WP_011551938.1
WP_011551940.1
MXAN_1839
WP_011551944.1
WP_011551946.1
WP_011551947.1
WP_011551948.1
WP_011551949.1
WP_011551950.1
WP_011551951.1
MXAN_1850
MXAN_1851
WP_011551957.1
WP_011551958.1
WP_011551959.1
WP_011551960.1
WP_011551961.1
WP_011551962.1
MXAN_1862
MXAN_1863
WP_011551967.1
MXAN_1866
WP_011551969.1
MXAN_1868
nan
MXAN_1872
MXAN_1874
MXAN_1875
MXAN_1876
MXAN_1877
MXAN_1878
WP_011551982.1
MXAN_1883
MXAN_1884
WP_011551988.1
MXAN_1887
MXAN_1888
MXAN_1890
MXAN_1892
nan
MXAN_1894
MXAN_1895
MXAN_1896
MXAN_1897
MXAN_1899
MXAN_1900
MXAN_1903
MXAN_1904
MXAN_1905
MXAN_1907
MXAN_1909
MXAN_1910
MXAN_1911
MXAN_1914
MXAN_1915
MXAN_1916
MXAN_1917
MXAN_1918
MXAN_1919
MXAN_1920
MXAN_1921
MXAN_1922
MXAN_1923
MXAN_1924
MXAN_1925
MXAN_1927
MXAN_1928
MXAN_1929
MXAN_1930
MXAN_1931
MXAN_1933
MXAN_1937
MXAN_1941
MXAN_1942
MXAN_1943
MXAN_1944
MXAN_1945
MXAN_1947
MXAN_1948
MXAN_1949
MXAN_1951
MXAN_1953
MXAN_1954
MXAN_1955
MXAN_1956
MXAN_1957
nan
MXAN_1963
No old locus tag
MXAN_1965
MXAN_1966
MXAN_1967
MXAN_1968
MXAN_1969
MXAN_1970
MXAN_1973
MXAN_1975
MXAN_1976
MXAN_1977
MXAN_1978
MXAN_1979
MXAN_1980
MXAN_1981
MXAN_1982
MXAN_1984
MXAN_1986
MXAN_1987
MXAN_1991
MXAN_1992
MXAN_1994
MXAN_1996
MXAN_1997
MXAN_1998
MXAN_1999
MXAN_2000
MXAN_2001
MXAN_2002
MXAN_2003
MXAN_2004
MXAN_2005
MXAN_2010
MXAN_2013
MXAN_2014
MXAN_2015
MXAN_2017
MXAN_2019
MXAN_2020
MXAN_2021
MXAN_2022
MXAN_2023
MXAN_2024
MXAN_2025
MXAN_2026
MXAN_2027
MXAN_2028
MXAN_2029
MXAN_2031
MXAN_2032
MXAN_2034
MXAN_2035
MXAN_2036
MXAN_2037
MXAN_2039
MXAN_2040
MXAN_2041
MXAN_2042
MXAN_2043
MXAN_2044
MXAN_2045
MXAN_2046
WP_011552131.1
MXAN_2050
MXAN_2051
MXAN_2052
nan
MXAN_2054
MXAN_2055
MXAN_2056
MXAN_2057
MXAN_2058
MXAN_2059
MXAN_2060
MXAN_2061
MXAN_2062
MXAN_2063
MXAN_2064
MXAN_2065
MXAN_2066
MXAN_2067
MXAN_2068
MXAN_2069
MXAN_2070
MXAN_2071
MXAN_2072
MXAN_2073
MXAN_2074
MXAN_2075
MXAN_2076
MXAN_2077
MXAN_2078
MXAN_2079
MXAN_2080
nan
MXAN_2082
nan
MXAN_2084
MXAN_2085
MXAN_2087
MXAN_2089
MXAN_2090
MXAN_2091
MXAN_2092
MXAN_2094
MXAN_2095
MXAN_2096
MXAN_2098
MXAN_2100
MXAN_2107
WP_011552190.1
MXAN_2112
MXAN_2117
WP_011552203.1
MXAN_2128
nan
MXAN_2132
MXAN_2134
MXAN_2136
MXAN_2137
MXAN_2139
MXAN_2140
MXAN_2143
MXAN_2144
MXAN_2145
MXAN_2147
MXAN_2148
MXAN_2150
MXAN_2151
MXAN_2152
MXAN_2154
MXAN_2155
MXAN_2160
MXAN_2162
MXAN_2163
MXAN_2164
MXAN_2165
WP_011552246.1
WP_011552247.1
MXAN_2170
MXAN_2171
WP_011552252.1
WP_011552253.1
MXAN_2176
MXAN_2177
MXAN_2178
MXAN_2179
MXAN_2180
WP_011552260.1
MXAN_2184
MXAN_2185
MXAN_2186
MXAN_2188
MXAN_2189
MXAN_2191
MXAN_2194
MXAN_2195
MXAN_2200
MXAN_2201
MXAN_2202
MXAN_2203
MXAN_2204
MXAN_2205
MXAN_2206
MXAN_2207
MXAN_2208
MXAN_2209
MXAN_2212
MXAN_2213
MXAN_2215
MXAN_2216
MXAN_2217
MXAN_2218
MXAN_2219
MXAN_2221
MXAN_2223
MXAN_2225
MXAN_2226
MXAN_2230
nan
MXAN_2232
WP_011552309.1
WP_011552310.1
WP_011552311.1
MXAN_2236
MXAN_2237
MXAN_2238
MXAN_2239
MXAN_2240
MXAN_2241
MXAN_2242
MXAN_2243
MXAN_2244
MXAN_2245
MXAN_2246
MXAN_2247
MXAN_2249
MXAN_2250
MXAN_2251
MXAN_2252
MXAN_2253
MXAN_2255
MXAN_2256
MXAN_2257
MXAN_2258
MXAN_2259
MXAN_2260
MXAN_2261
MXAN_2262
MXAN_2263
MXAN_2264
MXAN_2265
MXAN_2266
MXAN_2267
MXAN_2268
MXAN_2270
MXAN_2273
MXAN_2274
MXAN_2276
MXAN_2277
MXAN_2278
MXAN_2280
MXAN_2281
MXAN_2282
MXAN_2283
MXAN_2284
MXAN_2285
MXAN_2286
nan
MXAN_2289
MXAN_2290
MXAN_2291
MXAN_2292
MXAN_2293
WP_011552370.1
MXAN_2295
MXAN_2296
MXAN_2297
MXAN_2298
MXAN_2299
MXAN_2301
MXAN_2304
MXAN_2306
MXAN_2307
MXAN_2309
MXAN_2310
MXAN_2311
MXAN_2312
MXAN_2313
MXAN_2314
MXAN_2315
MXAN_2316
MXAN_2317
MXAN_2318
MXAN_2322
MXAN_2323
MXAN_2325
MXAN_2326
MXAN_2327
MXAN_2330
MXAN_2331
MXAN_2332
MXAN_2333
MXAN_2334
MXAN_2335
MXAN_2336
MXAN_2337
MXAN_2338
WP_011552414.1
MXAN_2340
MXAN_2342
MXAN_2343
MXAN_2344
MXAN_2345
MXAN_2346
MXAN_2348
MXAN_2349
MXAN_2350
MXAN_2351
MXAN_2352
MXAN_2354
MXAN_2355
MXAN_2356
MXAN_2357
MXAN_2358
MXAN_2359
MXAN_2360
MXAN_2361
MXAN_2362
MXAN_2363
MXAN_2366
MXAN_2367
MXAN_2368
MXAN_2369
MXAN_2371
MXAN_2372
MXAN_2373
MXAN_2374
MXAN_2375
MXAN_2377
MXAN_2378
MXAN_2379
MXAN_2380
MXAN_2381
MXAN_2382
MXAN_2383
WP_011552459.1
MXAN_2385
MXAN_2386
MXAN_2387
MXAN_2388
nan
MXAN_2390
MXAN_2391
MXAN_2392
MXAN_2394
MXAN_2395
MXAN_2396
MXAN_2397
MXAN_2398
MXAN_2399
MXAN_2400
MXAN_2401
MXAN_2402
MXAN_2403
MXAN_2404
MXAN_2405
MXAN_2406
MXAN_2407
MXAN_2408
MXAN_2409
MXAN_2410
MXAN_2411
MXAN_2413
MXAN_2415
MXAN_2416
MXAN_2417
MXAN_2419
MXAN_2420
MXAN_2421
MXAN_2422
MXAN_2423
MXAN_2425
MXAN_2426
MXAN_2427
MXAN_2428
MXAN_2429
MXAN_2430
MXAN_2431
MXAN_2432
MXAN_2433
MXAN_2434
MXAN_2436
MXAN_2437
MXAN_2438
MXAN_2439
MXAN_2440
MXAN_2441
MXAN_2442
MXAN_2443
MXAN_2444
MXAN_2445
MXAN_2449
MXAN_2450
MXAN_2451
MXAN_2453
MXAN_2454
MXAN_2455
MXAN_2458
MXAN_2459
MXAN_2462
MXAN_2463
MXAN_2464
MXAN_2465
MXAN_2466
MXAN_2467
MXAN_2468
MXAN_2469
MXAN_2470
MXAN_2471
MXAN_2472
MXAN_2475
MXAN_2476
MXAN_2477
MXAN_2478
MXAN_2480
MXAN_2482
MXAN_2483
MXAN_2485
MXAN_2486
MXAN_2489
MXAN_2490
MXAN_2491
MXAN_2492
MXAN_2495
MXAN_2496
MXAN_2497
MXAN_2498
MXAN_2499
MXAN_2500
MXAN_2501
MXAN_2502
MXAN_2503
MXAN_2504
MXAN_2505
MXAN_2507
MXAN_2508
MXAN_2509
MXAN_2510
MXAN_2512
MXAN_2513
MXAN_2514
MXAN_2515
MXAN_2516
MXAN_2518
MXAN_2519
MXAN_2520
MXAN_2521
MXAN_2522
MXAN_2523
MXAN_2524
MXAN_2525
MXAN_2526
MXAN_2527
MXAN_2530
MXAN_2531
MXAN_2532
MXAN_2533
MXAN_2534
MXAN_2535
MXAN_2536
MXAN_2537
MXAN_2539
MXAN_2540
MXAN_2543
MXAN_2544
MXAN_2547
MXAN_2548
MXAN_2549
MXAN_2550
MXAN_2551
MXAN_2552
MXAN_2553
nan
MXAN_2555
MXAN_2556
nan
MXAN_2558
MXAN_2559
MXAN_2560
MXAN_2561
MXAN_2563
MXAN_2564
MXAN_2565

In [29]:
for i in DataTable.index:
    if type(DataTable.GeneNames[i]) != str:
        DataTable = DataTable.drop(labels=i)
    if "MXAN" not in DataTable.GeneNames[i]:
        DataTable = DataTable.drop(labels=i)

DataTable.GeneNames

KeyError: 59

In [ ]:
# DataTable.to_csv("/home/mickael/github/M_xanthus-E_coli-Predation/data/Raw/WT_vs_4preys_iMAT.csv", sep = ",")