In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import cobra
from cobra.core.configuration import Configuration
from cobra.io import read_sbml_model, write_sbml_model
from cobra.flux_analysis import flux_variability_analysis
from tqdm import tqdm

In [2]:
M_xanthus = read_sbml_model("../M_xanthus_model_V3.xml")
M_xanthus

In [554]:
M_xanthus.summary()

In [ ]:
iMAT_res = pd.read_csv("/home/mickael/github/M_xanthus-E_coli-Predation/results/quantiles/iMAT/log2FoldChange/epsilon_1.0_quantiles_40_70_name.csv", sep=";", index_col="Unnamed: 0")
#iMAT_res = pd.read_csv("/home/mickael/github/M_xanthus-E_coli-Predation/results/iMat/reactionData_classification_name.csv", sep=";", index_col="Unnamed: 0")
iMAT_res

,reaction_id,flux_value,classification,y_f,y_r
0,"2-amino-4-hydroxy-6-hydroxymethyl-7,8-dihydrop...",0.0,moderate,NaN,NaN
1,gamma-L-glutamyl-L-cysteine:glycine ligase (AD...,1.0,high,1.0,0.0
2,R07600 [c],0.0,low,1.0,0.0
3,IMP:diphosphate phospho-D-ribosyltransferase [c],0.0,moderate,NaN,NaN
4,"2,3-dihydro-2,3-dihydroxybenzoate:NAD+ oxidore...",0.0,low,1.0,0.0
...,...,...,...,...,...
1362,Exchange for D-Lactate [e],255.0,NaN,NaN,NaN
1363,Exchange for H2S2O3 [e],0.0,NaN,NaN,NaN
1364,Demand for glycogen(n-1) [c],0.0,NaN,NaN,NaN
1365,Demand for Biomass [c],0.0,NaN,NaN,NaN
1366,Demand for S-Adenosyl-4-methylthio-2-oxobutano...,0.0,NaN,NaN,NaN

In [ ]:
iMAT_res_filter = iMAT_res[iMAT_res.flux_value != 0] # take all the flux different from 0 (so active one)
#iMAT_res_filter = iMAT_res[iMAT_res.flux != 0]
iMAT_res_filter

,reaction_id,flux_value,classification,y_f,y_r
1,gamma-L-glutamyl-L-cysteine:glycine ligase (AD...,1.000000,high,1.0,0.0
12,L-glutamate:L-cysteine gamma-ligase (ADP-formi...,1.000000,high,1.0,0.0
14,ATP:dCDP phosphotransferase [c],1.000000,high,1.0,0.0
26,oxalosuccinate carboxy-lyase (2-oxoglutarate-f...,501.142860,moderate,NaN,NaN
31,Sulfate adenyltransferase [c],1.000000,high,1.0,0.0
...,...,...,...,...,...
1341,Exchange for Enterobactin [e],1000.000000,NaN,NaN,NaN
1353,Exchange for NH3 [e],5.785714,NaN,NaN,NaN
1357,Exchange for Acetoacetate [e],-754.214290,NaN,NaN,NaN
1360,Exchange for O2 [e],-870.500000,NaN,NaN,NaN
1362,Exchange for D-Lactate [e],255.000000,NaN,NaN,NaN

In [557]:
# Create dictionary to convert name to id
Dico_reaction = {}
for i in M_xanthus.reactions._dict:
    Dico_reaction[M_xanthus.reactions.get_by_id(i).name] = i
print(Dico_reaction)

# create a list of reaction id that should have flux
active_list = []
for i in iMAT_res_filter["reaction_id"]:
    active_list.append(Dico_reaction[i])
print(active_list)

{'2-amino-4-hydroxy-6-hydroxymethyl-7,8-dihydropteridine-diphosphate:4-aminobenzoate 2-amino-4-hydroxydihydropteridine-6-methenyltransferase [c]': 'rxn02201_c', 'gamma-L-glutamyl-L-cysteine:glycine ligase (ADP-forming) [c]': 'rxn00351_c', 'R07600 [c]': 'rxn07431_c', 'IMP:diphosphate phospho-D-ribosyltransferase [c]': 'rxn00836_c', '2,3-dihydro-2,3-dihydroxybenzoate:NAD+ oxidoreductase [c]': 'rxn01094_c', 'acetyl-CoA:L-serine O-acetyltransferase [c]': 'rxn00423_c', 'palmitoyl-lipoteichoic acid synthesis (n=24), linked, glucose substituted [c]': 'rxn10298_c', 'ATP:CMP phosphotransferase [c]': 'rxn00364_c', 'Transport of dicarboxylates, extracellular [c]': 'rxn05561_c', 'UDP-N-acetyl-D-glucosamine:undecaprenyl-diphospho-N-acetylmuramoyl-L-alanyl-gamma-D-glutamyl-meso-2,6-diaminopimeloyl-D-alanyl-D-alanine 4-beta-N-acetylglucosaminlytransferase [c]': 'rxn03408_c', 'Isochorismate pyruvate-hydrolase [c]': 'rxn02177_c', 'FACOAL160(ISO) [c]': 'rxn05250_c', 'L-glutamate:L-cysteine gamma-ligase (ADP-forming) [c]': 'rxn00646_c', '7-methyl-trans-oct-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05440_c', 'ATP:dCDP phosphotransferase [c]': 'rxn01673_c', 'trans-4-Hydroxy-L-proline 2-epimerase [c]': 'rxn02360_c', 'R03270 [c]': 'rxn02342_c', 'ornithine transport via ABC system [c]': 'rxn05156_c', '(S)-3-Hydroxybutanoyl-CoA:NADP+ oxidoreductase [c]': 'rxn01452_c', 'GDP-mannose 4,6-hydro-lyase (GDP-4-dehydro-6-deoxy-D-mannose-forming) [c]': 'rxn00642_c', 'dTDP-4-dehydro-6-deoxy-D-glucose 3,5-epimerase [c]': 'rxn02000_c', '(S)-3-Hydroxyhexadecanoyl-CoA:NAD+ oxidoreductase [c]': 'rxn03239_c', '[Acyl-carrier-protein] acetyltransferase [c]': 'rxn05458_c', "ATP:2'-deoxy-5-hydroxymethylcytidine-5'-diphosphate phosphotransferase [c]": 'rxn00107_c', 'R05611 [c]': 'rxn12008_c', "pyridoxine 5'-phosphate synthase [c]": 'rxn04070_c', 'oxalosuccinate carboxy-lyase (2-oxoglutarate-forming) [c]': 'rxn00199_c', 'inosine:phosphate alpha-D-ribosyltransferase [c]': 'rxn01358_c', '(S)-3-Hydroxyisobutyryl-CoA hydrolase [c]': 'rxn03433_c', 'isohexadecanoyl-CDPdiacylglycerol-serine O-phosphatidyltransferase [c]': 'rxn10231_c', 'RXN0-6987.c [c]': 'rxn12637_c', 'Sulfate adenyltransferase [c]': 'rxn09240_c', 'Acetate:CoA ligase (ADP-forming) [c]': 'rxn00172_c', 'ATP:dCMP phosphotransferase [c]': 'rxn01219_c', '(3R)-3-Hydroxybutanoyl-CoA hydro-lyase [c]': 'rxn02168_c', 'N6-(1,2-dicarboxyethyl)AMP AMP-lyase (fumarate-forming) [c]': 'rxn00800_c', '1,4-dihydroxy-2-naphthoate octaprenyltransferase [c]': 'rxn08333_c', 'L-allo-threonine dehydrogenase [c]': 'rxn08172_c', "dCTP:cytidine 5'-phosphotransferase [c]": 'rxn01705_c', "(R)-4'-Phosphopantothenate:L-cysteine ligase [c]": 'rxn12512_c', 'UDP-glucose:NAD+ 6-oxidoreductase [c]': 'rxn00211_c', 'ATP:L-glutamate 5-phosphotransferase [c]': 'rxn00179_c', 'prephytoene diphosphate:geranylgeranyl-diphosphate geranylgeranyltransferase [c]': 'rxn05031_c', '10-Formyltetrahydrofolate:L-glutamate ligase (ADP-forming) [c]': 'rxn01210_c', 'acetyl-CoA:L-glutamate N-acetyltransferase [c]': 'rxn00192_c', "2'-Deoxycytidine 5'-monophosphate phosphohydrolase [c]": 'rxn01218_c', 'O-Succinylbenzoyl-CoA 1,4-dihydroxy-2-naphthoate-lyase [c]': 'rxn02898_c', 'Transport of succinate, extracellular [c]': 'rxn05654_c', '4-Hydroxybenzoate transport via proton symport [c]': 'rxn12549_c', 'ATP:D-fructose-6-phosphate 1-phosphotransferase [c]': 'rxn00545_c', 'Lysophospholipase L1 (2-acylglycerophosphoethanolamine, n-C16:1) (periplasm) [c]': 'rxn08807_c', 'L-methionine R-oxide transport via ABC system [c]': 'rxn05614_c', 'UTP:D-Tagatose 6-phosphate 1-phosphotransferase [c]': 'rxn02316_c', '3-Oxopropanoate:NAD+ oxidoreductase (decarboxylating, CoA-acetylating) [c]': 'rxn00501_c', 'stearoyl-cardiolipin synthase [c]': 'rxn10336_c', '5-Amino-2-oxopentanoate:2-oxoglutarate aminotransferase [c]': 'rxn02320_c', 'Uroporphyrinogen I carboxy-lyase [c]': 'rxn03384_c', '2-amino-4-hydroxy-6-(D-erythro-1,2,3-trihydroxypropyl)-7,8-dihydropteridine glycolaldehyde-lyase [c]': 'rxn02504_c', 'L-Aspartic acid:oxygen oxidoreductase (deaminating) [c]': 'rxn00262_c', 'R04638 [c]': 'rxn03173_c', "1-(5'-Phosphoribosyl)-5-amino-4-imidazolecarboxamide:pyrophosphate phosphoribosyltransferase [c]": 'rxn03039_c', 'isopentadecanoyl-CDPdiacylglycerol:sn-glycerol-3-phosphate 3-phosphatidyltransferase [c]': 'rxn10262_c', 'succinate dehyrdogenase [c]': 'rxn10126_c', 'anteisopentadecanoyl-glycerol-3-phosphate O-acyltransferase [c]': 'rxn10209_c', '1-tetradecanoyl-sn-glycerol 3-phosphate O-acyltransferase (n-C14:0) [c]': 'rxn08084_c', 'isohexadecanoyl-phosphatidate cytidylyltransferase [c]': 'rxn10225_c', 'trans,trans-Farnesyl-diphosphate:isopentenyl-diphosphate farnesyltranstransferase [c]': 'rxn01486_c', '15-methyl-trans-hexa-dec-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05444_c', '(3R)-3-Hydroxybutanoyl-[acyl-carrier-protein] hydro-lyase [c]': 'rxn05333_c', 'isoheptadecanoyl-glycerol-3-phosphate O-acyltransferase [c]': 'rxn10205_c', 'D-ribulose 5-phosphate formate-lyase (L-3,4-dihydroxybutan-2-one 4-phosphate-forming) [c]': 'rxn05040_c', '2-phenylacetamide amidohydrolase [c]': 'rxn01843_c', 'Lactose galactohydrolase [c]': 'rxn15230_c', 'glycerone phosphate:iminosuccinate alkyltransferase (cyclizing) [c]': 'rxn02988_c', 'S-(hydroxymethyl)glutathione dehydrogenase [c]': 'rxn04792_c', 'L-serine ammonia-lyase [c]': 'rxn00165_c', 'isotetradecanoyl-CDPdiacylglycerol-serine O-phosphatidyltransferase [c]': 'rxn10228_c', 'D-arabinose-5-phosphate aldose-ketose-isomerase [c]': 'rxn01117_c', 'diphosphate phosphohydrolase [c]': 'rxn00001_c', 'murein D,D-endopeptidase (murein4px4p) (periplasm) [c]': 'rxn08895_c', '2-Methyl-3-oxopropanoate:NAD+ oxidoreductase (CoA-propanoylating) [c]': 'rxn00671_c', 'phosphate ABC transporter permease protein [c]': 'rxn11268_c', "orotidine-5'-phosphate carboxy-lyase (UMP-forming) [c]": 'rxn00710_c', '2-methyl-4-amino-5-hydroxymethylpyrimidine-diphosphate:4-methyl-5-(2-phosphoethyl)-thiazole 2-methyl-4-aminopyridine-5-methenyltransferase [c]': 'rxn02305_c', 'R04134 [c]': 'rxn02885_c', 'Lysophospholipase L2 (2-acylglycerophosphotidate, n-C12:0) [c]': 'rxn08817_c', '5-methyltetrahydrofolate:NADP+ oxidoreductase [c]': 'rxn00910_c', 'L-Serine hydro-lyase (adding homocysteine) [c]': 'rxn00953_c', "dATP:uridine 5'-phosphotransferase [c]": 'rxn01129_c', 'diacylglycerol kinase (n-C14:1) [c]': 'rxn08296_c', 'Cytosine aminohydrolase [c]': 'rxn00717_c', 'salicin transport via PEP:Pyr PTS [c]': 'rxn05647_c', 'hypoxanthine:NAD+ oxidoreductase [c]': 'rxn01297_c', 'anteisoheptadecanoyl-Diacylglycerol kinase [c]': 'rxn10254_c', '(1S,2R)-1-C-(indol-3-yl)glycerol 3-phosphate D-glyceraldehyde-3-phosphate-lyase [c]': 'rxn01682_c', 'Lysophospholipase L1 (2-acylglycerophosphotidate, n-C12:0) (periplasm) [c]': 'rxn08796_c', 'nitrous-oxide:NAD+ oxidoreductase [c]': 'rxn01806_c', 'Maltodextrin phosphorylase (maltopentaose) [c]': 'rxn08941_c', "ATP:2,3,2',3'-tetrakis(3-hydroxytetradecanoyl)-D-glucosaminyl-beta-D-1,6-glucosaminyl-alpha-phosphate 4-O'-phosphotransferase [c]": 'rxn03181_c', 'UDP-N-acetylmuramate:L-alanyl-gamma-D-glutamyl-meso-diaminopimelate-D-alanine ligase [c]': 'rxn09360_c', 'phosphoenolpyruvate:D-arabinose-5-phosphate C-(1-carboxyvinyl)transferase (phosphate-hydrolysing, 2-carboxy-2-oxoethyl-forming) [c]': 'rxn02331_c', 'dihydrolipoylprotein:NAD+ oxidoreductase [c]': 'rxn06493_c', 'Gly-Phe aminopeptidase [c]': 'rxn12846_c', 'ATP:L-aspartate 4-phosphotransferase [c]': 'rxn00337_c', 'CDP-diacylglycerol synthetase (n-C14:1) [c]': 'rxn08308_c', '3-Hydroxy-L-kynurenine hydrolase [c]': 'rxn01930_c', "Pyridoxamine-5'-phosphate:oxygen oxidoreductase (deaminating) [c]": 'rxn00208_c', 'Lysophospholipase L2 (2-acylglycerophosphotidate, n-C18:1) [c]': 'rxn08823_c', '6-methyl-trans-oct-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05434_c', 'butyryl-[acyl-carrier protein]:malonyl-[acyl-carrier-protein] C-acyltransferase (decarboxylating) [c]': 'rxn05346_c', 'L-histidine ammonia-lyase (urocanate-forming) [c]': 'rxn00867_c', 'Hexanoyl-CoA:acetyl-CoA C-acyltransferase [c]': 'rxn03248_c', 'Amylomaltase (maltotetraose) [c]': 'rxn08127_c', '5-methyl-3-hydroxy-hexanoyl-ACP hydro-lyase [c]': 'rxn05386_c', 'Cadmium-translocating P-type ATPase [c]': 'rxn05516_c', 'O3-acetyl-L-serine:thiosulfate 2-amino-2-carboxyethyltransferase (reducing, L-cysteine-forming) [c]': 'rxn05733_c', 'L-aspartate:L-glutamine amido-ligase (AMP-forming) [c]': 'rxn00416_c', 'Phosphatidylserine syntase (n-C14:0) [c]': 'rxn09206_c', 'glutarate-semialdehyde:NAD+ oxidoreductase [c]': 'rxn01729_c', 'Maltose alpha-D-glucosylmutase [c]': 'rxn01134_c', 'R03316 [c]': 'rxn02376_c', 'acyl-[acyl-carrier-protein] synthetase  (n-C16:1) [c]': 'rxn08017_c', 'Phosphatidylserine syntase (n-C16:1) [c]': 'rxn09209_c', 'Glycerophosphodiester phosphodiesterase [c]': 'rxn08669_c', 'biotin-carboxyl-carrier-protein:carbon-dioxide ligase (ADP-forming) [c]': 'rxn06672_c', 'O3-acetyl-L-serine:hydrogen-sulfide 2-amino-2-carboxyethyltransferase [c]': 'rxn00649_c', 'ATP:shikimate 3-phosphotransferase [c]': 'rxn01739_c', 'Nicotinate D-ribonucleotide phosphohydrolase [c]': 'rxn02400_c', 'Prephenate:NAD+ oxidoreductase(decarboxylating) [c]': 'rxn01268_c', 'GTP:alpha-D-mannose-1-phosphate guanylyltransferase [c]': 'rxn00641_c', "ATP:adenylylsulfate 3'-phosphotransferase [c]": 'rxn00361_c', 'Octanoyl-CoA:oxygen 2-oxidoreductase [c]': 'rxn02679_c', 'R07603 [c]': 'rxn07434_c', 'LL-2,6-Diaminoheptanedioate 2-epimerase [c]': 'rxn01974_c', 'N-Formimino-L-glutamate iminohydrolase [c]': 'rxn01640_c', "guanosine-3',5'-bis(diphosphate) 3'-diphosphohydrolase [c]": 'rxn00242_c', 'RXN0-6977.c [c]': 'rxn12641_c', 'NADH dehydrogenase (menaquinone-8 & 0 protons) [c]': 'rxn08971_c', 'copper transport out via proton antiport [c]': 'rxn08275_c', '1-Pyrroline-4-hydroxy-2-carboxylate aminohydrolase (decyclizing) [c]': 'rxn01635_c', '5-Methylthio-5-deoxy-D-ribose-1-phosphate ketol-isomerase [c]': 'rxn03057_c', 'porphobilinogen:(4-[2-carboxyethyl]-3-[carboxymethyl]pyrrol-2-yl)methyltransferase (hydrolysing) [c]': 'rxn00060_c', 'hexanoyl-[acyl-carrier protein]:malonyl-[acyl-carrier-protein] C-acyltransferase (decarboxylating) [c]': 'rxn05350_c', 'Phosphatidylserine decarboxylase (n-C14:0) [c]': 'rxn09198_c', 'Lysophospholipase L2 (2-acylglycerophosphoethanolamine, n-C12:0) [c]': 'rxn08838_c', 'ATP:pyruvate 2-O-phosphotransferase [c]': 'rxn00148_c', 'ATP:(R)-glycerate 3-phosphotransferase [c]': 'rxn01102_c', 'D-glucosamine transport via PEP:Pyr PTS [c]': 'rxn05569_c', "ATP:dephospho-CoA 3'-phosphotransferase [c]": 'rxn00100_c', "Inosine 5'-triphosphate pyrophosphohydrolase [c]": 'rxn00514_c', '1-(5-phospho-D-ribosyl)-ATP:diphosphate phospho-alpha-D-ribosyl-transferase [c]': 'rxn00789_c', '7-methyl-3-hydroxy-octanoyl-ACP hydro-lyase [c]': 'rxn05390_c', 'D-fructose transport via PEP:Pyr PTS [c]': 'rxn05560_c', '12-methyl-trans-tetra-dec-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05437_c', 'quinone reductase [c]': 'rxn08976_c', 'D-glyceraldehyde-3-phosphate:NAD+ oxidoreductase (phosphorylating) [c]': 'rxn00781_c', 'TRANS-RXNBWI-115401.ce.maizeexp.OH_OH [c]': 'rxn05319_c', '1D-myo-Inositol 1-phosphate phosphohydrolase [c]': 'rxn00881_c', 'Na+/glutamate symport [c]': 'rxn05298_c', 'Protein-N(pai)-phosphohistidine:sugar N(pai)-phosphotransferase [c]': 'rxn06578_c', 'Propanoyl-CoA:carbon-dioxide ligase (ADP-forming) [c]': 'rxn01355_c', 'isoheptadecanoyl-cardiolipin synthase [c]': 'rxn10337_c', 'UDP-N-acetyl-D-glucosamine 2-epimerase [c]': 'rxn00297_c', 'dihydroorotic acid (menaquinone-8) [c]': 'rxn08336_c', '13-methyl-3-oxo-tetra-decanoyl-ACP:NADP+ oxidoreductase [c]': 'rxn05401_c', 'Hydroxymethylbilane hydro-lyase(cyclizing) [c]': 'rxn02264_c', 'anteisoheptadecanoyl-cardiolipin synthase [c]': 'rxn10338_c', 'Phosphatidylserine decarboxylase (n-C18:0) [c]': 'rxn09202_c', '(S)-3-Hydroxybutanoyl-CoA:NAD+ oxidoreductase [c]': 'rxn01451_c', 'UDPMurAc(oyl-L-Ala-D-gamma-Glu-L-Lys-D-Ala-D-Ala):undecaprenyl-phosphate phospho-N-acetylmuramoyl-pentapeptide-transferase [c]': 'rxn03903_c', 'ATP:AMP phosphotransferase [c]': 'rxn00097_c', 'dCMP aminohydrolase [c]': 'rxn01217_c', '2-Dehydro-3-deoxy-D-arabino-heptonate 7-phosphate phosphate-lyase (cyclyzing) [c]': 'rxn02212_c', 'ATP:alpha-D-glucose-1-phosphate adenylyltransferase [c]': 'rxn00695_c', 'Pyruvate:carbon-dioxide ligase (ADP-forming) [c]': 'rxn00250_c', 'Dodecanoyl-[acyl-carrier protein]:malonyl-CoA C-acyltransferase(decarboxylating, oxoacyl- and enoyl-reducing) [c]': 'rxn05324_c', 'Copper transport via ABC system [c]': 'rxn10481_c', 'ATP:cob(I)yrinic acid-a,c-diamide Cobeta-adenosyltransferase [c]': 'rxn03535_c', '5,10-Methylenetetrahydrofolate:glycine hydroxymethyltransferase [c]': 'rxn00692_c', 'ATP:D-fructose-1-phosphate 6-phosphotransferase [c]': 'rxn01492_c', '2-(Nomega-L-arginino)succinate arginine-lyase (fumarate-forming) [c]': 'rxn00802_c', 'lauroyl-CoA hydrolase [c]': 'rxn08440_c', 'L-Histidinol-phosphate phosphohydrolase [c]': 'rxn02160_c', 'Lysophospholipase L1 (2-acylglycerophosphotidate, n-C18:1) (periplasm) [c]': 'rxn08802_c', 'CTP:D-Tagatose 6-phosphate 1-phosphotransferase [c]': 'rxn02315_c', 'Homogentisate:oxygen 1,2-oxidoreductase (decyclizing) [c]': 'rxn01825_c', 'anteisopentadecanoyl-CDPdiacylglycerol-serine O-phosphatidyltransferase [c]': 'rxn10230_c', 'Lauroyl-CoA:(acceptor) 2,3-oxidoreductase [c]': 'rxn02720_c', "Guanosine 5'-monophosphate phosphohydrolase [c]": 'rxn00913_c', 'dTDPglucose 4,6-hydro-lyase [c]': 'rxn01997_c', 'Lysophospholipase L1 (2-acylglycerophosphoethanolamine, n-C18:1) (periplasm) [c]': 'rxn08809_c', 'UTP:pyruvate 2-O-phosphotransferase [c]': 'rxn00460_c', 'acetaldehyde:NAD+ oxidoreductase (CoA-acetylating) [c]': 'rxn00171_c', 'TRANS-RXNBWI-115531.ce [c]': 'rxn05578_c', 'Acetyl-CoA:acetyl-CoA C-acetyltransferase [c]': 'rxn00178_c', 'ATP:L-selenomethione S-adenosyltransferase [c]': 'rxn03264_c', "Orotidine-5'-phosphate:diphosphate phospho-alpha-D-ribosyl-transferase [c]": 'rxn01362_c', '2-Amino-4-hydroxy-6-(erythro-1,2,3-trihydroxypropyl) dihydropteridine triphosphate hydrolase [c]': 'rxn03174_c', 'ATP:D-glycero-beta-D-manno-heptose 7-phosphate 1-phosphotransferase [c]': 'rxn03918_c', 'nonpolar-amino-acid-transporting ATPase [c]': 'rxn05168_c', 'D-Fructose-1,6-bisphosphate 1-phosphohydrolase [c]': 'rxn00549_c', 'NAD-dependent threonine 4-phosphate dehydrogenase [c]': 'rxn03951_c', "S-methyl-5'-thioadenosine:phosphate S-methyl-5-thio-alpha-D-ribosyl-transferase [c]": 'rxn01022_c', '8-methyl-3-oxo-nonanoyl-ACP:NADP+ oxidoreductase [c]': 'rxn05418_c', 'Acetaldehyde:NAD+ oxidoreductase [c]': 'rxn00506_c', 'NAD kinase (dTTP) [c]': 'rxn10060_c', '(2S,3S)-3-hydroxy-2-methylbutanoyl-CoA:NAD+ oxidoreductase [c]': 'rxn02933_c', 'Chorismate pyruvate-lyase (amino-accepting) [c]': 'rxn00727_c', 'palmitoyl-lipoteichoic acid synthesis (n=24), linked, N-acetylglucosamine substituted [c]': 'rxn10307_c', 'mannitol transport via PEP:Pyr PTS [c]': 'rxn05617_c', 'UDP-N-acetyl-D-mannosamine:N-acetyl-beta-D-glucosaminyldiphosphoundecaprenol beta-1,4-N-acetylmannosaminyltransferase [c]': 'rxn03852_c', 'dGTP:pyruvate 2-O-phosphotransferase [c]': 'rxn01354_c', '(S)-2-methylbutanoyl-CoA:oxygen 2,3-oxidoreductase [c]': 'rxn02268_c', 'GTP:oxaloacetate carboxy-lyase (adding GTP;phosphoenolpyruvate-forming) [c]': 'rxn00305_c', "2'-Deoxyguanosine 5'-monophosphate phosphohydrolase [c]": 'rxn01445_c', 'FACOAL150(anteiso) [c]': 'rxn05248_c', 'sn-Glycerol-3-phosphate:NADP+ 2-oxidoreductase [c]': 'rxn00612_c', 'FabH [c]': 'rxn08766_c', 'oligopeptide-transporting ATPase [c]': 'rxn05539_c', 'Lysophospholipase L2 (2-acylglycerophosphoethanolamine, n-C16:0) [c]': 'rxn08841_c', '3-Hydroxyoctodecanoyl-ACP:NADP+ oxidoreductase [c]': 'rxn05461_c', 'L-Histidinol:NAD+ oxidoreductase [c]': 'rxn02159_c', 'isotetradecanoyl-phosphatidate cytidylyltransferase [c]': 'rxn10222_c', 'glycine:oxygen oxidoreductase (deaminating) [c]': 'rxn00269_c', 'anteisopentadecanoyl-CDPdiacylglycerol:sn-glycerol-3-phosphate 3-phosphatidyltransferase [c]': 'rxn10263_c', '(5-Glutamyl)-peptide:amino-acid 5-glutamyltransferase [c]': 'rxn02791_c', 'TRANS-RXN-173.ce [c]': 'rxn05466_c', 'Lysophospholipase L1 (2-acylglycerophosphoglycerol, n-C16:1) (periplasm) [c]': 'rxn08814_c', "Xanthosine-5'-phosphate:L-glutamine amido-ligase (AMP-forming) [c]": 'rxn00917_c', 'Lysophospholipase L2 (2-acylglycerophosphoglycerol, n-C12:0) [c]': 'rxn08845_c', 'L-Arginine iminohydrolase [c]': 'rxn00395_c', 'L-Kynurenine,NADPH:oxygen oxidoreductase (3-hydroxylating) [c]': 'rxn01438_c', 'GTP 7,8-8,9-dihydrolase (diphosphate-forming) [c]': 'rxn00300_c', '2-methylpropanoyl-CoA:enzyme N6-(dihydrolipoyl)lysine S-(2-methylpropanoyl)transferase [c]': 'rxn01925_c', 'Estrone 3-sulfate sulfohydrolase [c]': 'rxn02798_c', 'Phenylpyruvate:oxygen oxidoreductase (hydroxylating,decarboxylating) [c]': 'rxn00999_c', 'Lysophospholipase L1 (2-acylglycerophosphotidate, n-C16:0) (periplasm) [c]': 'rxn08799_c', 'sarcosine:oxygen oxidoreductase (demethylating) [c]': 'rxn00433_c', 'O4-succinyl-L-homoserine:hydrogen sulfide S-(3-amino-3-carboxypropyl)transferase [c]': 'rxn05957_c', '(3R)-3-Hydroxypalmitoyl-[acyl-carrier-protein] hydro-lyase [c]': 'rxn05332_c', 'formamidopyrimidine nucleoside triphosphate amidohydrolase [c]': 'rxn03419_c', 'glycerol-3-phosphate acyltransferase (C18:0) [c]': 'rxn08551_c', 'isopentadecanoyl-Diacylglycerol kinase [c]': 'rxn10256_c', 'propanoyl-CoA:oxaloacetate C-propanoyltransferase (thioester-hydrolysing, 1-carboxyethyl-forming) [c]': 'rxn00679_c', "dTTP:uridine 5'-phosphotransferase [c]": 'rxn01516_c', 'sn-Glycero-3-phosphocholine glycerophosphohydrolase [c]': 'rxn00758_c', 'anteisopentadecanoyl-lipoteichoic acid synthesis (n=24), linked, N-acetylglucosamine substituted [c]': 'rxn10314_c', 'Phosphatidylglycerol synthase (n-C16:0) [c]': 'rxn09111_c', 'O-acetyl-L-homoserine acetate-lyase (L-homocysteine forming) [c]': 'rxn06078_c', 'L-ornithine ammonia-lyase (cyclizing; L-proline-forming) [c]': 'rxn00471_c', 'maltose transport via PEP:Pyr PTS [c]': 'rxn05607_c', 'TRANS-RXN-3.ce [c]': 'rxn05595_c', 'Decanoyl-[acyl-carrier protein]:malonyl-[acyl-carrier-protein] C-acyltransferase (decarboxylating) [c]': 'rxn05348_c', '8-methyl-trans-dec-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05435_c', '(S)-Hydroxydecanoyl-CoA hydro-lyase [c]': 'rxn03245_c', '(S)-3-Hydroxy-3-methylglutaryl-CoA hydro-lyase (trans-3-methylglutaconyl-CoA-forming) [c]': 'rxn01504_c', '5,10-methylenetetrahydrofolate:NADP+ oxidoreductase [c]': 'rxn00907_c', 'diacylglycerol kinase (n-C18:1) [c]': 'rxn08300_c', '3-Deoxy-D-manno-octulosonate-8-phosphate 8-phosphohydrolase [c]': 'rxn02404_c', 'L-Aspartate-4-semialdehyde hydro-lyase (adding pyruvate and cyclizing) [c]': 'rxn01644_c', 'diacylglycerol kinase (n-C16:0) [c]': 'rxn08297_c', '(S)-3-Hydroxydodecanoyl-CoA hydro-lyase [c]': 'rxn02911_c', '14-methyl-trans-pentadec-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05450_c', 'Gly-Try aminopeptidase [c]': 'rxn12847_c', '4-methyl-3-oxo-pentanoyl-ACP:NADP+ oxidoreductase [c]': 'rxn05410_c', '13-methyl-trans-tetra-dec-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05443_c', 'Phosphatidylglycerol synthase (n-C18:1) [c]': 'rxn09114_c', 'Proline dehydrogenase [c]': 'rxn09188_c', 'Lysophospholipase L2 (2-acylglycerophosphotidate, n-C18:0) [c]': 'rxn08822_c', 'di-trans,poly-cis-decaprenyl-diphosphate:isopentenyl-diphosphate undecaprenylcistransferase [c]': 'rxn05030_c', 'isopentadecanoyl-glycerol-3-phosphate O-acyltransferase [c]': 'rxn10208_c', 'L-Fuculose-1-phosphate lactaldehyde-lyase [c]': 'rxn01620_c', 'dodecanoyl-[acyl-carrier-protein]:malonyl-[acyl-carrier-protein] C-acyltransferase (decarboxylating) [c]': 'rxn05345_c', 'isocitrate glyoxylate-lyase (succinate-forming) [c]': 'rxn00336_c', '10-methyl-3-oxo-undecanoyl-ACP:NADP+ oxidoreductase [c]': 'rxn05422_c', 'R05612 [c]': 'rxn03891_c', '(S)-dihydroorotate amidohydrolase [c]': 'rxn01465_c', 'acyl-CoA:sn-glycerol-

Check reaction bounds and change the bounds (0.0, 0.0) looking at ModelSeed

In [558]:
for i in active_list:
    print(M_xanthus.reactions.get_by_id(i).id + ": " + str(M_xanthus.reactions.get_by_id(i).bounds))

rxn00351_c: (-1000.0, 1000.0)
rxn00646_c: (0.0, 1000.0)
rxn01673_c: (-1000.0, 1000.0)
rxn00199_c: (0.0, 1000.0)
rxn09240_c: (0.0, 1000.0)
rxn00172_c: (-1000.0, 0.0)
rxn02168_c: (-1000.0, 1000.0)
rxn00192_c: (0.0, 1000.0)
rxn00262_c: (-1000.0, 1000.0)
rxn10126_c: (0.0, 1000.0)
rxn15230_c: (-1000.0, 1000.0)
rxn04792_c: (-1000.0, 1000.0)
rxn11268_c: (-1000.0, 0.0)
rxn00910_c: (-1000.0, 1000.0)
rxn00717_c: (-1000.0, 1000.0)
rxn00416_c: (-1000.0, 1000.0)
rxn02376_c: (-1000.0, 1000.0)
rxn00361_c: (0.0, 1000.0)
rxn08971_c: (0.0, 1000.0)
rxn05569_c: (0.0, 0.0)
rxn08976_c: (0.0, 1000.0)
rxn00781_c: (-1000.0, 1000.0)
rxn05298_c: (-1000.0, 1000.0)
rxn01451_c: (-1000.0, 1000.0)
rxn00097_c: (-1000.0, 1000.0)
rxn00802_c: (-1000.0, 1000.0)
rxn00178_c: (-1000.0, 1000.0)
rxn00549_c: (0.0, 1000.0)
rxn00305_c: (-1000.0, 1000.0)
rxn00269_c: (-1000.0, 1000.0)
rxn05466_c: (-1000.0, 1000.0)
rxn00395_c: (0.0, 1000.0)
rxn00471_c: (0.0, 1000.0)
rxn05595_c: (-1000.0, 1000.0)
rxn09188_c: (-1000.0, 1000.0)
rxn00336_c: (-1000.0, 1000.0)
rxn05145_c: (0.0, 1000.0)
rxn01872_c: (-1000.0, 1000.0)
rxn01301_c: (-1000.0, 1000.0)
rxn00248_c: (-1000.0, 1000.0)
rxn00707_c: (-1000.0, 1000.0)
rxn01637_c: (-1000.0, 1000.0)
rxn00566_c: (0.0, 1000.0)
rxn00747_c: (-1000.0, 1000.0)
rxn01108_c: (-1000.0, 1000.0)
rxn05168_c: (0.0, 1000.0)
rxn05256_c: (0.0, 1000.0)
rxn09562_c: (-1000.0, 1000.0)
rxn00213_c: (0.0, 1000.0)
rxn00190_c: (0.0, 1000.0)
rxn00237_c: (-1000.0, 1000.0)
rxn00285_c: (-1000.0, 1000.0)
rxn12844_c: (0.0, 0.0)
rxn00875_c: (-1000.0, 1000.0)
rxn00411_c: (0.0, 1000.0)
rxn00786_c: (-1000.0, 1000.0)
rxn01100_c: (-1000.0, 1000.0)
rxn12848_c: (0.0, 1000.0)
rxn01917_c: (-1000.0, 1000.0)
rxn08528_c: (-1000.0, 1000.0)
rxn03253_c: (-1000.0, 1000.0)
rxn01509_c: (-1000.0, 1000.0)
rxn08528_c: (-1000.0, 1000.0)
rxn01669_c: (-1000.0, 1000.0)
rxn00187_c: (0.0, 1000.0)
rxn00500_c: (-1000.0, 1000.0)
rxn00006_c: (-1000.0, 0.0)
rxn06077_c: (-1000.0, 1000.0)
rxn00137_c: (0.0, 1000.0)
rxn01678_c: (-1000.0, 1000.0)
rxn00872_c: (-1000.0, 1000.0)
rxn01106_c: (-1000.0, 1000.0)
rxn00066_c: (0.0, 1000.0)
rxn10012_c: (-1000.0, 1000.0)
rxn04938_c: (-1000.0, 1000.0)
rxn00412_c: (0.0, 1000.0)
rxn01573_c: (-1000.0, 1000.0)
rxn00650_c: (-1000.0, 1000.0)
rxn00515_c: (-1000.0, 1000.0)
rxn01353_c: (-1000.0, 1000.0)
rxn00552_c: (0.0, 1000.0)
rxn00189_c: (0.0, 1000.0)
rxn00469_c: (-1000.0, 1000.0)
rxn00184_c: (-1000.0, 1000.0)
rxn00379_c: (-1000.0, 1000.0)
rxn00105_c: (0.0, 1000.0)
rxn05484_c: (0.0, 0.0)
rxn05683_c: (0.0, 0.0)
rxn00205_c: (0.0, 1000.0)
rxn00410_c: (0.0, 1000.0)
rxn00799_c: (-1000.0, 1000.0)
rxn08783_c: (0.0, 1000.0)
rxn05312_c: (-1000.0, 0.0)
rxn08975_c: (0.0, 1000.0)
rxn01302_c: (-1000.0, 1000.0)
rxn01109_c: (-1000.0, 1000.0)
rxn00290_c: (-1000.0, 1000.0)
rxn00459_c: (-1000.0, 1000.0)
rxn05153_c: (0.0, 1000.0)
rxn00076_c: (0.0, 1000.0)
rxn05209_c: (-1000.0, 1000.0)
rxn01366_c: (-1000.0, 1000.0)
rxn00260_c: (-1000.0, 1000.0)
rxn05613_c: (-1000.0, 1000.0)
rxn01387_c: (-1000.0, 1000.0)
rxn00350_c: (-1000.0, 1000.0)
rxn05239_c: (0.0, 1000.0)
rxn04954_c: (-1000.0, 1000.0)
rxn09272_c: (-1000.0, 1000.0)
rxn01648_c: (-1000.0, 1000.0)
rxn00086_c: (-1000.0, 1000.0)
rxn01351_c: (0.0, 1000.0)
rxn06600_c: (0.0, 1000.0)
rxn00216_c: (-1000.0, 1000.0)
rxn02005_c: (-1000.0, 1000.0)
rxn00558_c: (-1000.0, 1000.0)
rxn05297_c: (-1000.0, 1000.0)
rxn05651_c: (-1000.0, 1000.0)
rxn00077_c: (-1000.0, 1000.0)
rxn01388_c: (-1000.0, 1000.0)
rxn01241_c: (-1000.0, 1000.0)
rxn00288_c: (-1000.0, 1000.0)
rxn05176_c: (0.0, 1000.0)
rxn01434_c: (-1000.0, 1000.0)
rxn02345_c: (-1000.0, 1000.0)
rxn00119_c: (-1000.0, 1000.0)
rxn01674_c: (-1000.0, 1000.0)
rxn00974_c: (-1000.0, 1000.0)
rxn00605_c: (-1000.0, 1000.0)
rxn01679_c: (-1000.0, 1000.0)
rxn01171_c: (-1000.0, 1000.0)
rxn00409_c: (-1000.0, 1000.0)
rxn10052_c: (-1000.0, 1000.0)
rxn00342_c: (-1000.0, 1000.0)
rxn00256_c: (-1000.0, 1000.0)
rxn00138_c: (0.0, 1000.0)
rxn00504_c: (-1000.0, 1000.0)
rxn05206_c: (-1000.0, 0.0)
rxn00239_c: (-1000.0, 1000.0)
rxn00441_c: (-1000.0, 1000.0)
rxn02465_c: (-1000.0, 0.0)
rxn00623_c: (-1000.0, 0.0)
rxn00104_c: (-1000.0, 1000.0)
rxn00014_c: (-1000.0, 1000.0)
rxn04945_c: (-1000.0, 1000.0)
rxn00686_c: (-1000.0, 1000.0)
rxn00117_c: (-1000.0, 1000.0)
rxn00330_c: (-1000.0, 0.0)
rxn00367_c: (0.0, 1000.0)
rxn00839_c: (-1000.0, 1000.0)
rxn15249_c: (-1000.0, 1000.0)
rxn14419_c: (0.0, 1000.0)
rxn08734_c: (0.0, 1000.0)
rxn14418_c: (0.0, 1000.0)
rxn14420_c: (0.0, 1000.0)
rxn14415_c: (-1000.0, 1000.0)
rxn13741_c: (0.0, 1000.0)
rxn15230_c: (-1000.0, 1000.0)
rxn20583_c: (-1000.0, 1000.0)
rxn05469_c: (0.0, 0.0)
rxn05488_c: (-1000.0, 1000.0)
rxn05468_c: (0.0, 1000.0)
rxn05467_c: (-1000.0, 1000.0)
rxn08502_e: (-1000.0, 1000.0)
rxn08691_c: (-1000.0, 1000.0)
rxn08350_c: (0.0, 0.0)
rxn08689_c: (-1000.0, 1000.0)
rxn09260_c: (0.0, 1000.0)
rxn09330_c: (-1000.0, 1000.0)
rxn00062_c: (0.0, 1000.0)
rxn12603_c: (-100.0, 0.0)
EX_metox_e: (-1000.0, 1000.0)
EX_met_L_e: (-1000.0, 1000.0)
EX_ac_e: (-1000.0, 1000.0)
EX_h2s_e: (-1000.0, 1000.0)
EX_so4_e: (-1000.0, 1000.0)
EX_ppi_e: (-1000.0, 1000.0)
EX_pi_e: (-1000.0, 1000.0)
EX_pyr_e: (-1000.0, 1000.0)
EX_but_e: (-1000.0, 1000.0)
EX_so3_e: (-1000.0, 1000.0)
EX_h2_e: (-1000.0, 1000.0)
EX_Fe3_e: (-1000.0, 1000.0)
EX_gam_e: (-1000.0, 1000.0)
EX_gly_cys_L_e: (-1000.0, 1000.0)
EX_co2_e: (-1000.0, 1000.0)
EX_h_e: (-1000.0, 1000.0)
EX_tre_e: (-1000.0, 1000.0)
EX_glu_L_e: (-1000.0, 1000.0)
EX_feenter_e: (-1000.0, 1000.0)
EX_enter_e: (-1000.0, 1000.0)
EX_nh4_e: (-1000.0, 1000.0)
EX_acac_e: (-1000.0, 1000.0)
EX_o2_e: (-1000.0, 1000.0)
EX_lac_D_e: (-1000.0, 1000.0)

For ModelSeed:

rxn08350 rxn05469 rxn05683 rxn05484 rxn12844 rxn05569

In [559]:
M_xanthus.reactions.rxn05469_c.bounds = [-1000, 1000]
M_xanthus.reactions.rxn05469_c

In [560]:
M_xanthus.reactions.rxn05484_c.bounds = [-1000, 1000]
M_xanthus.reactions.rxn05484_c

In [561]:
M_xanthus.reactions.rxn05569_c.bounds = [0, 1000]
M_xanthus.reactions.rxn05569_c

In [562]:
M_xanthus.reactions.rxn05683_c.bounds = [-1000,1000]
M_xanthus.reactions.rxn05683_c

In [563]:
M_xanthus.reactions.rxn08350_c.bounds = [0, 1000]
M_xanthus.reactions.rxn08350_c

In [564]:
M_xanthus.reactions.rxn12844_c.bounds = [-1000,1000]
M_xanthus.reactions.rxn12844_c

Force to activate specific reaction

In [565]:
M_xanthus.reactions.rxn00910_c

In [566]:
FBA = M_xanthus.optimize()
FBA.fluxes["rxn00910_c"]

np.float64(0.0)

In [ ]:
# Add constraint that force the fluxe to pass there / Infeasable
y = M_xanthus.problem.Variable("y_RXN", type="binary") # add a binary constraint
M_xanthus.add_cons_vars(y)

for i in active_list:
    have_flux = M_xanthus.problem.Constraint(
        M_xanthus.reactions.get_by_id(i).flux_expression - 1 + 1000*(1 - y), # - 1 [threshold] + 1000 [big number] * (1 - y) [if 1 = big number] [if 0 = - big number]
        lb=0,
        ub=0) # force the reaction to have at least 1 (or -1?) flux
    M_xanthus.add_cons_vars(have_flux)

M_xanthus.solver.update()

In [568]:
M_xanthus.reactions.get_by_id("rxn00910_c").bounds

(-1000.0, 1000.0)

In [569]:
FBA = M_xanthus.optimize()
FBA.fluxes["rxn00910_c"]

/home/mickael/miniconda3/envs/Micka_Predation/lib/python3.12/site-packages/cobra/util/solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

np.float64(0.0)

In [570]:
M_xanthus.slim_optimize()

nan

Shut down all others reactions

In [ ]:
for i in M_xanthus.reactions: # Shut down all the non active reaction
    if i.id not in active_list:
        i.bounds = [0,0]
M_xanthus.reactions.OF_BIOMASS.bounds = [-1000, 1000] # except Biomass

M_xanthus.slim_optimize() # Didn't growth

nan

New Data

python3 IntegrationPackage/main.py weighted_iMAT -f 'data/Raw/WT_vs_4preys.txt' -g 'GeneNames' -i 'W1' -m 'M_xanthus_model_V3_hdca_iMAT.xml' -o results/ -d "quantile"

In [6]:
DataTable = pd.read_csv("/home/mickael/github/M_xanthus-E_coli-Predation/data/Raw/WT_vs_4preys.txt", sep = "\t")
DataTable

,GeneNames,Ec1,Ec2,Ec3,B1,B2,B3,C1,C2,C3,...,W3,K1,K2,K3,WC1,WC2,WC3,KC1,KC2,KC3
0,WP_002614080.1,13032,13136,12917,18050,22828,16816,42888,32404,20170,...,60053,35638,38908,37314,15344,15530,27018,17185,13886,9121
1,WP_002614803.1,6817,5982,6246,15018,16718,18070,29227,34305,9713,...,69546,28536,31303,34021,19022,19870,35902,12388,22264,17843
2,WP_002633201.1,275,195,239,521,550,406,1140,727,386,...,2409,838,832,531,1110,995,1063,1841,1027,766
3,WP_002633598.1,15516,14792,13306,28206,30917,22916,64389,58243,23106,...,62136,27039,28864,34478,7962,9148,24438,4169,7524,7193
4,WP_002633601.1,4095,2680,1969,8170,8806,14771,20987,18394,9361,...,17038,13309,11109,20035,3338,2187,11373,3164,2406,4588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7184,WP_141276995.1,31,36,108,26,31,49,93,69,45,...,76,29,39,42,29,26,39,23,19,33
7185,WP_141277062.1,11,13,46,11,17,4,43,46,17,...,79,10,15,13,14,33,26,17,19,31
7186,WP_143049088.1,1332,1512,1834,2258,2340,1791,4704,5134,1659,...,13345,3235,3431,2941,4105,5714,3841,9265,5144,6080
7187,WP_143049089.1,46,26,305,79,90,72,154,115,44,...,196,89,63,71,102,60,67,100,47,93
7188,WP_143049094.1,918,2104,1781,1836,1928,1194,3263,3999,1372,...,3892,452,531,460,1444,3448,1236,264,711,468

In [12]:
DicoTable = pd.read_csv("/home/mickael/github/M_xanthus-E_coli-Predation/data/RNA_seq_DE_result/WT_vs_Ecol_ratio1_3.csv", sep = ";")
DicoTable

,gene,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,Gene_name,GeneID,orgdb_symbol,orgdb_old_MXAN,orgdb_Name
0,WP_002614080.1,"17681,5595400946","1,13148580809734","0,333820387052008","3,38950481152327","0,000700189800953942","0,00401749202195971",MXAN_RS25275,41362483.0,MXAN_RS25275,MXAN_5201,30S ribosomal protein S21
1,WP_002614803.1,"13055,8658450867","-0,279785484378841","0,341134653438939","-0,820161427630867","0,41212408777437","0,55634844891773",MXAN_RS16100,41360674.0,infA,MXAN_3321,translation initiation factor IF-1
2,WP_002633201.1,"520,781350902195","-0,488659406109829","0,310280848578043","-1,57489386905206","0,115280944069584","0,223684953832229",MXAN_RS31645,41363738.0,MXAN_RS31645,MXAN_6531,HPr family phosphocarrier protein
3,WP_002633598.1,"17667,1430239249","1,78674248251241","0,432318538781286","4,1329305181991","3,58167027156953e-05","0,000318057858780743",MXAN_RS16040,41360662.0,MXAN_RS16040,MXAN_3309,50S ribosomal protein L14
4,WP_002633601.1,"4426,40026145906","0,8104626466811","0,545743984534573","1,48506015576569","0,13752788957159","0,253668278115051",MXAN_RS16025,41360659.0,MXAN_RS16025,MXAN_3306,50S ribosomal protein L16
...,...,...,...,...,...,...,...,...,...,...,...,...
6886,WP_141276995.1,"55,5707618478865","2,38043768070863","0,546005542238998","4,35973171801004","1,30221996444244e-05","0,000133398790047742",NaN,NaN,NaN,NaN,NaN
6887,WP_141277062.1,"25,2414912393685","1,38263010290852","0,762769321629563","1,81264513884054","0,0698865710503559","0,155014402646007",NaN,NaN,NaN,NaN,NaN
6888,WP_143049088.1,"2729,23193040998","0,100695081633711","0,293071005956888","0,343585955577344","0,7311576882233","0,819386506675355",MXAN_RS19445,41361331.0,NaN,NaN,NaN
6889,WP_143049089.1,"109,891161452436","2,01788957892024","0,643239069754101","3,1370755816988","0,0017064213158805","0,008435401210712",NaN,NaN,NaN,NaN,NaN
6890,WP_143049094.1,"2090,89896910754","1,32918118754963","0,466747524468472","2,84775198125216","0,00440292229873144","0,0182225450814164",MXAN_RS37770,41364889.0,NaN,NaN,NaN

In [21]:
Dico = {}
for i in DicoTable.index:
    Dico[DicoTable.gene[i]] = DicoTable.orgdb_old_MXAN[i]

print(Dico)

{'WP_002614080.1': 'MXAN_5201', 'WP_002614803.1': 'MXAN_3321', 'WP_002633201.1': 'MXAN_6531', 'WP_002633598.1': 'MXAN_3309', 'WP_002633601.1': 'MXAN_3306', 'WP_002633602.1': 'MXAN_3305', 'WP_002633603.1': 'MXAN_3304', 'WP_002633604.1': 'MXAN_3303', 'WP_002633606.1': 'MXAN_3301', 'WP_002633607.1': 'MXAN_3300', 'WP_002633608.1': 'MXAN_3299', 'WP_002634092.1': 'MXAN_5125', 'WP_002634160.1': 'MXAN_5074', 'WP_002634235.1': 'MXAN_5002', 'WP_002634367.1': 'MXAN_5592', 'WP_002634498.1': 'MXAN_5688', 'WP_002634858.1': 'MXAN_2709', 'WP_002635080.1': 'MXAN_2913', 'WP_002635502.1': 'MXAN_1434', 'WP_002635980.1': 'MXAN_0672', 'WP_002636238.1': 'MXAN_0403', 'WP_002636478.1': 'MXAN_4033', 'WP_002636551.1': 'MXAN_4095', 'WP_002636698.1': 'MXAN_4636', 'WP_002636699.1': 'MXAN_4637', 'WP_002636736.1': 'MXAN_4673', 'WP_002637061.1': 'MXAN_2448', 'WP_002637270.1': 'MXAN_1926', 'WP_002637381.1': 'MXAN_3295', 'WP_002637840.1': 'MXAN_7512', 'WP_002638649.1': 'No old locus tag', 'WP_002639025.1': 'MXAN_2528', 'WP_002639318.1': 'No old locus tag', 'WP_002639616.1': 'MXAN_3793', 'WP_002639669.1': 'MXAN_3596', 'WP_002639727.1': 'MXAN_2978', 'WP_002640434.1': 'MXAN_4894', 'WP_002640507.1': 'MXAN_3154', 'WP_002640579.1': 'No old locus tag', 'WP_002640911.1': 'MXAN_7339', 'WP_002640925.1': 'MXAN_2457', 'WP_011550153.1': 'MXAN_0001', 'WP_011550154.1': 'MXAN_0002', 'WP_011550155.1': 'MXAN_0003', 'WP_011550156.1': 'MXAN_0004', 'WP_011550157.1': 'MXAN_0005', 'WP_011550158.1': 'MXAN_0008', 'WP_011550159.1': 'MXAN_0009', 'WP_011550160.1': 'MXAN_0010', 'WP_011550161.1': 'MXAN_0012', 'WP_011550162.1': 'MXAN_0013', 'WP_011550163.1': 'MXAN_0014', 'WP_011550164.1': 'MXAN_0015', 'WP_011550165.1': 'MXAN_0016', 'WP_011550166.1': 'MXAN_0017', 'WP_011550168.1': 'MXAN_0019', 'WP_011550169.1': 'MXAN_0020', 'WP_011550171.1': 'MXAN_0022', 'WP_011550173.1': 'MXAN_0024', 'WP_011550174.1': nan, 'WP_011550175.1': 'MXAN_0026', 'WP_011550176.1': 'MXAN_0027', 'WP_011550178.1': 'MXAN_0029', 'WP_011550179.1': 'MXAN_0030', 'WP_011550180.1': 'MXAN_0031', 'WP_011550181.1': 'MXAN_0032', 'WP_011550182.1': 'MXAN_0033', 'WP_011550183.1': 'MXAN_0034', 'WP_011550184.1': 'MXAN_0035', 'WP_011550188.1': 'MXAN_0039', 'WP_011550189.1': 'MXAN_0040', 'WP_011550190.1': 'MXAN_0041', 'WP_011550191.1': 'MXAN_0042', 'WP_011550192.1': 'MXAN_0043', 'WP_011550193.1': 'MXAN_0044', 'WP_011550194.1': 'MXAN_0045', 'WP_011550196.1': nan, 'WP_011550197.1': 'MXAN_0048', 'WP_011550198.1': 'MXAN_0049', 'WP_011550199.1': 'MXAN_0050', 'WP_011550200.1': 'MXAN_0051', 'WP_011550201.1': 'MXAN_0052', 'WP_011550202.1': 'MXAN_0053', 'WP_011550203.1': 'MXAN_0054', 'WP_011550204.1': nan, 'WP_011550205.1': 'MXAN_0056', 'WP_011550206.1': 'MXAN_0057', 'WP_011550207.1': 'MXAN_0058', 'WP_011550208.1': 'MXAN_0059', 'WP_011550209.1': 'MXAN_0060', 'WP_011550210.1': 'MXAN_0061', 'WP_011550212.1': 'MXAN_0063', 'WP_011550213.1': 'MXAN_0064', 'WP_011550217.1': 'MXAN_0070', 'WP_011550218.1': 'MXAN_0071', 'WP_011550219.1': 'MXAN_0072', 'WP_011550220.1': 'MXAN_0073', 'WP_011550221.1': 'MXAN_0074', 'WP_011550223.1': 'MXAN_0076', 'WP_011550224.1': 'MXAN_0077', 'WP_011550225.1': 'MXAN_0078', 'WP_011550226.1': 'MXAN_0079', 'WP_011550227.1': 'MXAN_0080', 'WP_011550228.1': 'MXAN_0081', 'WP_011550229.1': 'MXAN_0082', 'WP_011550230.1': 'MXAN_0083', 'WP_011550231.1': 'MXAN_0084', 'WP_011550232.1': 'MXAN_0085', 'WP_011550233.1': 'MXAN_0086', 'WP_011550234.1': 'MXAN_0087', 'WP_011550235.1': 'MXAN_0088', 'WP_011550236.1': 'MXAN_0089', 'WP_011550237.1': 'MXAN_0090', 'WP_011550239.1': 'MXAN_0092', 'WP_011550240.1': 'MXAN_0093', 'WP_011550241.1': 'MXAN_0094', 'WP_011550242.1': 'MXAN_0095', 'WP_011550243.1': 'MXAN_0096', 'WP_011550244.1': 'MXAN_0097', 'WP_011550245.1': 'MXAN_0098', 'WP_011550247.1': 'MXAN_0100', 'WP_011550248.1': 'MXAN_0101', 'WP_011550249.1': 'MXAN_0102', 'WP_011550251.1': 'MXAN_0104', 'WP_011550252.1': 'MXAN_0105', 'WP_011550254.1': 'MXAN_0107', 'WP_011550256.1': 'MXAN_0109', 'WP_011550257.1': 'MXAN_0110', 'WP_011550258.1': 'MXAN_0111', 'WP_011550259.1': 'MXAN_0112', 'WP_011550260.1': 'MXAN_0113', 'WP_011550261.1': 'MXAN_0114', 'WP_011550262.1': 'MXAN_0115', 'WP_011550263.1': 'MXAN_0116', 'WP_011550264.1': 'MXAN_0117', 'WP_011550265.1': 'MXAN_0118', 'WP_011550266.1': 'MXAN_0119', 'WP_011550267.1': 'MXAN_0120', 'WP_011550270.1': 'MXAN_0123', 'WP_011550271.1': 'MXAN_0124', 'WP_011550273.1': 'MXAN_0126', 'WP_011550275.1': 'MXAN_0128', 'WP_011550276.1': 'MXAN_0129', 'WP_011550277.1': 'MXAN_0130', 'WP_011550278.1': 'MXAN_0131', 'WP_011550279.1': 'MXAN_0133', 'WP_011550281.1': 'MXAN_0134', 'WP_011550282.1': 'MXAN_0135', 'WP_011550283.1': 'MXAN_0136', 'WP_011550284.1': 'MXAN_0137', 'WP_011550285.1': 'MXAN_0138', 'WP_011550286.1': 'MXAN_0139', 'WP_011550287.1': 'MXAN_0140', 'WP_011550288.1': 'MXAN_0141', 'WP_011550289.1': 'MXAN_0142', 'WP_011550290.1': 'MXAN_0143', 'WP_011550291.1': 'MXAN_0144', 'WP_011550292.1': 'MXAN_0145', 'WP_011550293.1': 'MXAN_0146', 'WP_011550294.1': 'MXAN_0147', 'WP_011550295.1': 'MXAN_0148', 'WP_011550298.1': 'MXAN_0151', 'WP_011550299.1': 'MXAN_0152', 'WP_011550300.1': 'MXAN_0153', 'WP_011550302.1': 'MXAN_0155', 'WP_011550303.1': 'MXAN_0156', 'WP_011550304.1': nan, 'WP_011550305.1': 'MXAN_0158', 'WP_011550306.1': 'MXAN_0159', 'WP_011550307.1': 'MXAN_0160', 'WP_011550309.1': 'MXAN_0162', 'WP_011550311.1': 'MXAN_0164', 'WP_011550312.1': 'MXAN_0165', 'WP_011550313.1': 'MXAN_0166', 'WP_011550314.1': 'MXAN_0167', 'WP_011550315.1': 'MXAN_0168', 'WP_011550317.1': 'MXAN_0170', 'WP_011550319.1': 'MXAN_0172', 'WP_011550320.1': 'MXAN_0173', 'WP_011550321.1': 'MXAN_0174', 'WP_011550322.1': 'MXAN_0175', 'WP_011550323.1': 'MXAN_0176', 'WP_011550326.1': 'MXAN_0179', 'WP_011550329.1': 'MXAN_0182', 'WP_011550330.1': 'MXAN_0183', 'WP_011550331.1': 'MXAN_0184', 'WP_011550332.1': 'MXAN_0185', 'WP_011550333.1': 'MXAN_0186', 'WP_011550334.1': 'MXAN_0188', 'WP_011550335.1': 'MXAN_0189', 'WP_011550339.1': 'MXAN_0193', 'WP_011550341.1': 'MXAN_0195', 'WP_011550342.1': 'MXAN_0196', 'WP_011550344.1': 'MXAN_0198', 'WP_011550345.1': 'MXAN_0199', 'WP_011550346.1': 'MXAN_0200', 'WP_011550347.1': 'MXAN_0201', 'WP_011550348.1': 'MXAN_0202', 'WP_011550349.1': 'MXAN_0203', 'WP_011550350.1': 'MXAN_0204', 'WP_011550351.1': 'MXAN_0205', 'WP_011550352.1': 'MXAN_0206', 'WP_011550353.1': 'MXAN_0207', 'WP_011550357.1': 'MXAN_0211', 'WP_011550358.1': 'MXAN_0212', 'WP_011550359.1': 'MXAN_0213', 'WP_011550360.1': 'MXAN_0214', 'WP_011550361.1': 'MXAN_0215', 'WP_011550363.1': 'MXAN_0217', 'WP_011550365.1': 'MXAN_0219', 'WP_011550366.1': 'MXAN_0220', 'WP_011550367.1': 'MXAN_0221', 'WP_011550368.1': 'MXAN_0222', 'WP_011550369.1': 'MXAN_0223', 'WP_011550371.1': 'MXAN_0225', 'WP_011550373.1': 'MXAN_0227', 'WP_011550374.1': 'MXAN_0228', 'WP_011550375.1': 'MXAN_0229', 'WP_011550376.1': 'MXAN_0230', 'WP_011550377.1': 'MXAN_0231', 'WP_011550378.1': 'MXAN_0232', 'WP_011550380.1': 'MXAN_0235', 'WP_011550381.1': 'MXAN_0236', 'WP_011550382.1': 'MXAN_0237', 'WP_011550383.1': 'MXAN_0238', 'WP_011550386.1': 'No old locus tag', 'WP_011550387.1': 'MXAN_0242', 'WP_011550388.1': 'MXAN_0243', 'WP_011550389.1': 'MXAN_0244', 'WP_011550390.1': 'MXAN_0245', 'WP_011550391.1': 'MXAN_0246', 'WP_011550393.1': 'MXAN_0248', 'WP_011550395.1': 'MXAN_0250', 'WP_011550396.1': 'MXAN_0251', 'WP_011550397.1': 'MXAN_0252', 'WP_011550398.1': 'MXAN_0253', 'WP_011550399.1': 'MXAN_0254', 'WP_011550400.1': 'MXAN_0255', 'WP_011550401.1': 'MXAN_0256', 'WP_011550402.1': 'MXAN_0257', 'WP_011550404.1': 'MXAN_0259', 'WP_011550405.1': 'MXAN_0260', 'WP_011550406.1': 'MXAN_0261', 'WP_011550407.1': 'MXAN_0262', 'WP_011550408.1': 'MXAN_0263', 'WP_011550409.1': 'MXAN_0264', 'WP_011550411.1': 'MXAN_0266', 'WP_011550412.1': 'MXAN_0267', 'WP_011550413.1': nan, 'WP_011550414.1': 'MXAN_0269', 'WP_011550416.1': 'MXAN_0271', 'WP_011550417.1': 'MXAN_0272', 'WP_011550418.1': 'MXAN_0273', 'WP_011550421.1': 'MXAN_0276', 'WP_011550422.1': 'MXAN_0277', 'WP_011550423.1': 'MXAN_0278', 'WP_011550424.1': 'MXAN_0279', 'WP_011550426.1': 'MXAN_0282', 'WP_011550427.1': 'MXAN_0283', 'WP_011550428.1': 'MXAN_0284', 'WP_011550429.1': 'MXAN_0285', 'WP_011550430.1': 'MXAN_0286', 'WP_011550432.1': 'MXAN_0288', 'WP_011550433.1': 'MXAN_0289', 'WP_011550434.1': 'MXAN_0290', 'WP_011550436.1': 'MXAN_0292', 'WP_011550437.1': 'MXAN_0293', 'WP_011550438.1': 'MXAN_0294', 'WP_011550439.1': 'MXAN_0295', 'WP_011550440.1': 'MXAN_0296', 'WP_011550441.1': 'MXAN_0297', 'WP_011550443.1': 'MXAN_0299', 'WP_011550444.1': 'MXAN_0300', 'WP_011550445.1': 'MXAN_0301', 'WP_011550446.1': 'MXAN_0302', 'WP_011550447.1': 'MXAN_0303', 'WP_011550448.1': 'MXAN_0304', 'WP_011550449.1': 'MXAN_0305', 'WP_011550450.1': 'MXAN_0306', 'WP_011550451.1': 'MXAN_0307', 'WP_011550452.1': 'MXAN_0308', 'WP_011550453.1': 'MXAN_0309', 'WP_011550455.1': 'MXAN_0311', 'WP_011550456.1': 'MXAN_0312', 'WP_011550457.1': 'MXAN_0313', 'WP_011550458.1': 'MXAN_0314', 'WP_011550459.1': 'MXAN_0315', 'WP_011550460.1': 'MXAN_0316', 'WP_011550461.1': 'MXAN_0317', 'WP_011550462.1': 'MXAN_0318', 'WP_011550463.1': 'MXAN_0324', 'WP_011550464.1': 'MXAN_0325', 'WP_011550465.1': 'MXAN_0326', 'WP_011550466.1': 'MXAN_0327', 'WP_011550467.1': 'MXAN_0328', 'WP_011550468.1': 'MXAN_0330', 'WP_011550469.1': 'MXAN_0331', 'WP_011550470.1': 'MXAN_0332', 'WP_011550471.1': 'MXAN_0333', 'WP_011550473.1': 'MXAN_0335', 'WP_011550474.1': 'MXAN_0336', 'WP_011550477.1': 'MXAN_0339', 'WP_011550479.1': 'MXAN_0341', 'WP_011550480.1': 'MXAN_0342', 'WP_011550481.1': 'MXAN_0343', 'WP_011550482.1': 'MXAN_0344', 'WP_011550483.1': 'MXAN_0345', 'WP_011550484.1': 'MXAN_0346', 'WP_011550486.1': 'MXAN_0348', 'WP_011550489.1': 'MXAN_0351', 'WP_011550490.1': 'MXAN_0352', 'WP_011550493.1': 'MXAN_0355', 'WP_011550496.1': 'MXAN_0358', 'WP_011550497.1': 'MXAN_0359', 'WP_011550498.1': 'MXAN_0360', 'WP_011550499.1': 'MXAN_0361', 'WP_011550501.1': 'MXAN_0363', 'WP_011550502.1': 'MXAN_0364', 'WP_011550503.1': 'MXAN_0365', 'WP_011550504.1': 'MXAN_0366', 'WP_011550506.1': 'MXAN_0368', 'WP_011550507.1': 'MXAN_0369', 'WP_011550509.1': 'MXAN_0371', 'WP_011550510.1': 'MXAN_0372', 'WP_011550512.1': 'MXAN_0374', 'WP_011550513.1': 'MXAN_0375', 'WP_011550514.1': 'MXAN_0376', 'WP_011550515.1': 'MXAN_0377', 'WP_011550516.1': nan, 'WP_011550517.1': 'MXAN_0379', 'WP_011550520.1': 'MXAN_0384', 'WP_011550522.1': 'MXAN_0386', 'WP_011550523.1': 'MXAN_0387', 'WP_011550524.1': 'MXAN_0389', 'WP_011550525.1': 'MXAN_0390', 'WP_011550526.1': 'MXAN_0391', 'WP_011550530.1': 'MXAN_0395', 'WP_011550534.1': 'MXAN_0399', 'WP_011550536.1': 'MXAN_0401', 'WP_011550539.1': 'MXAN_0405', 'WP_011550541.1': 'MXAN_0407', 'WP_011550543.1': 'MXAN_0409', 'WP_011550544.1': 'MXAN_0410', 'WP_011550545.1': 'MXAN_0411', 'WP_011550546.1': 'MXAN_0412', 'WP_011550549.1': 'MXAN_0415', 'WP_011550551.1': 'MXAN_0417', 'WP_011550552.1': 'MXAN_0418', 'WP_011550553.1': 'MXAN_0419', 'WP_011550554.1': 'MXAN_0420', 'WP_011550555.1': 'MXAN_0421', 'WP_011550556.1': 'MXAN_0422', 'WP_011550557.1': 'MXAN_0423', 'WP_011550565.1': 'MXAN_0432', 'WP_011550566.1': 'MXAN_0433', 'WP_011550567.1': 'MXAN_0434', 'WP_011550568.1': 'MXAN_0435', 'WP_011550569.1': 'MXAN_0436', 'WP_011550570.1': 'MXAN_0437', 'WP_011550571.1': 'MXAN_0438', 'WP_011550572.1': 'MXAN_0439', 'WP_011550575.1': 'MXAN_0442', 'WP_011550576.1': 'MXAN_0443', 'WP_011550577.1': 'MXAN_0444', 'WP_011550579.1': 'MXAN_0446', 'WP_011550580.1': 'MXAN_0447', 'WP_011550581.1': 'MXAN_0448', 'WP_011550584.1': 'MXAN_0451', 'WP_011550585.1': 'MXAN_0452', 'WP_011550586.1': 'MXAN_0453', 'WP_011550587.1': 'MXAN_0454', 'WP_011550588.1': 'MXAN_0455', 'WP_011550589.1': nan, 'WP_011550590.1': 'MXAN_0457', 'WP_011550591.1': 'MXAN_0458', 'WP_011550592.1': 'MXAN_0459', 'WP_011550593.1': 'MXAN_0460', 'WP_011550594.1': 'MXAN_0461', 'WP_011550595.1': 'MXAN_0462', 'WP_011550596.1': 'MXAN_0463', 'WP_011550597.1': 'MXAN_0464', 'WP_011550599.1': 'MXAN_0466', 'WP_011550600.1': 'MXAN_0467', 'WP_011550601.1': 'MXAN_0468', 'WP_011550602.1': 'MXAN_0469', 'WP_011550603.1': 'MXAN_0470', 'WP_011550604.1': 'MXAN_0471', 'WP_011550606.1': 'MXAN_0473', 'WP_011550608.1': 'MXAN_0475', 'WP_011550609.1': 'MXAN_0476', 'WP_011550610.1': 'MXAN_0477', 'WP_011550611.1': 'MXAN_0478', 'WP_011550612.1': 'MXAN_0479', 'WP_011550613.1': 'MXAN_0480', 'WP_011550614.1': 'MXAN_0481', 'WP_011550615.1': 'MXAN_0482', 'WP_011550616.1': 'MXAN_0483', 'WP_011550617.1': 'MXAN_0484', 'WP_011550618.1': 'MXAN_0485', 'WP_011550619.1': 'MXAN_0486', 'WP_011550621.1': 'MXAN_0488', 'WP_011550626.1': 'MXAN_0493', 'WP_011550627.1': 'MXAN_0494', 'WP_011550629.1': 'MXAN_0496', 'WP_011550634.1': 'MXAN_0501', 'WP_011550636.1': 'MXAN_0504', 'WP_011550637.1': nan, 'WP_011550638.1': 'MXAN_0506', 'WP_011550644.1': 'MXAN_0512', 'WP_011550646.1': 'MXAN_0513', 'WP_011550647.1': 'MXAN_0515', 'WP_011550649.1': 'MXAN_0517', 'WP_011550650.1': 'MXAN_0518', 'WP_011550653.1': 'MXAN_0521', 'WP_011550654.1': 'MXAN_0522', 'WP_011550657.1': 'MXAN_0525', 'WP_011550658.1': 'MXAN_0526', 'WP_011550659.1': 'MXAN_0527', 'WP_011550661.1': 'MXAN_0529', 'WP_011550662.1': 'MXAN_0530', 'WP_011550663.1': 'MXAN_0531', 'WP_011550664.1': 'MXAN_0532', 'WP_011550665.1': 'MXAN_0533', 'WP_011550666.1': 'MXAN_0534', 'WP_011550668.1': 'MXAN_0536', 'WP_011550669.1': 'MXAN_0537', 'WP_011550670.1': 'MXAN_0538', 'WP_011550671.1': 'MXAN_0539', 'WP_011550672.1': nan, 'WP_011550673.1': 'MXAN_0541', 'WP_011550674.1': 'MXAN_0542', 'WP_011550675.1': 'MXAN_0543', 'WP_011550676.1': 'MXAN_0544', 'WP_011550677.1': 'MXAN_0545', 'WP_011550678.1': 'MXAN_0546', 'WP_011550679.1': 'MXAN_0547', 'WP_011550680.1': 'MXAN_0548', 'WP_011550681.1': 'MXAN_0549', 'WP_011550684.1': nan, 'WP_011550686.1': 'MXAN_0554', 'WP_011550687.1': 'MXAN_0555', 'WP_011550688.1': 'MXAN_0556', 'WP_011550690.1': 'MXAN_0558', 'WP_011550691.1': 'MXAN_0559', 'WP_011550692.1': 'MXAN_0560', 'WP_011550693.1': 'MXAN_0561', 'WP_011550694.1': 'MXAN_0562', 'WP_011550696.1': 'MXAN_0564', 'WP_011550697.1': 'MXAN_0565', 'WP_011550698.1': 'MXAN_0566', 'WP_011550699.1': 'MXAN_0567', 'WP_011550704.1': 'MXAN_0572', 'WP_011550706.1': 'MXAN_0575', 'WP_011550709.1': 'MXAN_0578', 'WP_011550710.1': 'MXAN_0579', 'WP_011550712.1': 'MXAN_0581', 'WP_011550714.1': 'MXAN_0583', 'WP_011550715.1': 'MXAN_0584', 'WP_011550716.1': 'MXAN_0585', 'WP_011550717.1': 'MXAN_0586', 'WP_011550718.1': 'MXAN_0587', 'WP_011550719.1': 'MXAN_0588', 'WP_011550722.1': 'MXAN_0592', 'WP_011550725.1': 'MXAN_0594', 'WP_011550727.1': 'MXAN_0596', 'WP_011550729.1': 'MXAN_0598', 'WP_011550730.1': 'MXAN_0599', 'WP_011550732.1': 'MXAN_0601', 'WP_011550733.1': 'MXAN_0602', 'WP_011550735.1': 'MXAN_0604', 'WP_011550736.1': 'MXAN_0605', 'WP_011550738.1': 'MXAN_0607', 'WP_011550740.1': 'MXAN_0609', 'WP_011550741.1': 'MXAN_0610', 'WP_011550742.1': 'MXAN_0611', 'WP_011550743.1': 'MXAN_0612', 'WP_011550744.1': 'MXAN_0613', 'WP_011550746.1': 'MXAN_0615', 'WP_011550747.1': 'MXAN_0616', 'WP_011550748.1': 'MXAN_0617', 'WP_011550749.1': 'MXAN_0618', 'WP_011550750.1': 'MXAN_0619', 'WP_011550751.1': 'MXAN_0620', 'WP_011550752.1': 'MXAN_0621', 'WP_011550753.1': 'MXAN_0622', 'WP_011550754.1': 'MXAN_0623', 'WP_011550755.1': 'MXAN_0624', 'WP_011550756.1': 'MXAN_0625', 'WP_011550757.1': 'MXAN_0626', 'WP_011550758.1': 'MXAN_0627', 'WP_011550759.1': 'MXAN_0628', 'WP_011550760.1': 'MXAN_0629', 'WP_011550761.1': 'MXAN_0630', 'WP_011550763.1': 'MXAN_0632', 'WP_011550765.1': 'MXAN_0634', 'WP_011550766.1': 'MXAN_0635', 'WP_011550767.1': 'MXAN_0636', 'WP_011550768.1': 'MXAN_0637', 'WP_011550769.1': 'MXAN_0638', 'WP_011550770.1': 'MXAN_0639', 'WP_011550771.1': 'MXAN_0640', 'WP_011550772.1': 'MXAN_0641', 'WP_011550775.1': 'MXAN_0644', 'WP_011550776.1': 'MXAN_0645', 'WP_011550777.1': 'MXAN_0646', 'WP_011550778.1': 'MXAN_0647', 'WP_011550782.1': 'MXAN_0651', 'WP_011550783.1': 'MXAN_0652', 'WP_011550784.1': 'MXAN_0653', 'WP_011550785.1': 'MXAN_0654', 'WP_011550786.1': 'MXAN_0655', 'WP_011550788.1': nan, 'WP_011550789.1': 'MXAN_0658', 'WP_011550790.1': 'MXAN_0659', 'WP_011550791.1': 'MXAN_0660', 'WP_011550792.1': 'MXAN_0661', 'WP_011550793.1': 'MXAN_0662', 'WP_011550794.1': 'MXAN_0663', 'WP_011550795.1': 'MXAN_0664', 'WP_011550796.1': 'MXAN_0665', 'WP_011550797.1': 'MXAN_0666', 'WP_011550798.1': 'MXAN_0667', 'WP_011550799.1': 'MXAN_0668', 'WP_011550800.1': 'MXAN_0669', 'WP_011550801.1': 'MXAN_0670', 'WP_011550802.1': 'MXAN_0671', 'WP_011550804.1': 'MXAN_0674', 'WP_011550805.1': 'MXAN_0675', 'WP_011550806.1': 'MXAN_0676', 'WP_011550808.1': 'MXAN_0678', 'WP_011550809.1': 'MXAN_0679', 'WP_011550810.1': nan, 'WP_011550811.1': 'MXAN_0681', 'WP_011550812.1': 'MXAN_0682', 'WP_011550814.1': 'MXAN_0684', 'WP_011550815.1': 'MXAN_0685', 'WP_011550816.1': 'MXAN_0686', 'WP_011550820.1': 'MXAN_0690', 'WP_011550822.1': 'MXAN_0694', 'WP_011550823.1': 'MXAN_0695', 'WP_011550824.1': 'MXAN_0696', 'WP_011550827.1': 'MXAN_0699', 'WP_011550828.1': 'MXAN_0700', 'WP_011550829.1': 'MXAN_0701', 'WP_011550831.1': 'MXAN_0703', 'WP_011550832.1': 'MXAN_0704', 'WP_011550836.1': 'MXAN_0708', 'WP_011550837.1': 'MXAN_0709', 'WP_011550838.1': 'MXAN_0710', 'WP_011550839.1': 'MXAN_0711', 'WP_011550840.1': 'MXAN_0712', 'WP_011550841.1': 'MXAN_0713', 'WP_011550842.1': 'MXAN_0714', 'WP_011550843.1': 'MXAN_0715', 'WP_011550844.1': 'MXAN_0716', 'WP_011550845.1': 'MXAN_0717', 'WP_011550846.1': 'MXAN_0718', 'WP_011550848.1': 'MXAN_0720', 'WP_011550850.1': 'MXAN_0722', 'WP_011550852.1': 'MXAN_0724', 'WP_011550853.1': 'MXAN_0725', 'WP_011550855.1': 'MXAN_0729', 'WP_011550856.1': 'MXAN_0730', 'WP_011550857.1': 'MXAN_0731', 'WP_011550858.1': 'MXAN_0732', 'WP_011550859.1': 'MXAN_0733', 'WP_011550861.1': 'MXAN_0735', 'WP_011550862.1': 'MXAN_0736', 'WP_011550863.1': 'MXAN_0737', 'WP_011550864.1': 'MXAN_0738', 'WP_011550865.1': 'MXAN_0739', 'WP_011550866.1': 'MXAN_0740', 'WP_011550867.1': 'MXAN_0741', 'WP_011550868.1': 'MXAN_0742', 'WP_011550870.1': 'MXAN_0744', 'WP_011550872.1': 'MXAN_0746', 'WP_011550873.1': 'MXAN_0747', 'WP_011550874.1': 'MXAN_0748', 'WP_011550876.1': 'MXAN_0750', 'WP_011550877.1': 'MXAN_0751', 'WP_011550878.1': 'MXAN_0752', 'WP_011550880.1': 'MXAN_0754', 'WP_011550883.1': 'MXAN_0756', 'WP_011550884.1': 'MXAN_0758', 'WP_011550886.1': 'MXAN_0760', 'WP_011550887.1': 'MXAN_0761', 'WP_011550888.1': 'MXAN_0762', 'WP_011550889.1': 'MXAN_0763', 'WP_011550890.1': 'MXAN_0764', 'WP_011550891.1': 'MXAN_0765', 'WP_011550893.1': 'MXAN_0767', 'WP_011550894.1': 'MXAN_0768', 'WP_011550896.1': 'MXAN_0770', 'WP_011550897.1': 'MXAN_0771', 'WP_011550898.1': 'MXAN_0772', 'WP_011550899.1': 'MXAN_0773', 'WP_011550900.1': 'MXAN_0774', 'WP_011550901.1': 'MXAN_0775', 'WP_011550902.1': 'MXAN_0776', 'WP_011550903.1': 'MXAN_0777', 'WP_011550905.1': 'MXAN_0779', 'WP_011550907.1': 'MXAN_0781', 'WP_011550909.1': 'MXAN_0785', 'WP_011550910.1': 'MXAN_0787', 'WP_011550911.1': 'MXAN_0788', 'WP_011550913.1': 'No old locus tag', 'WP_011550914.1': 'MXAN_0791', 'WP_011550915.1': 'MXAN_0792', 'WP_011550916.1': 'MXAN_0793', 'WP_011550918.1': 'MXAN_0795', 'WP_011550919.1': 'MXAN_0796', 'WP_011550920.1': 'MXAN_0797', 'WP_011550924.1': 'MXAN_0801', 'WP_011550925.1': 'MXAN_0802', 'WP_011550927.1': 'MXAN_0804', 'WP_011550928.1': 'MXAN_0805', 'WP_011550929.1': 'MXAN_0806', 'WP_011550930.1': 'MXAN_0807', 'WP_011550931.1': 'MXAN_0808', 'WP_011550932.1': 'MXAN_0809', 'WP_011550933.1': 'MXAN_0810', 'WP_011550934.1': 'MXAN_0811', 'WP_011550935.1': 'MXAN_0812', 'WP_011550936.1': 'MXAN_0813', 'WP_011550937.1': 'MXAN_0814', 'WP_011550939.1': 'MXAN_0816', 'WP_011550940.1': 'MXAN_0817', 'WP_011550941.1': 'MXAN_0818', 'WP_011550942.1': 'MXAN_0819', 'WP_011550943.1': 'MXAN_0820', 'WP_011550944.1': 'MXAN_0821', 'WP_011550945.1': 'MXAN_0822', 'WP_011550946.1': 'MXAN_0823', 'WP_011550947.1': 'MXAN_0824', 'WP_011550948.1': 'MXAN_0825', 'WP_011550950.1': 'MXAN_0827', 'WP_011550952.1': 'MXAN_0829', 'WP_011550953.1': 'MXAN_0831', 'WP_011550954.1': 'MXAN_0832', 'WP_011550955.1': 'MXAN_0833', 'WP_011550958.1': 'MXAN_0836', 'WP_011550960.1': 'MXAN_0838', 'WP_011550961.1': 'MXAN_0839', 'WP_011550962.1': 'MXAN_0840', 'WP_011550963.1': 'MXAN_0841', 'WP_011550966.1': 'MXAN_0844', 'WP_011550967.1': 'MXAN_0845', 'WP

In [9]:
for i in DataTable.GeneNames:
    print(i)

WP_002614080.1
WP_002614803.1
WP_002633201.1
WP_002633598.1
WP_002633601.1
WP_002633602.1
WP_002633603.1
WP_002633604.1
WP_002633606.1
WP_002633607.1
WP_002633608.1
WP_002634092.1
WP_002634160.1
WP_002634235.1
WP_002634367.1
WP_002634498.1
WP_002634858.1
WP_002635080.1
WP_002635502.1
WP_002635980.1
WP_002636238.1
WP_002636478.1
WP_002636551.1
WP_002636698.1
WP_002636699.1
WP_002636736.1
WP_002637061.1
WP_002637270.1
WP_002637381.1
WP_002637840.1
WP_002638649.1
WP_002639025.1
WP_002639318.1
WP_002639616.1
WP_002639669.1
WP_002639727.1
WP_002640434.1
WP_002640507.1
WP_002640579.1
WP_002640911.1
WP_002640925.1
WP_011550153.1
WP_011550154.1
WP_011550155.1
WP_011550156.1
WP_011550157.1
WP_011550158.1
WP_011550159.1
WP_011550160.1
WP_011550161.1
WP_011550162.1
WP_011550163.1
WP_011550164.1
WP_011550165.1
WP_011550166.1
WP_011550168.1
WP_011550169.1
WP_011550171.1
WP_011550173.1
WP_011550174.1
WP_011550175.1
WP_011550176.1
WP_011550178.1
WP_011550179.1
WP_011550180.1
WP_011550181.1
WP_011550182.1
WP_011550183.1
WP_011550184.1
WP_011550185.1
WP_011550188.1
WP_011550189.1
WP_011550190.1
WP_011550191.1
WP_011550192.1
WP_011550193.1
WP_011550194.1
WP_011550196.1
WP_011550197.1
WP_011550198.1
WP_011550199.1
WP_011550200.1
WP_011550201.1
WP_011550202.1
WP_011550203.1
WP_011550204.1
WP_011550205.1
WP_011550206.1
WP_011550207.1
WP_011550208.1
WP_011550209.1
WP_011550210.1
WP_011550212.1
WP_011550213.1
WP_011550217.1
WP_011550218.1
WP_011550219.1
WP_011550220.1
WP_011550221.1
WP_011550223.1
WP_011550224.1
WP_011550225.1
WP_011550226.1
WP_011550227.1
WP_011550228.1
WP_011550229.1
WP_011550230.1
WP_011550231.1
WP_011550232.1
WP_011550233.1
WP_011550234.1
WP_011550235.1
WP_011550236.1
WP_011550237.1
WP_011550239.1
WP_011550240.1
WP_011550241.1
WP_011550242.1
WP_011550243.1
WP_011550244.1
WP_011550245.1
WP_011550247.1
WP_011550248.1
WP_011550249.1
WP_011550251.1
WP_011550252.1
WP_011550254.1
WP_011550256.1
WP_011550257.1
WP_011550258.1
WP_011550259.1
WP_011550260.1
WP_011550261.1
WP_011550262.1
WP_011550263.1
WP_011550264.1
WP_011550265.1
WP_011550266.1
WP_011550267.1
WP_011550270.1
WP_011550271.1
WP_011550273.1
WP_011550275.1
WP_011550276.1
WP_011550277.1
WP_011550278.1
WP_011550279.1
WP_011550281.1
WP_011550282.1
WP_011550283.1
WP_011550284.1
WP_011550285.1
WP_011550286.1
WP_011550287.1
WP_011550288.1
WP_011550289.1
WP_011550290.1
WP_011550291.1
WP_011550292.1
WP_011550293.1
WP_011550294.1
WP_011550295.1
WP_011550298.1
WP_011550299.1
WP_011550300.1
WP_011550302.1
WP_011550303.1
WP_011550304.1
WP_011550305.1
WP_011550306.1
WP_011550307.1
WP_011550309.1
WP_011550311.1
WP_011550312.1
WP_011550313.1
WP_011550314.1
WP_011550315.1
WP_011550317.1
WP_011550319.1
WP_011550320.1
WP_011550321.1
WP_011550322.1
WP_011550323.1
WP_011550324.1
WP_011550325.1
WP_011550326.1
WP_011550329.1
WP_011550330.1
WP_011550331.1
WP_011550332.1
WP_011550333.1
WP_011550334.1
WP_011550335.1
WP_011550339.1
WP_011550341.1
WP_011550342.1
WP_011550344.1
WP_011550345.1
WP_011550346.1
WP_011550347.1
WP_011550348.1
WP_011550349.1
WP_011550350.1
WP_011550351.1
WP_011550352.1
WP_011550353.1
WP_011550356.1
WP_011550357.1
WP_011550358.1
WP_011550359.1
WP_011550360.1
WP_011550361.1
WP_011550363.1
WP_011550365.1
WP_011550366.1
WP_011550367.1
WP_011550368.1
WP_011550369.1
WP_011550371.1
WP_011550373.1
WP_011550374.1
WP_011550375.1
WP_011550376.1
WP_011550377.1
WP_011550378.1
WP_011550380.1
WP_011550381.1
WP_011550382.1
WP_011550383.1
WP_011550384.1
WP_011550386.1
WP_011550387.1
WP_011550388.1
WP_011550389.1
WP_011550390.1
WP_011550391.1
WP_011550393.1
WP_011550395.1
WP_011550396.1
WP_011550397.1
WP_011550398.1
WP_011550399.1
WP_011550400.1
WP_011550401.1
WP_011550402.1
WP_011550404.1
WP_011550405.1
WP_011550406.1
WP_011550407.1
WP_011550408.1
WP_011550409.1
WP_011550411.1
WP_011550412.1
WP_011550413.1
WP_011550414.1
WP_011550416.1
WP_011550417.1
WP_011550418.1
WP_011550419.1
WP_011550420.1
WP_011550421.1
WP_011550422.1
WP_011550423.1
WP_011550424.1
WP_011550426.1
WP_011550427.1
WP_011550428.1
WP_011550429.1
WP_011550430.1
WP_011550432.1
WP_011550433.1
WP_011550434.1
WP_011550436.1
WP_011550437.1
WP_011550438.1
WP_011550439.1
WP_011550440.1
WP_011550441.1
WP_011550443.1
WP_011550444.1
WP_011550445.1
WP_011550446.1
WP_011550447.1
WP_011550448.1
WP_011550449.1
WP_011550450.1
WP_011550451.1
WP_011550452.1
WP_011550453.1
WP_011550455.1
WP_011550456.1
WP_011550457.1
WP_011550458.1
WP_011550459.1
WP_011550460.1
WP_011550461.1
WP_011550462.1
WP_011550463.1
WP_011550464.1
WP_011550465.1
WP_011550466.1
WP_011550467.1
WP_011550468.1
WP_011550469.1
WP_011550470.1
WP_011550471.1
WP_011550473.1
WP_011550474.1
WP_011550477.1
WP_011550479.1
WP_011550480.1
WP_011550481.1
WP_011550482.1
WP_011550483.1
WP_011550484.1
WP_011550485.1
WP_011550486.1
WP_011550489.1
WP_011550490.1
WP_011550493.1
WP_011550496.1
WP_011550497.1
WP_011550498.1
WP_011550499.1
WP_011550501.1
WP_011550502.1
WP_011550503.1
WP_011550504.1
WP_011550506.1
WP_011550507.1
WP_011550509.1
WP_011550510.1
WP_011550512.1
WP_011550513.1
WP_011550514.1
WP_011550515.1
WP_011550516.1
WP_011550517.1
WP_011550520.1
WP_011550521.1
WP_011550522.1
WP_011550523.1
WP_011550524.1
WP_011550525.1
WP_011550526.1
WP_011550530.1
WP_011550534.1
WP_011550536.1
WP_011550539.1
WP_011550541.1
WP_011550542.1
WP_011550543.1
WP_011550544.1
WP_011550545.1
WP_011550546.1
WP_011550549.1
WP_011550551.1
WP_011550552.1
WP_011550553.1
WP_011550554.1
WP_011550555.1
WP_011550556.1
WP_011550557.1
WP_011550565.1
WP_011550566.1
WP_011550567.1
WP_011550568.1
WP_011550569.1
WP_011550570.1
WP_011550571.1
WP_011550572.1
WP_011550573.1
WP_011550575.1
WP_011550576.1
WP_011550577.1
WP_011550579.1
WP_011550580.1
WP_011550581.1
WP_011550584.1
WP_011550585.1
WP_011550586.1
WP_011550587.1
WP_011550588.1
WP_011550589.1
WP_011550590.1
WP_011550591.1
WP_011550592.1
WP_011550593.1
WP_011550594.1
WP_011550595.1
WP_011550596.1
WP_011550597.1
WP_011550599.1
WP_011550600.1
WP_011550601.1
WP_011550602.1
WP_011550603.1
WP_011550604.1
WP_011550606.1
WP_011550608.1
WP_011550609.1
WP_011550610.1
WP_011550611.1
WP_011550612.1
WP_011550613.1
WP_011550614.1
WP_011550615.1
WP_011550616.1
WP_011550617.1
WP_011550618.1
WP_011550619.1
WP_011550621.1
WP_011550624.1
WP_011550626.1
WP_011550627.1
WP_011550629.1
WP_011550634.1
WP_011550636.1
WP_011550637.1
WP_011550638.1
WP_011550644.1
WP_011550646.1
WP_011550647.1
WP_011550649.1
WP_011550650.1
WP_011550653.1
WP_011550654.1
WP_011550657.1
WP_011550658.1
WP_011550659.1
WP_011550660.1
WP_011550661.1
WP_011550662.1
WP_011550663.1
WP_011550664.1
WP_011550665.1
WP_011550666.1
WP_011550668.1
WP_011550669.1
WP_011550670.1
WP_011550671.1
WP_011550672.1
WP_011550673.1
WP_011550674.1
WP_011550675.1
WP_011550676.1
WP_011550677.1
WP_011550678.1
WP_011550679.1
WP_011550680.1
WP_011550681.1
WP_011550682.1
WP_011550683.1
WP_011550684.1
WP_011550686.1
WP_011550687.1
WP_011550688.1
WP_011550689.1
WP_011550690.1
WP_011550691.1
WP_011550692.1
WP_011550693.1
WP_011550694.1
WP_011550696.1
WP_011550697.1
WP_011550698.1
WP_011550699.1
WP_011550700.1
WP_011550703.1
WP_011550704.1
WP_011550706.1
WP_011550707.1
WP_011550709.1
WP_011550710.1
WP_011550712.1
WP_011550714.1
WP_011550715.1
WP_011550716.1
WP_011550717.1
WP_011550718.1
WP_011550719.1
WP_011550720.1
WP_011550721.1
WP_011550722.1
WP_011550725.1
WP_011550727.1
WP_011550729.1
WP_011550730.1
WP_011550731.1
WP_011550732.1
WP_011550733.1
WP_011550735.1
WP_011550736.1
WP_011550738.1
WP_011550740.1
WP_011550741.1
WP_011550742.1
WP_011550743.1
WP_011550744.1
WP_011550746.1
WP_011550747.1
WP_011550748.1
WP_011550749.1
WP_011550750.1
WP_011550751.1
WP_011550752.1
WP_011550753.1
WP_011550754.1
WP_011550755.1
WP_011550756.1
WP_011550757.1
WP_011550758.1
WP_011550759.1
WP_011550760.1
WP_011550761.1
WP_011550763.1
WP_011550765.1
WP_011550766.1
WP_011550767.1
WP_011550768.1
WP_011550769.1
WP_011550770.1
WP_011550771.1
WP_011550772.1
WP_011550775.1
WP_011550776.1
WP_011550777.1
WP_011550778.1
WP_011550782.1
WP_011550783.1
WP_011550784.1
WP_011550785.1
WP_011550786.1
WP_011550788.1
WP_011550789.1
WP_011550790.1
WP_011550791.1
WP_011550792.1
WP_011550793.1
WP_011550794.1
WP_011550795.1
WP_011550796.1
WP_011550797.1
WP_011550798.1
WP_011550799.1
WP_011550800.1
WP_011550801.1
WP_011550802.1
WP_011550804.1
WP_011550805.1
WP_011550806.1
WP_011550808.1
WP_011550809.1
WP_011550810.1
WP_011550811.1
WP_011550812.1
WP_011550814.1
WP_011550815.1
WP_011550816.1
WP_011550820.1
WP_011550822.1
WP_011550823.1
WP_011550824.1
WP_011550827.1
WP_011550828.1
WP_011550829.1
WP_011550831.1
WP_011550832.1
WP_011550833.1
WP_011550836.1
WP_011550837.1
WP_011550838.1
WP_011550839.1
WP_011550840.1
WP_011550841.1
WP_011550842.1
WP_011550843.1
WP_011550844.1
WP_011550845.1
WP_011550846.1
WP_011550848.1
WP_011550850.1
WP_011550852.1
WP_011550853.1
WP_011550855.1
WP_011550856.1
WP_011550857.1
WP_011550858.1
WP_011550859.1
WP_011550861.1
WP_011550862.1
WP_011550863.1
WP_011550864.1
WP_011550865.1
WP_011550866.1
WP_011550867.1
WP_011550868.1
WP_011550870.1
WP_011550872.1
WP_011550873.1
WP_011550874.1
WP_011550876.1
WP_011550877.1
WP_011550878.1
WP_011550880.1
WP_011550883.1
WP_011550884.1
WP_011550886.1
WP_011550887.1
WP_011550888.1
WP_011550889.1
WP_011550890.1
WP_011550891.1
WP_011550893.1
WP_011550894.1
WP_011550896.1
WP_011550897.1
WP_011550898.1
WP_011550899.1
WP_011550900.1
WP_011550901.1
WP_011550902.1
WP_011550903.1
WP_011550905.1
WP_011550906.1
WP_011550907.1
WP_011550909.1
WP_011550910.1
WP_011550911.1
WP_011550913.1
WP_011550914.1
WP_011550915.1
WP_011550916.1
WP_011550918.1
WP_011550919.1
WP_011550920.1
WP_011550924.1
WP_011550925.1
WP_011550927.1
WP_011550928.1
WP_011550929.1
WP_011550930.1
WP_011550931.1
WP_011550932.1
WP_011550933.1
WP_011550934.1
WP_011550935.1
WP_011550936.1
WP_011550937.1
WP_011550939.1
WP_011550940.1
WP_011550941.1
WP_011550942.1
WP_011550943.1
WP_011550944.1
WP_011550945.1
WP_011550946.1
WP_011550947.1
WP_011550948.1
WP_011550949.1
WP_011550950.1
WP_011550952.1
WP_011550953.1
WP_011550954.1
WP_011550955.1
WP_011550958.1
WP_011550960.1
WP_011550961.1
WP_011550962.1
WP_011550963.1
WP_011550966.1
WP_011550967.1
WP_011550969.1
WP_011550970.1
WP_011550974.1
WP_011550975.1
WP_011550976.1
WP_011550977.1
WP_011550978.1
WP_011550979.1
WP_011550980.1
WP_011550981.1
WP_011550982.1
WP_011550983.1
WP_011550984.1
WP_011550985.1
WP_011550986.1
WP_011550987.1
WP_011550988.1
WP_011550989.1
WP_011550990.1
WP_011550991.1
WP_011550992.1
WP_011550993.1
WP_011550994.1
WP_011550995.1
WP_011550996.1
WP_011550997.1
WP_011550998.1
WP_011550999.1
WP_011551000.1
WP_011551001.1
WP_011551002.1
WP_011551003.1
WP_011551004.1
WP_011551005.1
WP_011551006.1
WP_011551007.1
WP_011551008.1
WP_011551009.1
WP_011551010.1
WP_011551011.1
WP_011551012.1
WP_011551014.1
WP_011551015.1
WP_011551016.1
WP_011551017.1
WP_011551018.1
WP_011551019.1
WP_011551020.1
WP_011551021.1
WP_011551022.1
WP_011551023.1
WP_011551024.1
WP_011551025.1
WP_011551026.1
WP_011551027.1
WP_011551029.1
WP_011551030.1
WP_011551031.1
WP_011551032.1
WP_011551033.1
WP_011551034.1
WP_011551035.1
WP_011551036.1
WP_011551037.1
WP_011551038.1
WP_011551039.1
WP_011551040.1
WP_011551041.1
WP_011551042.1
WP_011551043.1
WP_011551044.1
WP_011551045.1
WP_011551046.1
WP_011551047.1
WP_011551048.1
WP_011551050.1
WP_011551052.1
WP_011551053.1
WP_011551054.1
WP_011551055.1
WP_011551057.1
WP_011551058.1
WP_011551059.1
WP_011551060.1
WP_011551061.1
WP_011551062.1
WP_011551063.1
WP_011551064.1
WP_011551065.1
WP_011551066.1
WP_011551067.1
WP_011551069.1
WP_011551071.1
WP_011551072.1
WP_011551073.1
WP_011551074.1
WP_011551075.1
WP_011551076.1
WP_011551077.1
WP_011551078.1
WP_011551079.1
WP_011551080.1
WP_011551082.1
WP_011551083.1
WP_011551085.1
WP_011551086.1
WP_011551087.1
WP_011551089.1
WP_011551090.1
WP_011551091.1
WP_011551096.1
WP_011551097.1
WP_011551098.1
WP_011551099.1
WP_011551100.1
WP_011551102.1
WP_011551105.1
WP_011551106.1
WP_011551107.1
WP_011551109.1
WP_011551111.1
WP_011551112.1
WP_011551113.1
WP_011551114.1
WP_011551115.1
WP_011551116.1
WP_011551117.1
WP_011551118.1
WP_011551119.1
WP_011551121.1
WP_011551122.1
WP_011551123.1
WP_011551124.1
WP_011551125.1
WP_011551126.1
WP_011551127.1
WP_011551128.1
WP_011551130.1
WP_011551131.1
WP_011551132.1
WP_011551133.1
WP_011551134.1
WP_011551136.1
WP_011551137.1
WP_011551138.1
WP_011551139.1
WP_011551140.1
WP_011551141.1
WP_011551142.1
WP_011551143.1
WP_011551144.1
WP_011551147.1
WP_011551148.1
WP_011551149.1
WP_011551151.1
WP_011551152.1
WP_011551153.1
WP_011551154.1
WP_011551155.1
WP_011551156.1
WP_011551157.1
WP_011551158.1
WP_011551159.1
WP_011551160.1
WP_011551161.1
WP_011551162.1
WP_011551163.1
WP_011551164.1
WP_011551168.1
WP_011551169.1
WP_011551170.1
WP_011551171.1
WP_011551172.1
WP_011551173.1
WP_011551174.1
WP_011551176.1
WP_011551177.1
WP_011551178.1
WP_011551179.1
WP_011551180.1
WP_011551181.1
WP_011551182.1
WP_011551183.1
WP_011551184.1
WP_011551185.1
WP_011551186.1
WP_011551187.1
WP_011551188.1
WP_011551190.1
WP_011551191.1
WP_011551192.1
WP_011551193.1
WP_011551194.1
WP_011551195.1
WP_011551196.1
WP_011551197.1
WP_011551199.1
WP_011551200.1
WP_011551201.1
WP_011551203.1
WP_011551204.1
WP_011551205.1
WP_011551206.1
WP_011551207.1
WP_011551208.1
WP_011551209.1
WP_011551210.1
WP_011551211.1
WP_011551212.1
WP_011551215.1
WP_011551216.1
WP_011551217.1
WP_011551218.1
WP_011551219.1
WP_011551220.1
WP_011551221.1
WP_011551222.1
WP_011551223.1
WP_011551224.1
WP_011551225.1
WP_011551226.1
WP_011551227.1
WP_011551229.1
WP_011551230.1
WP_011551231.1
WP_011551232.1
WP_011551233.1
WP_011551234.1
WP_011551235.1
WP_011551236.1
WP_011551238.1
WP_011551239.1
WP_011551240.1
WP_011551242.1
WP_011551243.1
WP_011551244.1
WP_011551245.1
WP_011551246.1
WP_011551247.1
WP_011551249.1
WP_011551250.1
WP_011551252.1
WP_011551253.1
WP_011551254.1
WP_011551255.1
WP_011551256.1
WP_011551257.1
WP_011551258.1
WP_011551259.1
WP_011551260.1
WP_011551261.1
WP_011551262.1
WP_011551263.1
WP_011551264.1
WP_011551265.1
WP_011551266.1
WP_011551267.1
WP_011551268.1
WP_011551270.1
WP_011551272.1
WP_011551273.1
WP_011551274.1
WP_011551275.1
WP_011551276.1
WP_011551277.1
WP_011551279.1
WP_011551281.1
WP_011551282.1
WP_011551283.1
WP_011551284.1
WP_011551286.1
WP_011551287.1
WP_011551290.1
WP_011551291.1
WP_011551294.1
WP_011551295.1
WP_011551296.1
WP_011551297.1
WP_011551298.1
WP_011551299.1
WP_011551300.1
WP_011551301.1
WP_011551302.1
WP_011551303.1
WP_011551304.1
WP_011551305.1
WP_011551306.1
WP_011551307.1
WP_011551308.1
WP_011551310.1
WP_011551311.1
WP_011551312.1
WP_011551313.1
WP_011551316.1
WP_011551317.1
WP_011551318.1
WP_011551320.1
WP_011551321.1
WP_011551322.1
WP_011551323.1
WP_011551326.1
WP_011551330.1
WP_011551331.1
WP_011551333.1
WP_011551334.1
WP_011551335.1
WP_011551336.1
WP_011551337.1
WP_011551338.1
WP_011551339.1
WP_011551340.1
WP_011551341.1
WP_011551342.1
WP_011551344.1
WP_011551345.1
WP_011551347.1
WP_011551348.1
WP_011551349.1
WP_011551350.1
WP_011551351.1
WP_011551352.1
WP_011551353.1
WP_011551354.1
WP_011551355.1
WP_011551356.1
WP_011551357.1
WP_011551358.1
WP_011551359.1
WP_011551361.1
WP_011551362.1
WP_011551363.1
WP_011551365.1
WP_011551366.1
WP_011551367.1
WP_011551368.1
WP_011551369.1
WP_011551371.1
WP_011551372.1
WP_011551373.1
WP_011551374.1
WP_011551375.1
WP_011551376.1
WP_011551378.1
WP_011551379.1
WP_011551380.1
WP_011551381.1
WP_011551382.1
WP_011551383.1
WP_011551384.1
WP_011551385.1
WP_011551386.1
WP_011551387.1
WP_011551388.1
WP_011551389.1
WP_011551390.1
WP_011551392.1
WP_011551393.1
WP_011551394.1
WP_011551395.1
WP_011551397.1
WP_011551399.1
WP_011551400.1
WP_011551404.1
WP_011551407.1
WP_011551410.1
WP_011551411.1
WP_011551412.1
WP_011551413.1
WP_011551414.1
WP_011551415.1
WP_011551416.1
WP_011551417.1
WP_011551418.1
WP_011551419.1
WP_011551420.1
WP_011551421.1
WP_011551422.1
WP_011551424.1
WP_011551426.1
WP_011551427.1
WP_011551428.1
WP_011551429.1
WP_011551431.1
WP_011551433.1
WP_011551434.1
WP_011551435.1
WP_011551436.1
WP_011551437.1
WP_011551438.1
WP_011551440.1
WP_011551441.1
WP_011551442.1
WP_011551443.1
WP_011551444.1
WP_011551445.1
WP_011551448.1
WP_011551449.1
WP_011551450.1
WP_011551451.1
WP_011551452.1
WP_011551453.1
WP_011551454.1
WP_011551455.1
WP_011551456.1
WP_011551457.1
WP_011551458.1
WP_011551459.1
WP_011551460.1
WP_011551461.1
WP_011551462.1
WP_011551463.1
WP_011551464.1
WP_011551466.1
WP_011551467.1
WP_011551468.1
WP_011551469.1
WP_011551471.1
WP_011551472.1
WP_011551474.1
WP_011551475.1
WP_011551476.1
WP_011551477.1
WP_011551478.1
WP_011551479.1
WP_011551480.1
WP_011551481.1
WP_011551482.1
WP_011551483.1
WP_011551484.1
WP_011551485.1
WP_011551486.1
WP_011551489.1
WP_011551490.1
WP_011551491.1
WP_011551493.1
WP_011551495.1
WP_011551497.1
WP_011551499.1
WP_011551500.1
WP_011551501.1
WP_011551502.1
WP_011551503.1
WP_011551504.1
WP_011551505.1
WP_011551506.1
WP_011551507.1
WP_011551508.1
WP_011551509.1
WP_011551510.1
WP_011551511.1
WP_011551512.1
WP_011551513.1
WP_011551514.1
WP_011551516.1
WP_011551517.1
WP_011551518.1
WP_011551519.1
WP_011551520.1
WP_011551522.1
WP_011551523.1
WP_011551524.1
WP_011551525.1
WP_011551526.1
WP_011551529.1
WP_011551530.1
WP_011551531.1
WP_011551532.1
WP_011551533.1
WP_011551534.1
WP_011551535.1
WP_011551537.1
WP_011551538.1
WP_011551539.1
WP_011551540.1
WP_011551541.1
WP_011551542.1
WP_011551543.1
WP_011551544.1
WP_011551545.1
WP_011551546.1
WP_011551547.1
WP_011551549.1
WP_011551550.1
WP_011551551.1
WP_011551552.1
WP_011551554.1
WP_011551555.1
WP_011551556.1
WP_011551557.1
WP_011551558.1
WP_011551559.1
WP_011551560.1
WP_011551561.1
WP_011551562.1
WP_011551563.1
WP_011551564.1
WP_011551565.1
WP_011551566.1
WP_011551567.1
WP_011551568.1
WP_011551569.1
WP_011551570.1
WP_011551571.1
WP_011551572.1
WP_011551573.1
WP_011551574.1
WP_011551575.1
WP_011551576.1
WP_011551578.1
WP_011551579.1
WP_011551580.1
WP_011551581.1
WP_011551582.1
WP_011551584.1
WP_011551586.1
WP_011551587.1
WP_011551588.1
WP_011551590.1
WP_011551592.1
WP_011551593.1
WP_011551594.1
WP_011551595.1
WP_011551596.1
WP_011551597.1
WP_011551598.1
WP_011551599.1
WP_011551601.1
WP_011551602.1
WP_011551604.1
WP_011551606.1
WP_011551610.1
WP_011551611.1
WP_011551612.1
WP_011551614.1
WP_011551615.1
WP_011551616.1
WP_011551617.1
WP_011551618.1
WP_011551619.1
WP_011551620.1
WP_011551621.1
WP_011551622.1
WP_011551623.1
WP_011551624.1
WP_011551625.1
WP_011551626.1
WP_011551627.1
WP_011551628.1
WP_011551629.1
WP_011551631.1
WP_011551632.1
WP_011551633.1
WP_011551634.1
WP_011551635.1
WP_011551638.1
WP_011551639.1
WP_011551640.1
WP_011551641.1
WP_011551642.1
WP_011551643.1
WP_011551645.1
WP_011551646.1
WP_011551647.1
WP_011551648.1
WP_011551649.1
WP_011551651.1
WP_011551652.1
WP_011551653.1
WP_011551654.1
WP_011551655.1
WP_011551657.1
WP_011551658.1
WP_011551659.1
WP_011551660.1
WP_011551661.1
WP_011551663.1
WP_011551664.1
WP_011551665.1
WP_011551666.1
WP_011551667.1
WP_011551668.1
WP_011551670.1
WP_011551671.1
WP_011551672.1
WP_011551673.1
WP_011551674.1
WP_011551675.1
WP_011551676.1
WP_011551677.1
WP_011551678.1
WP_011551679.1
WP_011551681.1
WP_011551682.1
WP_011551683.1
WP_011551685.1
WP_011551686.1
WP_011551689.1
WP_011551690.1
WP_011551691.1
WP_011551692.1
WP_011551693.1
WP_011551696.1
WP_011551697.1
WP_011551698.1
WP_011551699.1
WP_011551700.1
WP_011551701.1
WP_011551702.1
WP_011551704.1
WP_011551705.1
WP_011551706.1
WP_011551707.1
WP_011551708.1
WP_011551709.1
WP_011551710.1
WP_011551711.1
WP_011551712.1
WP_011551713.1
WP_011551715.1
WP_011551716.1
WP_011551717.1
WP_011551719.1
WP_011551720.1
WP_011551721.1
WP_011551722.1
WP_011551723.1
WP_011551725.1
WP_011551726.1
WP_011551727.1
WP_011551728.1
WP_011551729.1
WP_011551730.1
WP_011551731.1
WP_011551732.1
WP_011551734.1
WP_011551735.1
WP_011551737.1
WP_011551738.1
WP_011551739.1
WP_011551743.1
WP_011551744.1
WP_011551747.1
WP_011551749.1
WP_011551750.1
WP_011551751.1
WP_011551752.1
WP_011551753.1
WP_011551754.1
WP_011551755.1
WP_011551756.1
WP_011551757.1
WP_011551758.1
WP_011551759.1
WP_011551760.1
WP_011551761.1
WP_011551762.1
WP_011551763.1
WP_011551764.1
WP_011551765.1
WP_011551767.1
WP_011551768.1

In [11]:
M_xanthus.genes.MAXN_4565