In [99]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import cobra
from cobra.core.configuration import Configuration
from cobra.io import read_sbml_model, write_sbml_model
from cobra.flux_analysis import flux_variability_analysis
from tqdm import tqdm

In [100]:
M_xanthus = read_sbml_model("../M_xanthus_model_V3.xml")
M_xanthus

In [101]:
M_xanthus.summary()

In [102]:
iMAT_res = pd.read_csv("/home/mickael/github/M_xanthus-E_coli-Predation/results/quantiles/iMAT/log2FoldChange/epsilon_1.0_quantiles_40_70_name.csv", sep=";", index_col="Unnamed: 0")
iMAT_res

,reaction_id,flux_value,classification,y_f,y_r
0,"2-amino-4-hydroxy-6-hydroxymethyl-7,8-dihydrop...",0.0,moderate,NaN,NaN
1,gamma-L-glutamyl-L-cysteine:glycine ligase (AD...,1.0,high,1.0,0.0
2,R07600 [c],0.0,low,1.0,0.0
3,IMP:diphosphate phospho-D-ribosyltransferase [c],0.0,moderate,NaN,NaN
4,"2,3-dihydro-2,3-dihydroxybenzoate:NAD+ oxidore...",0.0,low,1.0,0.0
...,...,...,...,...,...
1362,Exchange for D-Lactate [e],255.0,NaN,NaN,NaN
1363,Exchange for H2S2O3 [e],0.0,NaN,NaN,NaN
1364,Demand for glycogen(n-1) [c],0.0,NaN,NaN,NaN
1365,Demand for Biomass [c],0.0,NaN,NaN,NaN
1366,Demand for S-Adenosyl-4-methylthio-2-oxobutano...,0.0,NaN,NaN,NaN

In [103]:
iMAT_res_filter = iMAT_res[iMAT_res.flux_value != 0]
iMAT_res_filter

,reaction_id,flux_value,classification,y_f,y_r
1,gamma-L-glutamyl-L-cysteine:glycine ligase (AD...,1.000000,high,1.0,0.0
12,L-glutamate:L-cysteine gamma-ligase (ADP-formi...,1.000000,high,1.0,0.0
14,ATP:dCDP phosphotransferase [c],1.000000,high,1.0,0.0
26,oxalosuccinate carboxy-lyase (2-oxoglutarate-f...,501.142860,moderate,NaN,NaN
31,Sulfate adenyltransferase [c],1.000000,high,1.0,0.0
...,...,...,...,...,...
1341,Exchange for Enterobactin [e],1000.000000,NaN,NaN,NaN
1353,Exchange for NH3 [e],5.785714,NaN,NaN,NaN
1357,Exchange for Acetoacetate [e],-754.214290,NaN,NaN,NaN
1360,Exchange for O2 [e],-870.500000,NaN,NaN,NaN
1362,Exchange for D-Lactate [e],255.000000,NaN,NaN,NaN

In [104]:
# Create dictionary to convert name to id
Dico_reaction = {}
for i in M_xanthus.reactions._dict:
    Dico_reaction[M_xanthus.reactions.get_by_id(i).name] = i
print(Dico_reaction)

# create a list of reaction id that should have flux
active_list = []
for i in iMAT_res_filter["reaction_id"]:
    active_list.append(Dico_reaction[i])
print(active_list)

{'2-amino-4-hydroxy-6-hydroxymethyl-7,8-dihydropteridine-diphosphate:4-aminobenzoate 2-amino-4-hydroxydihydropteridine-6-methenyltransferase [c]': 'rxn02201_c', 'gamma-L-glutamyl-L-cysteine:glycine ligase (ADP-forming) [c]': 'rxn00351_c', 'R07600 [c]': 'rxn07431_c', 'IMP:diphosphate phospho-D-ribosyltransferase [c]': 'rxn00836_c', '2,3-dihydro-2,3-dihydroxybenzoate:NAD+ oxidoreductase [c]': 'rxn01094_c', 'acetyl-CoA:L-serine O-acetyltransferase [c]': 'rxn00423_c', 'palmitoyl-lipoteichoic acid synthesis (n=24), linked, glucose substituted [c]': 'rxn10298_c', 'ATP:CMP phosphotransferase [c]': 'rxn00364_c', 'Transport of dicarboxylates, extracellular [c]': 'rxn05561_c', 'UDP-N-acetyl-D-glucosamine:undecaprenyl-diphospho-N-acetylmuramoyl-L-alanyl-gamma-D-glutamyl-meso-2,6-diaminopimeloyl-D-alanyl-D-alanine 4-beta-N-acetylglucosaminlytransferase [c]': 'rxn03408_c', 'Isochorismate pyruvate-hydrolase [c]': 'rxn02177_c', 'FACOAL160(ISO) [c]': 'rxn05250_c', 'L-glutamate:L-cysteine gamma-ligase (ADP-forming) [c]': 'rxn00646_c', '7-methyl-trans-oct-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05440_c', 'ATP:dCDP phosphotransferase [c]': 'rxn01673_c', 'trans-4-Hydroxy-L-proline 2-epimerase [c]': 'rxn02360_c', 'R03270 [c]': 'rxn02342_c', 'ornithine transport via ABC system [c]': 'rxn05156_c', '(S)-3-Hydroxybutanoyl-CoA:NADP+ oxidoreductase [c]': 'rxn01452_c', 'GDP-mannose 4,6-hydro-lyase (GDP-4-dehydro-6-deoxy-D-mannose-forming) [c]': 'rxn00642_c', 'dTDP-4-dehydro-6-deoxy-D-glucose 3,5-epimerase [c]': 'rxn02000_c', '(S)-3-Hydroxyhexadecanoyl-CoA:NAD+ oxidoreductase [c]': 'rxn03239_c', '[Acyl-carrier-protein] acetyltransferase [c]': 'rxn05458_c', "ATP:2'-deoxy-5-hydroxymethylcytidine-5'-diphosphate phosphotransferase [c]": 'rxn00107_c', 'R05611 [c]': 'rxn12008_c', "pyridoxine 5'-phosphate synthase [c]": 'rxn04070_c', 'oxalosuccinate carboxy-lyase (2-oxoglutarate-forming) [c]': 'rxn00199_c', 'inosine:phosphate alpha-D-ribosyltransferase [c]': 'rxn01358_c', '(S)-3-Hydroxyisobutyryl-CoA hydrolase [c]': 'rxn03433_c', 'isohexadecanoyl-CDPdiacylglycerol-serine O-phosphatidyltransferase [c]': 'rxn10231_c', 'RXN0-6987.c [c]': 'rxn12637_c', 'Sulfate adenyltransferase [c]': 'rxn09240_c', 'Acetate:CoA ligase (ADP-forming) [c]': 'rxn00172_c', 'ATP:dCMP phosphotransferase [c]': 'rxn01219_c', '(3R)-3-Hydroxybutanoyl-CoA hydro-lyase [c]': 'rxn02168_c', 'N6-(1,2-dicarboxyethyl)AMP AMP-lyase (fumarate-forming) [c]': 'rxn00800_c', '1,4-dihydroxy-2-naphthoate octaprenyltransferase [c]': 'rxn08333_c', 'L-allo-threonine dehydrogenase [c]': 'rxn08172_c', "dCTP:cytidine 5'-phosphotransferase [c]": 'rxn01705_c', "(R)-4'-Phosphopantothenate:L-cysteine ligase [c]": 'rxn12512_c', 'UDP-glucose:NAD+ 6-oxidoreductase [c]': 'rxn00211_c', 'ATP:L-glutamate 5-phosphotransferase [c]': 'rxn00179_c', 'prephytoene diphosphate:geranylgeranyl-diphosphate geranylgeranyltransferase [c]': 'rxn05031_c', '10-Formyltetrahydrofolate:L-glutamate ligase (ADP-forming) [c]': 'rxn01210_c', 'acetyl-CoA:L-glutamate N-acetyltransferase [c]': 'rxn00192_c', "2'-Deoxycytidine 5'-monophosphate phosphohydrolase [c]": 'rxn01218_c', 'O-Succinylbenzoyl-CoA 1,4-dihydroxy-2-naphthoate-lyase [c]': 'rxn02898_c', 'Transport of succinate, extracellular [c]': 'rxn05654_c', '4-Hydroxybenzoate transport via proton symport [c]': 'rxn12549_c', 'ATP:D-fructose-6-phosphate 1-phosphotransferase [c]': 'rxn00545_c', 'Lysophospholipase L1 (2-acylglycerophosphoethanolamine, n-C16:1) (periplasm) [c]': 'rxn08807_c', 'L-methionine R-oxide transport via ABC system [c]': 'rxn05614_c', 'UTP:D-Tagatose 6-phosphate 1-phosphotransferase [c]': 'rxn02316_c', '3-Oxopropanoate:NAD+ oxidoreductase (decarboxylating, CoA-acetylating) [c]': 'rxn00501_c', 'stearoyl-cardiolipin synthase [c]': 'rxn10336_c', '5-Amino-2-oxopentanoate:2-oxoglutarate aminotransferase [c]': 'rxn02320_c', 'Uroporphyrinogen I carboxy-lyase [c]': 'rxn03384_c', '2-amino-4-hydroxy-6-(D-erythro-1,2,3-trihydroxypropyl)-7,8-dihydropteridine glycolaldehyde-lyase [c]': 'rxn02504_c', 'L-Aspartic acid:oxygen oxidoreductase (deaminating) [c]': 'rxn00262_c', 'R04638 [c]': 'rxn03173_c', "1-(5'-Phosphoribosyl)-5-amino-4-imidazolecarboxamide:pyrophosphate phosphoribosyltransferase [c]": 'rxn03039_c', 'isopentadecanoyl-CDPdiacylglycerol:sn-glycerol-3-phosphate 3-phosphatidyltransferase [c]': 'rxn10262_c', 'succinate dehyrdogenase [c]': 'rxn10126_c', 'anteisopentadecanoyl-glycerol-3-phosphate O-acyltransferase [c]': 'rxn10209_c', '1-tetradecanoyl-sn-glycerol 3-phosphate O-acyltransferase (n-C14:0) [c]': 'rxn08084_c', 'isohexadecanoyl-phosphatidate cytidylyltransferase [c]': 'rxn10225_c', 'trans,trans-Farnesyl-diphosphate:isopentenyl-diphosphate farnesyltranstransferase [c]': 'rxn01486_c', '15-methyl-trans-hexa-dec-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05444_c', '(3R)-3-Hydroxybutanoyl-[acyl-carrier-protein] hydro-lyase [c]': 'rxn05333_c', 'isoheptadecanoyl-glycerol-3-phosphate O-acyltransferase [c]': 'rxn10205_c', 'D-ribulose 5-phosphate formate-lyase (L-3,4-dihydroxybutan-2-one 4-phosphate-forming) [c]': 'rxn05040_c', '2-phenylacetamide amidohydrolase [c]': 'rxn01843_c', 'Lactose galactohydrolase [c]': 'rxn15230_c', 'glycerone phosphate:iminosuccinate alkyltransferase (cyclizing) [c]': 'rxn02988_c', 'S-(hydroxymethyl)glutathione dehydrogenase [c]': 'rxn04792_c', 'L-serine ammonia-lyase [c]': 'rxn00165_c', 'isotetradecanoyl-CDPdiacylglycerol-serine O-phosphatidyltransferase [c]': 'rxn10228_c', 'D-arabinose-5-phosphate aldose-ketose-isomerase [c]': 'rxn01117_c', 'diphosphate phosphohydrolase [c]': 'rxn00001_c', 'murein D,D-endopeptidase (murein4px4p) (periplasm) [c]': 'rxn08895_c', '2-Methyl-3-oxopropanoate:NAD+ oxidoreductase (CoA-propanoylating) [c]': 'rxn00671_c', 'phosphate ABC transporter permease protein [c]': 'rxn11268_c', "orotidine-5'-phosphate carboxy-lyase (UMP-forming) [c]": 'rxn00710_c', '2-methyl-4-amino-5-hydroxymethylpyrimidine-diphosphate:4-methyl-5-(2-phosphoethyl)-thiazole 2-methyl-4-aminopyridine-5-methenyltransferase [c]': 'rxn02305_c', 'R04134 [c]': 'rxn02885_c', 'Lysophospholipase L2 (2-acylglycerophosphotidate, n-C12:0) [c]': 'rxn08817_c', '5-methyltetrahydrofolate:NADP+ oxidoreductase [c]': 'rxn00910_c', 'L-Serine hydro-lyase (adding homocysteine) [c]': 'rxn00953_c', "dATP:uridine 5'-phosphotransferase [c]": 'rxn01129_c', 'diacylglycerol kinase (n-C14:1) [c]': 'rxn08296_c', 'Cytosine aminohydrolase [c]': 'rxn00717_c', 'salicin transport via PEP:Pyr PTS [c]': 'rxn05647_c', 'hypoxanthine:NAD+ oxidoreductase [c]': 'rxn01297_c', 'anteisoheptadecanoyl-Diacylglycerol kinase [c]': 'rxn10254_c', '(1S,2R)-1-C-(indol-3-yl)glycerol 3-phosphate D-glyceraldehyde-3-phosphate-lyase [c]': 'rxn01682_c', 'Lysophospholipase L1 (2-acylglycerophosphotidate, n-C12:0) (periplasm) [c]': 'rxn08796_c', 'nitrous-oxide:NAD+ oxidoreductase [c]': 'rxn01806_c', 'Maltodextrin phosphorylase (maltopentaose) [c]': 'rxn08941_c', "ATP:2,3,2',3'-tetrakis(3-hydroxytetradecanoyl)-D-glucosaminyl-beta-D-1,6-glucosaminyl-alpha-phosphate 4-O'-phosphotransferase [c]": 'rxn03181_c', 'UDP-N-acetylmuramate:L-alanyl-gamma-D-glutamyl-meso-diaminopimelate-D-alanine ligase [c]': 'rxn09360_c', 'phosphoenolpyruvate:D-arabinose-5-phosphate C-(1-carboxyvinyl)transferase (phosphate-hydrolysing, 2-carboxy-2-oxoethyl-forming) [c]': 'rxn02331_c', 'dihydrolipoylprotein:NAD+ oxidoreductase [c]': 'rxn06493_c', 'Gly-Phe aminopeptidase [c]': 'rxn12846_c', 'ATP:L-aspartate 4-phosphotransferase [c]': 'rxn00337_c', 'CDP-diacylglycerol synthetase (n-C14:1) [c]': 'rxn08308_c', '3-Hydroxy-L-kynurenine hydrolase [c]': 'rxn01930_c', "Pyridoxamine-5'-phosphate:oxygen oxidoreductase (deaminating) [c]": 'rxn00208_c', 'Lysophospholipase L2 (2-acylglycerophosphotidate, n-C18:1) [c]': 'rxn08823_c', '6-methyl-trans-oct-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05434_c', 'butyryl-[acyl-carrier protein]:malonyl-[acyl-carrier-protein] C-acyltransferase (decarboxylating) [c]': 'rxn05346_c', 'L-histidine ammonia-lyase (urocanate-forming) [c]': 'rxn00867_c', 'Hexanoyl-CoA:acetyl-CoA C-acyltransferase [c]': 'rxn03248_c', 'Amylomaltase (maltotetraose) [c]': 'rxn08127_c', '5-methyl-3-hydroxy-hexanoyl-ACP hydro-lyase [c]': 'rxn05386_c', 'Cadmium-translocating P-type ATPase [c]': 'rxn05516_c', 'O3-acetyl-L-serine:thiosulfate 2-amino-2-carboxyethyltransferase (reducing, L-cysteine-forming) [c]': 'rxn05733_c', 'L-aspartate:L-glutamine amido-ligase (AMP-forming) [c]': 'rxn00416_c', 'Phosphatidylserine syntase (n-C14:0) [c]': 'rxn09206_c', 'glutarate-semialdehyde:NAD+ oxidoreductase [c]': 'rxn01729_c', 'Maltose alpha-D-glucosylmutase [c]': 'rxn01134_c', 'R03316 [c]': 'rxn02376_c', 'acyl-[acyl-carrier-protein] synthetase  (n-C16:1) [c]': 'rxn08017_c', 'Phosphatidylserine syntase (n-C16:1) [c]': 'rxn09209_c', 'Glycerophosphodiester phosphodiesterase [c]': 'rxn08669_c', 'biotin-carboxyl-carrier-protein:carbon-dioxide ligase (ADP-forming) [c]': 'rxn06672_c', 'O3-acetyl-L-serine:hydrogen-sulfide 2-amino-2-carboxyethyltransferase [c]': 'rxn00649_c', 'ATP:shikimate 3-phosphotransferase [c]': 'rxn01739_c', 'Nicotinate D-ribonucleotide phosphohydrolase [c]': 'rxn02400_c', 'Prephenate:NAD+ oxidoreductase(decarboxylating) [c]': 'rxn01268_c', 'GTP:alpha-D-mannose-1-phosphate guanylyltransferase [c]': 'rxn00641_c', "ATP:adenylylsulfate 3'-phosphotransferase [c]": 'rxn00361_c', 'Octanoyl-CoA:oxygen 2-oxidoreductase [c]': 'rxn02679_c', 'R07603 [c]': 'rxn07434_c', 'LL-2,6-Diaminoheptanedioate 2-epimerase [c]': 'rxn01974_c', 'N-Formimino-L-glutamate iminohydrolase [c]': 'rxn01640_c', "guanosine-3',5'-bis(diphosphate) 3'-diphosphohydrolase [c]": 'rxn00242_c', 'RXN0-6977.c [c]': 'rxn12641_c', 'NADH dehydrogenase (menaquinone-8 & 0 protons) [c]': 'rxn08971_c', 'copper transport out via proton antiport [c]': 'rxn08275_c', '1-Pyrroline-4-hydroxy-2-carboxylate aminohydrolase (decyclizing) [c]': 'rxn01635_c', '5-Methylthio-5-deoxy-D-ribose-1-phosphate ketol-isomerase [c]': 'rxn03057_c', 'porphobilinogen:(4-[2-carboxyethyl]-3-[carboxymethyl]pyrrol-2-yl)methyltransferase (hydrolysing) [c]': 'rxn00060_c', 'hexanoyl-[acyl-carrier protein]:malonyl-[acyl-carrier-protein] C-acyltransferase (decarboxylating) [c]': 'rxn05350_c', 'Phosphatidylserine decarboxylase (n-C14:0) [c]': 'rxn09198_c', 'Lysophospholipase L2 (2-acylglycerophosphoethanolamine, n-C12:0) [c]': 'rxn08838_c', 'ATP:pyruvate 2-O-phosphotransferase [c]': 'rxn00148_c', 'ATP:(R)-glycerate 3-phosphotransferase [c]': 'rxn01102_c', 'D-glucosamine transport via PEP:Pyr PTS [c]': 'rxn05569_c', "ATP:dephospho-CoA 3'-phosphotransferase [c]": 'rxn00100_c', "Inosine 5'-triphosphate pyrophosphohydrolase [c]": 'rxn00514_c', '1-(5-phospho-D-ribosyl)-ATP:diphosphate phospho-alpha-D-ribosyl-transferase [c]': 'rxn00789_c', '7-methyl-3-hydroxy-octanoyl-ACP hydro-lyase [c]': 'rxn05390_c', 'D-fructose transport via PEP:Pyr PTS [c]': 'rxn05560_c', '12-methyl-trans-tetra-dec-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05437_c', 'quinone reductase [c]': 'rxn08976_c', 'D-glyceraldehyde-3-phosphate:NAD+ oxidoreductase (phosphorylating) [c]': 'rxn00781_c', 'TRANS-RXNBWI-115401.ce.maizeexp.OH_OH [c]': 'rxn05319_c', '1D-myo-Inositol 1-phosphate phosphohydrolase [c]': 'rxn00881_c', 'Na+/glutamate symport [c]': 'rxn05298_c', 'Protein-N(pai)-phosphohistidine:sugar N(pai)-phosphotransferase [c]': 'rxn06578_c', 'Propanoyl-CoA:carbon-dioxide ligase (ADP-forming) [c]': 'rxn01355_c', 'isoheptadecanoyl-cardiolipin synthase [c]': 'rxn10337_c', 'UDP-N-acetyl-D-glucosamine 2-epimerase [c]': 'rxn00297_c', 'dihydroorotic acid (menaquinone-8) [c]': 'rxn08336_c', '13-methyl-3-oxo-tetra-decanoyl-ACP:NADP+ oxidoreductase [c]': 'rxn05401_c', 'Hydroxymethylbilane hydro-lyase(cyclizing) [c]': 'rxn02264_c', 'anteisoheptadecanoyl-cardiolipin synthase [c]': 'rxn10338_c', 'Phosphatidylserine decarboxylase (n-C18:0) [c]': 'rxn09202_c', '(S)-3-Hydroxybutanoyl-CoA:NAD+ oxidoreductase [c]': 'rxn01451_c', 'UDPMurAc(oyl-L-Ala-D-gamma-Glu-L-Lys-D-Ala-D-Ala):undecaprenyl-phosphate phospho-N-acetylmuramoyl-pentapeptide-transferase [c]': 'rxn03903_c', 'ATP:AMP phosphotransferase [c]': 'rxn00097_c', 'dCMP aminohydrolase [c]': 'rxn01217_c', '2-Dehydro-3-deoxy-D-arabino-heptonate 7-phosphate phosphate-lyase (cyclyzing) [c]': 'rxn02212_c', 'ATP:alpha-D-glucose-1-phosphate adenylyltransferase [c]': 'rxn00695_c', 'Pyruvate:carbon-dioxide ligase (ADP-forming) [c]': 'rxn00250_c', 'Dodecanoyl-[acyl-carrier protein]:malonyl-CoA C-acyltransferase(decarboxylating, oxoacyl- and enoyl-reducing) [c]': 'rxn05324_c', 'Copper transport via ABC system [c]': 'rxn10481_c', 'ATP:cob(I)yrinic acid-a,c-diamide Cobeta-adenosyltransferase [c]': 'rxn03535_c', '5,10-Methylenetetrahydrofolate:glycine hydroxymethyltransferase [c]': 'rxn00692_c', 'ATP:D-fructose-1-phosphate 6-phosphotransferase [c]': 'rxn01492_c', '2-(Nomega-L-arginino)succinate arginine-lyase (fumarate-forming) [c]': 'rxn00802_c', 'lauroyl-CoA hydrolase [c]': 'rxn08440_c', 'L-Histidinol-phosphate phosphohydrolase [c]': 'rxn02160_c', 'Lysophospholipase L1 (2-acylglycerophosphotidate, n-C18:1) (periplasm) [c]': 'rxn08802_c', 'CTP:D-Tagatose 6-phosphate 1-phosphotransferase [c]': 'rxn02315_c', 'Homogentisate:oxygen 1,2-oxidoreductase (decyclizing) [c]': 'rxn01825_c', 'anteisopentadecanoyl-CDPdiacylglycerol-serine O-phosphatidyltransferase [c]': 'rxn10230_c', 'Lauroyl-CoA:(acceptor) 2,3-oxidoreductase [c]': 'rxn02720_c', "Guanosine 5'-monophosphate phosphohydrolase [c]": 'rxn00913_c', 'dTDPglucose 4,6-hydro-lyase [c]': 'rxn01997_c', 'Lysophospholipase L1 (2-acylglycerophosphoethanolamine, n-C18:1) (periplasm) [c]': 'rxn08809_c', 'UTP:pyruvate 2-O-phosphotransferase [c]': 'rxn00460_c', 'acetaldehyde:NAD+ oxidoreductase (CoA-acetylating) [c]': 'rxn00171_c', 'TRANS-RXNBWI-115531.ce [c]': 'rxn05578_c', 'Acetyl-CoA:acetyl-CoA C-acetyltransferase [c]': 'rxn00178_c', 'ATP:L-selenomethione S-adenosyltransferase [c]': 'rxn03264_c', "Orotidine-5'-phosphate:diphosphate phospho-alpha-D-ribosyl-transferase [c]": 'rxn01362_c', '2-Amino-4-hydroxy-6-(erythro-1,2,3-trihydroxypropyl) dihydropteridine triphosphate hydrolase [c]': 'rxn03174_c', 'ATP:D-glycero-beta-D-manno-heptose 7-phosphate 1-phosphotransferase [c]': 'rxn03918_c', 'nonpolar-amino-acid-transporting ATPase [c]': 'rxn05168_c', 'D-Fructose-1,6-bisphosphate 1-phosphohydrolase [c]': 'rxn00549_c', 'NAD-dependent threonine 4-phosphate dehydrogenase [c]': 'rxn03951_c', "S-methyl-5'-thioadenosine:phosphate S-methyl-5-thio-alpha-D-ribosyl-transferase [c]": 'rxn01022_c', '8-methyl-3-oxo-nonanoyl-ACP:NADP+ oxidoreductase [c]': 'rxn05418_c', 'Acetaldehyde:NAD+ oxidoreductase [c]': 'rxn00506_c', 'NAD kinase (dTTP) [c]': 'rxn10060_c', '(2S,3S)-3-hydroxy-2-methylbutanoyl-CoA:NAD+ oxidoreductase [c]': 'rxn02933_c', 'Chorismate pyruvate-lyase (amino-accepting) [c]': 'rxn00727_c', 'palmitoyl-lipoteichoic acid synthesis (n=24), linked, N-acetylglucosamine substituted [c]': 'rxn10307_c', 'mannitol transport via PEP:Pyr PTS [c]': 'rxn05617_c', 'UDP-N-acetyl-D-mannosamine:N-acetyl-beta-D-glucosaminyldiphosphoundecaprenol beta-1,4-N-acetylmannosaminyltransferase [c]': 'rxn03852_c', 'dGTP:pyruvate 2-O-phosphotransferase [c]': 'rxn01354_c', '(S)-2-methylbutanoyl-CoA:oxygen 2,3-oxidoreductase [c]': 'rxn02268_c', 'GTP:oxaloacetate carboxy-lyase (adding GTP;phosphoenolpyruvate-forming) [c]': 'rxn00305_c', "2'-Deoxyguanosine 5'-monophosphate phosphohydrolase [c]": 'rxn01445_c', 'FACOAL150(anteiso) [c]': 'rxn05248_c', 'sn-Glycerol-3-phosphate:NADP+ 2-oxidoreductase [c]': 'rxn00612_c', 'FabH [c]': 'rxn08766_c', 'oligopeptide-transporting ATPase [c]': 'rxn05539_c', 'Lysophospholipase L2 (2-acylglycerophosphoethanolamine, n-C16:0) [c]': 'rxn08841_c', '3-Hydroxyoctodecanoyl-ACP:NADP+ oxidoreductase [c]': 'rxn05461_c', 'L-Histidinol:NAD+ oxidoreductase [c]': 'rxn02159_c', 'isotetradecanoyl-phosphatidate cytidylyltransferase [c]': 'rxn10222_c', 'glycine:oxygen oxidoreductase (deaminating) [c]': 'rxn00269_c', 'anteisopentadecanoyl-CDPdiacylglycerol:sn-glycerol-3-phosphate 3-phosphatidyltransferase [c]': 'rxn10263_c', '(5-Glutamyl)-peptide:amino-acid 5-glutamyltransferase [c]': 'rxn02791_c', 'TRANS-RXN-173.ce [c]': 'rxn05466_c', 'Lysophospholipase L1 (2-acylglycerophosphoglycerol, n-C16:1) (periplasm) [c]': 'rxn08814_c', "Xanthosine-5'-phosphate:L-glutamine amido-ligase (AMP-forming) [c]": 'rxn00917_c', 'Lysophospholipase L2 (2-acylglycerophosphoglycerol, n-C12:0) [c]': 'rxn08845_c', 'L-Arginine iminohydrolase [c]': 'rxn00395_c', 'L-Kynurenine,NADPH:oxygen oxidoreductase (3-hydroxylating) [c]': 'rxn01438_c', 'GTP 7,8-8,9-dihydrolase (diphosphate-forming) [c]': 'rxn00300_c', '2-methylpropanoyl-CoA:enzyme N6-(dihydrolipoyl)lysine S-(2-methylpropanoyl)transferase [c]': 'rxn01925_c', 'Estrone 3-sulfate sulfohydrolase [c]': 'rxn02798_c', 'Phenylpyruvate:oxygen oxidoreductase (hydroxylating,decarboxylating) [c]': 'rxn00999_c', 'Lysophospholipase L1 (2-acylglycerophosphotidate, n-C16:0) (periplasm) [c]': 'rxn08799_c', 'sarcosine:oxygen oxidoreductase (demethylating) [c]': 'rxn00433_c', 'O4-succinyl-L-homoserine:hydrogen sulfide S-(3-amino-3-carboxypropyl)transferase [c]': 'rxn05957_c', '(3R)-3-Hydroxypalmitoyl-[acyl-carrier-protein] hydro-lyase [c]': 'rxn05332_c', 'formamidopyrimidine nucleoside triphosphate amidohydrolase [c]': 'rxn03419_c', 'glycerol-3-phosphate acyltransferase (C18:0) [c]': 'rxn08551_c', 'isopentadecanoyl-Diacylglycerol kinase [c]': 'rxn10256_c', 'propanoyl-CoA:oxaloacetate C-propanoyltransferase (thioester-hydrolysing, 1-carboxyethyl-forming) [c]': 'rxn00679_c', "dTTP:uridine 5'-phosphotransferase [c]": 'rxn01516_c', 'sn-Glycero-3-phosphocholine glycerophosphohydrolase [c]': 'rxn00758_c', 'anteisopentadecanoyl-lipoteichoic acid synthesis (n=24), linked, N-acetylglucosamine substituted [c]': 'rxn10314_c', 'Phosphatidylglycerol synthase (n-C16:0) [c]': 'rxn09111_c', 'O-acetyl-L-homoserine acetate-lyase (L-homocysteine forming) [c]': 'rxn06078_c', 'L-ornithine ammonia-lyase (cyclizing; L-proline-forming) [c]': 'rxn00471_c', 'maltose transport via PEP:Pyr PTS [c]': 'rxn05607_c', 'TRANS-RXN-3.ce [c]': 'rxn05595_c', 'Decanoyl-[acyl-carrier protein]:malonyl-[acyl-carrier-protein] C-acyltransferase (decarboxylating) [c]': 'rxn05348_c', '8-methyl-trans-dec-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05435_c', '(S)-Hydroxydecanoyl-CoA hydro-lyase [c]': 'rxn03245_c', '(S)-3-Hydroxy-3-methylglutaryl-CoA hydro-lyase (trans-3-methylglutaconyl-CoA-forming) [c]': 'rxn01504_c', '5,10-methylenetetrahydrofolate:NADP+ oxidoreductase [c]': 'rxn00907_c', 'diacylglycerol kinase (n-C18:1) [c]': 'rxn08300_c', '3-Deoxy-D-manno-octulosonate-8-phosphate 8-phosphohydrolase [c]': 'rxn02404_c', 'L-Aspartate-4-semialdehyde hydro-lyase (adding pyruvate and cyclizing) [c]': 'rxn01644_c', 'diacylglycerol kinase (n-C16:0) [c]': 'rxn08297_c', '(S)-3-Hydroxydodecanoyl-CoA hydro-lyase [c]': 'rxn02911_c', '14-methyl-trans-pentadec-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05450_c', 'Gly-Try aminopeptidase [c]': 'rxn12847_c', '4-methyl-3-oxo-pentanoyl-ACP:NADP+ oxidoreductase [c]': 'rxn05410_c', '13-methyl-trans-tetra-dec-2-enoyl-ACP:NAD+ oxidoreductase (A-specific) [c]': 'rxn05443_c', 'Phosphatidylglycerol synthase (n-C18:1) [c]': 'rxn09114_c', 'Proline dehydrogenase [c]': 'rxn09188_c', 'Lysophospholipase L2 (2-acylglycerophosphotidate, n-C18:0) [c]': 'rxn08822_c', 'di-trans,poly-cis-decaprenyl-diphosphate:isopentenyl-diphosphate undecaprenylcistransferase [c]': 'rxn05030_c', 'isopentadecanoyl-glycerol-3-phosphate O-acyltransferase [c]': 'rxn10208_c', 'L-Fuculose-1-phosphate lactaldehyde-lyase [c]': 'rxn01620_c', 'dodecanoyl-[acyl-carrier-protein]:malonyl-[acyl-carrier-protein] C-acyltransferase (decarboxylating) [c]': 'rxn05345_c', 'isocitrate glyoxylate-lyase (succinate-forming) [c]': 'rxn00336_c', '10-methyl-3-oxo-undecanoyl-ACP:NADP+ oxidoreductase [c]': 'rxn05422_c', 'R05612 [c]': 'rxn03891_c', '(S)-dihydroorotate amidohydrolase [c]': 'rxn01465_c', 'acyl-CoA:sn-glycerol-

Force to activate specific reaction

In [105]:
FBA = M_xanthus.optimize()
FBA.fluxes["rxn09240_c"]

np.float64(0.0)

In [137]:
# TODO add constraint that force the fluxe to pass there / Not work
M_xanthus.reactions.get_by_id("rxn09240_c")
have_flux = M_xanthus.problem.Constraint(
    M_xanthus.reactions.rxn09240_c.flux - 0,
    lb=0,
    ub=0)
M_xanthus.add_cons_vars(have_flux)

In [130]:
FBA = M_xanthus.optimize()
FBA.fluxes["rxn09240_c"]

np.float64(0.0)

Shut down all others reactions

In [110]:
for i in M_xanthus.reactions:
    if i.id not in active_list:
        i.bounds = [0,0]

M_xanthus.slim_optimize() # Didn't growth

-2.1126720371209696e-12