In [13]:
import cobra
from cobra.io import (
    load_json_model,
    save_json_model,
    load_matlab_model,
    save_matlab_model,
    read_sbml_model,
    write_sbml_model,
)
from cobra.flux_analysis import flux_variability_analysis
import numpy as np

In [14]:
M_xanthus = read_sbml_model("../M_xanthus_model_V3.xml")
M_xanthus

In [15]:
hdca_e = cobra.Metabolite(
    "hdca_e", formula="C16H31O2", name="Palmitate [e]", compartment="e"
)
M_xanthus.add_metabolites(hdca_e)  # add M_xanthus.metabolites.Biomass_e
M_xanthus.add_boundary(
    M_xanthus.metabolites.get_by_id("hdca_e"), type="exchange"
)  # add the exchange reaction for Biomass_e

MXAN_7040 = cobra.Gene(id="MXAN_7040", name="MXAN_7040", functional=True)

FAreaction = cobra.Reaction("rxn08704_c")
FAreaction.name = "Hexadecanoate transport via facilitated irreversible diffusion (extracellular to periplasm)"  # Porin (Probably) so energy independant
FAreaction.subsystem = ""
FAreaction.lower_bound = -1000.0  # This is the default
FAreaction.upper_bound = 1000.0  # This is the default
hdca_e = M_xanthus.metabolites.hdca_e
hdca_c = M_xanthus.metabolites.hdca_c
FAreaction.add_metabolites(
    {hdca_e: -1, hdca_c: 1}
)  # add the metabolites to the reaction
FAreaction.gene_reaction_rule = "MXAN_7040"  # define which gene allow the reaction
M_xanthus.add_reactions([FAreaction])  # add the PR_Biomass reaction

M_xanthus.reactions.rxn08704_c.annotation = {
    "seed.reaction": "rxn08704",
    "bigg.reaction": ["FA160tp", "HDCAt", "HDCAtex", "HDCAtexi", "U209"],
    "metanetx.reaction": "MNXR99101",
}

M_xanthus.reactions.rxn08704_c

In [16]:
liste = []
for i in M_xanthus.exchanges._dict:
    liste.append(i)
    print("M_xanthus.reactions." + i + ".lower_bound = 0")
    # print(i + ": " + M_xanthus.reactions.get_by_id(i).name)

M_xanthus.reactions.EX_malt_e.lower_bound = 0
M_xanthus.reactions.EX_his_L_e.lower_bound = 0
M_xanthus.reactions.EX_cd2_e.lower_bound = 0
M_xanthus.reactions.EX_ferrich_e.lower_bound = 0
M_xanthus.reactions.EX_tttnt_e.lower_bound = 0
M_xanthus.reactions.EX_metox_e.lower_bound = 0
M_xanthus.reactions.EX_btn_e.lower_bound = 0
M_xanthus.reactions.EX_met_L_e.lower_bound = 0
M_xanthus.reactions.EX_mg2_e.lower_bound = 0
M_xanthus.reactions.EX_ac_e.lower_bound = 0
M_xanthus.reactions.EX_arsenb_e.lower_bound = 0
M_xanthus.reactions.EX_cbl1_e.lower_bound = 0
M_xanthus.reactions.EX_cgly_e.lower_bound = 0
M_xanthus.reactions.EX_fum_e.lower_bound = 0
M_xanthus.reactions.EX_h2s_e.lower_bound = 0
M_xanthus.reactions.EX_so4_e.lower_bound = 0
M_xanthus.reactions.EX_pydx_e.lower_bound = 0
M_xanthus.reactions.EX_spmd_e.lower_bound = 0
M_xanthus.reactions.EX_ppi_e.lower_bound = 0
M_xanthus.reactions.EX_mnl_e.lower_bound = 0
M_xanthus.reactions.EX_pro_L_e.lower_bound = 0
M_xanthus.reactions.EX_glyc3p_e.lower_bound = 0
M_xanthus.reactions.EX_orn_e.lower_bound = 0
M_xanthus.reactions.EX_salcn_e.lower_bound = 0
M_xanthus.reactions.EX_pi_e.lower_bound = 0
M_xanthus.reactions.EX_acgam_e.lower_bound = 0
M_xanthus.reactions.EX_pyr_e.lower_bound = 0
M_xanthus.reactions.EX_etoh_e.lower_bound = 0
M_xanthus.reactions.EX_but_e.lower_bound = 0
M_xanthus.reactions.EX_hom_L_e.lower_bound = 0
M_xanthus.reactions.EX_na1_e.lower_bound = 0
M_xanthus.reactions.EX_acald_e.lower_bound = 0
M_xanthus.reactions.EX_mobd_e.lower_bound = 0
M_xanthus.reactions.EX_metox_R_e.lower_bound = 0
M_xanthus.reactions.EX_arbt_e.lower_bound = 0
M_xanthus.reactions.EX_sucr_e.lower_bound = 0
M_xanthus.reactions.EX_galt_e.lower_bound = 0
M_xanthus.reactions.EX_glyb_e.lower_bound = 0
M_xanthus.reactions.EX_leu_L_e.lower_bound = 0
M_xanthus.reactions.EX_h2o_e.lower_bound = 0
M_xanthus.reactions.EX_so3_e.lower_bound = 0
M_xanthus.reactions.EX_h2_e.lower_bound = 0
M_xanthus.reactions.EX_lys_L_e.lower_bound = 0
M_xanthus.reactions.EX_k_e.lower_bound = 0
M_xanthus.reactions.EX_n2o_e.lower_bound = 0
M_xanthus.reactions.EX_cu2_e.lower_bound = 0
M_xanthus.reactions.EX_Fe3_e.lower_bound = 0
M_xanthus.reactions.EX_fru_e.lower_bound = 0
M_xanthus.reactions.EX_gam_e.lower_bound = 0
M_xanthus.reactions.EX_gly_cys_L_e.lower_bound = 0
M_xanthus.reactions.EX_alaala_e.lower_bound = 0
M_xanthus.reactions.EX_co2_e.lower_bound = 0
M_xanthus.reactions.EX_h_e.lower_bound = 0
M_xanthus.reactions.EX_ca2_e.lower_bound = 0
M_xanthus.reactions.EX_zn2_e.lower_bound = 0
M_xanthus.reactions.EX_cl_e.lower_bound = 0
M_xanthus.reactions.EX_tre_e.lower_bound = 0
M_xanthus.reactions.EX_thr_L_e.lower_bound = 0
M_xanthus.reactions.EX_pheme_e.lower_bound = 0
M_xanthus.reactions.EX_glu_L_e.lower_bound = 0
M_xanthus.reactions.EX_feenter_e.lower_bound = 0
M_xanthus.reactions.EX_mn2_e.lower_bound = 0
M_xanthus.reactions.EX_malthx_e.lower_bound = 0
M_xanthus.reactions.EX_enter_e.lower_bound = 0
M_xanthus.reactions.EX_malttr_e.lower_bound = 0
M_xanthus.reactions.EX_arsni_e.lower_bound = 0
M_xanthus.reactions.EX_4hbz_e.lower_bound = 0
M_xanthus.reactions.EX_Butyro_betaine_e.lower_bound = 0
M_xanthus.reactions.EX_man_e.lower_bound = 0
M_xanthus.reactions.EX_chitob_e.lower_bound = 0
M_xanthus.reactions.EX_for_e.lower_bound = 0
M_xanthus.reactions.EX_mal_D_e.lower_bound = 0
M_xanthus.reactions.EX_adocbl_e.lower_bound = 0
M_xanthus.reactions.EX_meoh_e.lower_bound = 0
M_xanthus.reactions.EX_succ_e.lower_bound = 0
M_xanthus.reactions.EX_nh4_e.lower_bound = 0
M_xanthus.reactions.EX_ile_L_e.lower_bound = 0
M_xanthus.reactions.EX_cobalt2_e.lower_bound = 0
M_xanthus.reactions.EX_glc_D_e.lower_bound = 0
M_xanthus.reactions.EX_acac_e.lower_bound = 0
M_xanthus.reactions.EX_val_L_e.lower_bound = 0
M_xanthus.reactions.EX_no_e.lower_bound = 0
M_xanthus.reactions.EX_o2_e.lower_bound = 0
M_xanthus.reactions.EX_lac_D_e.lower_bound = 0
M_xanthus.reactions.EX_tsul_e.lower_bound = 0
M_xanthus.reactions.EX_hdca_e.lower_bound = 0

In [17]:
M_xanthus.summary()

In [18]:
## NON ESSENTIAL METABOLITES
M_xanthus.reactions.EX_malt_e.lower_bound = 0
M_xanthus.reactions.EX_his_L_e.lower_bound = 0
M_xanthus.reactions.EX_cd2_e.lower_bound = 0
M_xanthus.reactions.EX_ferrich_e.lower_bound = 0
M_xanthus.reactions.EX_tttnt_e.lower_bound = 0
M_xanthus.reactions.EX_metox_e.lower_bound = 0
M_xanthus.reactions.EX_btn_e.lower_bound = 0
M_xanthus.reactions.EX_met_L_e.lower_bound = 0
M_xanthus.reactions.EX_ac_e.lower_bound = 0
M_xanthus.reactions.EX_arsenb_e.lower_bound = 0
M_xanthus.reactions.EX_cbl1_e.lower_bound = 0
M_xanthus.reactions.EX_cgly_e.lower_bound = 0
M_xanthus.reactions.EX_fum_e.lower_bound = 0
M_xanthus.reactions.EX_ppi_e.lower_bound = 0
M_xanthus.reactions.EX_mnl_e.lower_bound = 0
M_xanthus.reactions.EX_pro_L_e.lower_bound = 0
M_xanthus.reactions.EX_glyc3p_e.lower_bound = 0
M_xanthus.reactions.EX_orn_e.lower_bound = 0
M_xanthus.reactions.EX_salcn_e.lower_bound = 0
M_xanthus.reactions.EX_acgam_e.lower_bound = 0
M_xanthus.reactions.EX_pyr_e.lower_bound = 0
M_xanthus.reactions.EX_etoh_e.lower_bound = 0
M_xanthus.reactions.EX_but_e.lower_bound = 0
M_xanthus.reactions.EX_hom_L_e.lower_bound = 0
M_xanthus.reactions.EX_na1_e.lower_bound = 0
M_xanthus.reactions.EX_acald_e.lower_bound = 0
M_xanthus.reactions.EX_mobd_e.lower_bound = 0
M_xanthus.reactions.EX_metox_R_e.lower_bound = 0
M_xanthus.reactions.EX_arbt_e.lower_bound = 0
M_xanthus.reactions.EX_sucr_e.lower_bound = 0
M_xanthus.reactions.EX_galt_e.lower_bound = 0
M_xanthus.reactions.EX_glyb_e.lower_bound = 0
M_xanthus.reactions.EX_h2o_e.lower_bound = 0
M_xanthus.reactions.EX_so3_e.lower_bound = 0
M_xanthus.reactions.EX_h2_e.lower_bound = 0
M_xanthus.reactions.EX_lys_L_e.lower_bound = 0
M_xanthus.reactions.EX_n2o_e.lower_bound = 0
M_xanthus.reactions.EX_feenter_e.lower_bound = 0
M_xanthus.reactions.EX_fru_e.lower_bound = 0
M_xanthus.reactions.EX_gam_e.lower_bound = 0
M_xanthus.reactions.EX_gly_cys_L_e.lower_bound = 0
M_xanthus.reactions.EX_alaala_e.lower_bound = 0
M_xanthus.reactions.EX_co2_e.lower_bound = 0
M_xanthus.reactions.EX_h_e.lower_bound = 0
M_xanthus.reactions.EX_tre_e.lower_bound = 0
M_xanthus.reactions.EX_thr_L_e.lower_bound = 0
M_xanthus.reactions.EX_pheme_e.lower_bound = 0
M_xanthus.reactions.EX_glu_L_e.lower_bound = 0
M_xanthus.reactions.EX_malthx_e.lower_bound = 0
M_xanthus.reactions.EX_enter_e.lower_bound = 0
M_xanthus.reactions.EX_malttr_e.lower_bound = 0
M_xanthus.reactions.EX_arsni_e.lower_bound = 0
M_xanthus.reactions.EX_4hbz_e.lower_bound = 0
M_xanthus.reactions.EX_Butyro_betaine_e.lower_bound = 0
M_xanthus.reactions.EX_man_e.lower_bound = 0
M_xanthus.reactions.EX_chitob_e.lower_bound = 0
M_xanthus.reactions.EX_for_e.lower_bound = 0
M_xanthus.reactions.EX_mal_D_e.lower_bound = 0
M_xanthus.reactions.EX_adocbl_e.lower_bound = 0
M_xanthus.reactions.EX_meoh_e.lower_bound = 0
M_xanthus.reactions.EX_succ_e.lower_bound = 0
M_xanthus.reactions.EX_glc_D_e.lower_bound = 0
M_xanthus.reactions.EX_acac_e.lower_bound = 0
M_xanthus.reactions.EX_no_e.lower_bound = 0
M_xanthus.reactions.EX_lac_D_e.lower_bound = 0
M_xanthus.reactions.EX_tsul_e.lower_bound = 0

## ESSENTIAL METABOLITES
M_xanthus.reactions.EX_mg2_e.lower_bound = -1000
M_xanthus.reactions.EX_h2s_e.lower_bound = -1000
M_xanthus.reactions.EX_so4_e.lower_bound = -1000
M_xanthus.reactions.EX_pydx_e.lower_bound = -1000
M_xanthus.reactions.EX_spmd_e.lower_bound = -1000
M_xanthus.reactions.EX_pi_e.lower_bound = -1000
M_xanthus.reactions.EX_leu_L_e.lower_bound = -1000
M_xanthus.reactions.EX_k_e.lower_bound = -1000
M_xanthus.reactions.EX_cu2_e.lower_bound = -1000
M_xanthus.reactions.EX_ca2_e.lower_bound = -1000
M_xanthus.reactions.EX_zn2_e.lower_bound = -1000
M_xanthus.reactions.EX_cl_e.lower_bound = -1000
M_xanthus.reactions.EX_Fe3_e.lower_bound = -1000
M_xanthus.reactions.EX_mn2_e.lower_bound = -1000
M_xanthus.reactions.EX_nh4_e.lower_bound = -1000
M_xanthus.reactions.EX_ile_L_e.lower_bound = -1000
M_xanthus.reactions.EX_cobalt2_e.lower_bound = -1000
M_xanthus.reactions.EX_val_L_e.lower_bound = -1000
M_xanthus.reactions.EX_o2_e.lower_bound = -1000
M_xanthus.reactions.EX_hdca_e.lower_bound = -1000

In [19]:
FBA = M_xanthus.optimize()
FBA.objective_value

52.53170827312301

In [20]:
M_xanthus.summary()

In [21]:
FVA = flux_variability_analysis(
    M_xanthus,
)

for i in liste:
    if FVA.loc[i][0] < 0:
        rdm = np.random.uniform(
            FVA.loc[i][0], FVA.loc[i][1]
        )  # get a random value between two point
        print(i + ": " + "\n" + "random   " + str(rdm) + "\n" + str(FVA.loc[i]))

EX_mg2_e:
random   -0.08405286930449299
minimum   -0.084053
maximum   -0.084053
Name: EX_mg2_e, dtype: float64
EX_h2s_e:
random   -12.081636828150188
minimum   -12.081637
maximum   -12.081637
Name: EX_h2s_e, dtype: float64
EX_so4_e:
random   -0.08405286857343972
minimum   -0.084053
maximum   -0.084053
Name: EX_so4_e, dtype: float64
EX_pydx_e:
random   -0.08405286917030036
minimum   -0.084053
maximum   -0.084053
Name: EX_pydx_e, dtype: float64
EX_spmd_e:
random   -0.08405286930452449
minimum   -0.084053
maximum   -0.084053
Name: EX_spmd_e, dtype: float64
EX_pi_e:
random   -34.72186376124158
minimum   -34.721864
maximum   -34.721864
Name: EX_pi_e, dtype: float64
EX_leu_L_e:
random   -19.032956572479225
minimum   -19.032957
maximum   -19.032957
Name: EX_leu_L_e, dtype: float64
EX_k_e:
random   -0.0840528693045923
minimum   -0.084053
maximum   -0.084053
Name: EX_k_e, dtype: float64
EX_cu2_e:
random   -0.08405286930460511
minimum   -0.084053
maximum   -0.084053
Name: EX_cu2_e, dtype: float64
EX_Fe3_e:
random   -0.3362114772179641
minimum   -0.336211
maximum   -0.336211
Name: EX_Fe3_e, dtype: float64
EX_ca2_e:
random   -0.08405286930451306
minimum   -0.084053
maximum   -0.084053
Name: EX_ca2_e, dtype: float64
EX_zn2_e:
random   -0.08405286930448887
minimum   -0.084053
maximum   -0.084053
Name: EX_zn2_e, dtype: float64
EX_cl_e:
random   -0.08405286930451852
minimum   -0.084053
maximum   -0.084053
Name: EX_cl_e, dtype: float64
EX_mn2_e:
random   -0.08405286930449582
minimum   -0.084053
maximum   -0.084053
Name: EX_mn2_e, dtype: float64
EX_nh4_e:
random   -371.5360106664658
minimum   -371.536011
maximum   -371.536011
Name: EX_nh4_e, dtype: float64
EX_ile_L_e:
random   -12.259662419519884
minimum   -12.259662
maximum   -12.259662
Name: EX_ile_L_e, dtype: float64
EX_cobalt2_e:
random   -0.08405286930447384
minimum   -0.084053
maximum   -0.084053
Name: EX_cobalt2_e, dtype: float64
EX_val_L_e:
random   -18.027024659124237
minimum   -18.027025
maximum   -18.027025
Name: EX_val_L_e, dtype: float64
EX_o2_e:
random   -888.4990387258724
minimum   -1000.000000
maximum    -600.366691
Name: EX_o2_e, dtype: float64
EX_tsul_e:
random   -9.749994450823123e-10
minimum   -1.717635e-09
maximum    0.000000e+00
Name: EX_tsul_e, dtype: float64
EX_hdca_e:
random   -106.03030344781496
minimum   -156.684526
maximum    -99.594053
Name: EX_hdca_e, dtype: float64

/tmp/ipykernel_1496862/604500475.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if FVA.loc[i][0] < 0:
/tmp/ipykernel_1496862/604500475.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  rdm = np.random.uniform(FVA.loc[i][0], FVA.loc[i][1]) # get a random value between two point

In [22]:
np.random.uniform(
    FVA.loc["EX_hdca_e"][0], FVA.loc["EX_hdca_e"][1]
)  # get a random value between two point

/tmp/ipykernel_1496862/3797060294.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  np.random.uniform(FVA.loc["EX_hdca_e"][0], FVA.loc["EX_hdca_e"][1]) # get a random value between two point

-105.0340609528256

In [23]:
round(0.055555555, 1)

0.1